"""
Bootcamp v3.0 Seed Data - 15 Modules in 4 Tracks
Phase C.1: Seed Bootcamp v3.0 Content (Redo)

Source: docs/bootcamp/bootcamp_v3.0.md

Structure:
- 4 Tracks
- 15 Modules (~200-300 hours total)
- 60+ Labs
- 15+ Projects
"""
from typing import Literal, Optional

DifficultyLevel = Literal["beginner", "intermediate", "advanced", "expert"]


# =============================================================================
# TRACK DEFINITIONS
# =============================================================================

BOOTCAMP_TRACKS: list[dict] = [
    {
        "name": "Foundation",
        "slug": "foundation",
        "description": "Build your core DevOps skills with Linux, scripting, Git, and Python",
        "color": "#6366f1",  # Indigo
        "icon": "🏗️",
        "order_index": 1,
    },
    {
        "name": "Cloud & Infrastructure",
        "slug": "cloud-infrastructure",
        "description": "Master AWS services, Terraform, serverless architecture, and security",
        "color": "#8b5cf6",  # Purple
        "icon": "☁️",
        "order_index": 2,
    },
    {
        "name": "Containers & Orchestration",
        "slug": "containers-orchestration",
        "description": "Learn Docker containerization and Kubernetes orchestration",
        "color": "#06b6d4",  # Cyan
        "icon": "🐳",
        "order_index": 3,
    },
    {
        "name": "Platform Engineering",
        "slug": "platform-engineering",
        "description": "Advanced Kubernetes, GitOps, observability, and SRE practices",
        "color": "#f97316",  # Orange
        "icon": "🚀",
        "order_index": 4,
    },
]


# =============================================================================
# MODULE DEFINITIONS
# =============================================================================

BOOTCAMP_MODULES: list[dict] = [
    # =========================================================================
    # TRACK 1: FOUNDATION (Modules 01-05)
    # =========================================================================
    {
        "track_slug": "foundation",
        "order_index": 1,
        "name": "Environment & Tooling Setup",
        "slug": "environment-tooling-setup",
        "description": "Establish a professional development environment identical to enterprise standards. Build the foundation for the entire bootcamp.",
        "difficulty": "beginner",
        "estimated_hours": 10.0,
        "prerequisites": [],
        "tasks": [
            {"title": "macOS vs Linux for DevOps work", "difficulty": "easy"},
            {"title": "Terminal emulators (iTerm2, Alacritty)", "difficulty": "easy"},
            {"title": "Shell selection (zsh, bash) and configuration", "difficulty": "easy"},
            {"title": "Package managers (Homebrew, apt, yum)", "difficulty": "easy"},
            {"title": "VS Code with DevOps extensions", "difficulty": "easy"},
            {"title": "Docker Desktop installation", "difficulty": "easy"},
            {"title": "Git and GitHub CLI setup", "difficulty": "easy"},
            {"title": "AWS CLI v2 installation", "difficulty": "medium"},
            {"title": "Terraform installation", "difficulty": "medium"},
            {"title": "kubectl installation", "difficulty": "medium"},
            {"title": "Python 3.11+ setup", "difficulty": "easy"},
            {"title": "SSH key generation and management", "difficulty": "medium"},
            {"title": "GPG signing for commits", "difficulty": "medium"},
            {"title": "MFA setup for all services", "difficulty": "medium"},
            {"title": "Create personal dotfiles repository", "difficulty": "medium"},
            {"title": "Shell aliases and functions", "difficulty": "medium"},
            {"title": "Environment variables management", "difficulty": "medium"},
        ],
        "labs": [
            {"title": "Terminal Power User Setup", "slug": "lab-1-1-terminal-setup", "hours": 2.0},
            {"title": "Complete Tool Chain Installation", "slug": "lab-1-2-tool-chain", "hours": 3.0},
            {"title": "SSH & Security Configuration", "slug": "lab-1-3-ssh-security", "hours": 2.0},
            {"title": "Dotfiles Repository Creation", "slug": "lab-1-4-dotfiles", "hours": 2.0},
        ],
        "project": {
            "title": "Development Environment as Code",
            "slug": "project-dev-environment-as-code",
            "description": "Create an automated setup script that installs your entire development environment on a new machine within 30 minutes.",
            "deliverables": [
                "Dotfiles repository on GitHub",
                "Automated setup script (bootstrap.sh)",
                "Tool verification checklist",
                "Environment documentation",
            ],
            "xp_reward": 500,
            "estimated_hours": 5.0,
        },
    },
    {
        "track_slug": "foundation",
        "order_index": 2,
        "name": "Linux Mastery",
        "slug": "linux-mastery",
        "description": "Deep understanding of Linux as the foundation for all DevOps infrastructure. Learn not just commands — understand why things work.",
        "difficulty": "intermediate",
        "estimated_hours": 20.0,
        "prerequisites": ["environment-tooling-setup"],
        "tasks": [
            {"title": "Filesystem Hierarchy Standard (FHS)", "difficulty": "medium"},
            {"title": "Mount points and device files", "difficulty": "medium"},
            {"title": "Inodes, hard links, symbolic links", "difficulty": "medium"},
            {"title": "Disk management (fdisk, lvm, df, du)", "difficulty": "hard"},
            {"title": "File permissions (chmod, chown, umask, ACLs)", "difficulty": "medium"},
            {"title": "Process lifecycle and states", "difficulty": "medium"},
            {"title": "Foreground vs background processes", "difficulty": "medium"},
            {"title": "Job control (jobs, fg, bg, nohup)", "difficulty": "medium"},
            {"title": "Signals (SIGTERM, SIGKILL, SIGHUP)", "difficulty": "medium"},
            {"title": "Process monitoring (ps, top, htop, pgrep)", "difficulty": "medium"},
            {"title": "Systemd architecture", "difficulty": "hard"},
            {"title": "Unit files (service, timer, socket)", "difficulty": "hard"},
            {"title": "Service management (systemctl)", "difficulty": "medium"},
            {"title": "Boot process and targets", "difficulty": "hard"},
            {"title": "Journald and logging", "difficulty": "medium"},
            {"title": "User/group management", "difficulty": "medium"},
            {"title": "sudo configuration", "difficulty": "medium"},
            {"title": "PAM modules", "difficulty": "hard"},
            {"title": "SSH hardening", "difficulty": "hard"},
            {"title": "Firewall basics (ufw, iptables)", "difficulty": "hard"},
            {"title": "grep, sed, awk mastery", "difficulty": "hard"},
            {"title": "cut, sort, uniq, tr", "difficulty": "medium"},
            {"title": "xargs and command substitution", "difficulty": "hard"},
            {"title": "Regular expressions", "difficulty": "hard"},
            {"title": "Network interfaces (ip, ifconfig)", "difficulty": "medium"},
            {"title": "DNS resolution (dig, nslookup)", "difficulty": "medium"},
            {"title": "Socket inspection (ss, netstat)", "difficulty": "medium"},
            {"title": "Traffic analysis (tcpdump basics)", "difficulty": "hard"},
        ],
        "labs": [
            {"title": "Filesystem Exploration Challenge", "slug": "lab-2-1-filesystem", "hours": 3.0},
            {"title": "Process Detective", "slug": "lab-2-2-processes", "hours": 2.0},
            {"title": "Systemd Service Creation", "slug": "lab-2-3-systemd", "hours": 3.0},
            {"title": "User Security Hardening", "slug": "lab-2-4-security", "hours": 2.0},
            {"title": "Text Processing Olympics", "slug": "lab-2-5-text-processing", "hours": 4.0},
            {"title": "Network Troubleshooting", "slug": "lab-2-6-networking", "hours": 3.0},
        ],
        "project": {
            "title": "Linux System Administration",
            "slug": "project-linux-sysadmin",
            "description": "Configure a Linux server from scratch with hardened SSH, custom systemd services, log rotation, automated backups, and monitoring scripts.",
            "deliverables": [
                "Server configuration documentation",
                "Security hardening checklist",
                "Custom systemd unit files",
                "System monitoring script",
            ],
            "xp_reward": 750,
            "estimated_hours": 8.0,
        },
    },
    {
        "track_slug": "foundation",
        "order_index": 3,
        "name": "Shell Scripting & Automation",
        "slug": "shell-scripting-automation",
        "description": "Transform manual processes into automated, reliable scripts. Build tools that save hours of work.",
        "difficulty": "intermediate",
        "estimated_hours": 20.0,
        "prerequisites": ["linux-mastery"],
        "tasks": [
            {"title": "Shebang and script execution", "difficulty": "easy"},
            {"title": "Variables (local, global, environment)", "difficulty": "medium"},
            {"title": "Quoting rules (single, double, backticks)", "difficulty": "medium"},
            {"title": "Exit codes and error handling", "difficulty": "medium"},
            {"title": "set options (-e, -u, -x, -o pipefail)", "difficulty": "medium"},
            {"title": "Conditionals (if, case, [[]])", "difficulty": "medium"},
            {"title": "Loops (for, while, until)", "difficulty": "medium"},
            {"title": "Functions and return values", "difficulty": "medium"},
            {"title": "Traps and signal handling", "difficulty": "hard"},
            {"title": "Subshells and command grouping", "difficulty": "hard"},
            {"title": "Here documents and here strings", "difficulty": "medium"},
            {"title": "Process substitution", "difficulty": "hard"},
            {"title": "Arrays (indexed, associative)", "difficulty": "hard"},
            {"title": "String manipulation", "difficulty": "medium"},
            {"title": "Arithmetic operations", "difficulty": "medium"},
            {"title": "Log monitoring and alerting", "difficulty": "hard"},
            {"title": "Backup automation", "difficulty": "hard"},
            {"title": "System health checks", "difficulty": "medium"},
            {"title": "User provisioning scripts", "difficulty": "hard"},
            {"title": "Deployment scripts", "difficulty": "hard"},
            {"title": "ShellCheck for linting", "difficulty": "easy"},
            {"title": "Unit testing with BATS", "difficulty": "hard"},
        ],
        "labs": [
            {"title": "Bash Fundamentals Exercises", "slug": "lab-3-1-bash-fundamentals", "hours": 3.0},
            {"title": "Control Flow Challenges", "slug": "lab-3-2-control-flow", "hours": 3.0},
            {"title": "Log Monitor with Email Alerts", "slug": "lab-3-3-log-monitor", "hours": 4.0},
            {"title": "Automated Backup System", "slug": "lab-3-4-backup-system", "hours": 3.0},
            {"title": "System Health Dashboard", "slug": "lab-3-5-health-dashboard", "hours": 4.0},
        ],
        "project": {
            "title": "DevOps Automation Toolkit",
            "slug": "project-automation-toolkit",
            "description": "Create a complete toolkit with server provisioning, automated backup with rotation, log analyzer with alerting, and deployment script with rollback.",
            "deliverables": [
                "5+ production-ready scripts",
                "Function library",
                "Documentation for each script",
                "Test suite with BATS",
            ],
            "xp_reward": 750,
            "estimated_hours": 8.0,
        },
    },
    {
        "track_slug": "foundation",
        "order_index": 4,
        "name": "Git & Collaborative Workflows",
        "slug": "git-collaborative-workflows",
        "description": "Master version control and collaboration workflows used by professional teams. Git is the foundation for all modern software development and DevOps.",
        "difficulty": "intermediate",
        "estimated_hours": 15.0,
        "prerequisites": ["environment-tooling-setup"],
        "tasks": [
            {"title": "Git object model (blobs, trees, commits)", "difficulty": "hard"},
            {"title": "References and HEAD", "difficulty": "medium"},
            {"title": "Index (staging area)", "difficulty": "medium"},
            {"title": "Packfiles and garbage collection", "difficulty": "hard"},
            {"title": "Feature branches", "difficulty": "easy"},
            {"title": "GitFlow workflow", "difficulty": "medium"},
            {"title": "Trunk-based development", "difficulty": "medium"},
            {"title": "Release branches", "difficulty": "medium"},
            {"title": "Hotfix management", "difficulty": "medium"},
            {"title": "Interactive rebase", "difficulty": "hard"},
            {"title": "Cherry-picking", "difficulty": "medium"},
            {"title": "Bisect for debugging", "difficulty": "hard"},
            {"title": "Reflog and recovery", "difficulty": "hard"},
            {"title": "Submodules and subtrees", "difficulty": "hard"},
            {"title": "Pull requests and code review", "difficulty": "medium"},
            {"title": "Branch protection rules", "difficulty": "medium"},
            {"title": "Merge strategies (merge, squash, rebase)", "difficulty": "medium"},
            {"title": "Conflict resolution", "difficulty": "medium"},
            {"title": "Git hooks", "difficulty": "hard"},
            {"title": "GitHub Issues and Projects", "difficulty": "easy"},
            {"title": "GitHub Actions basics", "difficulty": "medium"},
            {"title": "GitHub CLI", "difficulty": "easy"},
        ],
        "labs": [
            {"title": "Git Internals Exploration", "slug": "lab-4-1-git-internals", "hours": 2.0},
            {"title": "Branching Strategy Simulation", "slug": "lab-4-2-branching", "hours": 3.0},
            {"title": "Conflict Resolution Scenarios", "slug": "lab-4-3-conflicts", "hours": 2.0},
            {"title": "Rebase and History Rewriting", "slug": "lab-4-4-rebase", "hours": 3.0},
            {"title": "Pull Request Workflow", "slug": "lab-4-5-pull-requests", "hours": 3.0},
        ],
        "project": {
            "title": "Team Collaboration Simulation",
            "slug": "project-team-collaboration",
            "description": "Simulate a team project with multiple branches, pull requests with review, conflict resolution, release management, and protected main branch.",
            "deliverables": [
                "Git workflow documentation",
                "Contribution guidelines (CONTRIBUTING.md)",
                "Branch protection configuration",
                "Release process documentation",
            ],
            "xp_reward": 600,
            "estimated_hours": 6.0,
        },
    },
    {
        "track_slug": "foundation",
        "order_index": 5,
        "name": "Python for DevOps",
        "slug": "python-for-devops",
        "description": "Python is the dominant language for DevOps automation. Learn to build tools that interact with cloud APIs, automate infrastructure, and process data.",
        "difficulty": "intermediate",
        "estimated_hours": 25.0,
        "prerequisites": ["shell-scripting-automation"],
        "tasks": [
            {"title": "Data types and structures", "difficulty": "easy"},
            {"title": "Functions and decorators", "difficulty": "medium"},
            {"title": "Classes and OOP basics", "difficulty": "medium"},
            {"title": "Exception handling", "difficulty": "medium"},
            {"title": "Virtual environments", "difficulty": "easy"},
            {"title": "boto3 (AWS SDK)", "difficulty": "hard"},
            {"title": "requests (HTTP client)", "difficulty": "medium"},
            {"title": "paramiko (SSH)", "difficulty": "hard"},
            {"title": "jinja2 (templating)", "difficulty": "medium"},
            {"title": "pyyaml and json", "difficulty": "easy"},
            {"title": "Configuration management patterns", "difficulty": "medium"},
            {"title": "Secret handling", "difficulty": "hard"},
            {"title": "Logging and monitoring", "difficulty": "medium"},
            {"title": "Error handling strategies", "difficulty": "medium"},
            {"title": "Retry logic", "difficulty": "medium"},
            {"title": "argparse fundamentals", "difficulty": "medium"},
            {"title": "Click framework", "difficulty": "medium"},
            {"title": "Rich for beautiful output", "difficulty": "easy"},
            {"title": "REST API consumption", "difficulty": "medium"},
            {"title": "Authentication (API keys, OAuth)", "difficulty": "hard"},
            {"title": "Rate limiting handling", "difficulty": "hard"},
            {"title": "pytest fundamentals", "difficulty": "medium"},
            {"title": "Mocking external services", "difficulty": "hard"},
            {"title": "Type hints and mypy", "difficulty": "medium"},
            {"title": "Black and flake8", "difficulty": "easy"},
        ],
        "labs": [
            {"title": "Python Fundamentals Review", "slug": "lab-5-1-python-fundamentals", "hours": 3.0},
            {"title": "AWS Resource Manager with boto3", "slug": "lab-5-2-boto3", "hours": 4.0},
            {"title": "CLI Tool with Click", "slug": "lab-5-3-cli-click", "hours": 3.0},
            {"title": "REST API Client", "slug": "lab-5-4-rest-api", "hours": 3.0},
            {"title": "Configuration Manager", "slug": "lab-5-5-config-manager", "hours": 3.0},
            {"title": "Testing Your Tools", "slug": "lab-5-6-testing", "hours": 3.0},
        ],
        "project": {
            "title": "AWS Automation Suite",
            "slug": "project-aws-automation-suite",
            "description": "Build a complete automation suite: EC2 instance manager, S3 backup tool, IAM user provisioning, cost reporter, and resource tagger.",
            "deliverables": [
                "Python package with 5+ tools",
                "CLI interface",
                "Unit tests (80%+ coverage)",
                "Documentation",
                "PyPI-ready setup",
            ],
            "xp_reward": 1000,
            "estimated_hours": 10.0,
        },
    },

    # =========================================================================
    # TRACK 2: CLOUD & INFRASTRUCTURE (Modules 06-09)
    # =========================================================================
    {
        "track_slug": "cloud-infrastructure",
        "order_index": 6,
        "name": "AWS Core Services",
        "slug": "aws-core-services",
        "description": "Master AWS fundamental services that form the foundation for all cloud infrastructure. Build real production architecture.",
        "difficulty": "advanced",
        "estimated_hours": 25.0,
        "prerequisites": ["python-for-devops"],
        "tasks": [
            {"title": "Global infrastructure (regions, AZs)", "difficulty": "easy"},
            {"title": "Account setup and Organizations", "difficulty": "medium"},
            {"title": "Cost management and budgets", "difficulty": "medium"},
            {"title": "Well-Architected Framework intro", "difficulty": "medium"},
            {"title": "IAM users, groups, roles", "difficulty": "medium"},
            {"title": "IAM policies (managed, inline, custom)", "difficulty": "hard"},
            {"title": "Policy evaluation logic", "difficulty": "hard"},
            {"title": "Cross-account access", "difficulty": "hard"},
            {"title": "VPC CIDR planning", "difficulty": "medium"},
            {"title": "Subnets (public, private)", "difficulty": "medium"},
            {"title": "Internet Gateway", "difficulty": "medium"},
            {"title": "NAT Gateway/Instance", "difficulty": "medium"},
            {"title": "Route tables", "difficulty": "medium"},
            {"title": "Security Groups vs NACLs", "difficulty": "hard"},
            {"title": "VPC Peering", "difficulty": "hard"},
            {"title": "VPC Endpoints", "difficulty": "hard"},
            {"title": "EC2 instance types and selection", "difficulty": "medium"},
            {"title": "AMIs (Amazon Machine Images)", "difficulty": "medium"},
            {"title": "Key pairs and SSH", "difficulty": "easy"},
            {"title": "User data scripts", "difficulty": "medium"},
            {"title": "EBS volumes", "difficulty": "medium"},
            {"title": "ALB, NLB, CLB differences", "difficulty": "hard"},
            {"title": "Target groups and health checks", "difficulty": "medium"},
            {"title": "Auto Scaling groups", "difficulty": "hard"},
            {"title": "S3 bucket configuration", "difficulty": "medium"},
            {"title": "S3 storage classes", "difficulty": "medium"},
            {"title": "S3 lifecycle policies", "difficulty": "medium"},
            {"title": "S3 versioning and encryption", "difficulty": "medium"},
        ],
        "labs": [
            {"title": "Multi-AZ VPC from Scratch", "slug": "lab-6-1-vpc", "hours": 4.0},
            {"title": "IAM Policy Workshop", "slug": "lab-6-2-iam", "hours": 3.0},
            {"title": "EC2 Fleet Deployment", "slug": "lab-6-3-ec2", "hours": 3.0},
            {"title": "Load Balanced Application", "slug": "lab-6-4-load-balancing", "hours": 4.0},
            {"title": "Auto Scaling Configuration", "slug": "lab-6-5-auto-scaling", "hours": 3.0},
            {"title": "S3 Static Website", "slug": "lab-6-6-s3-website", "hours": 2.0},
        ],
        "project": {
            "title": "Three-Tier Web Architecture",
            "slug": "project-three-tier-architecture",
            "description": "Build a complete three-tier application: VPC with public/private subnets, ALB + Auto Scaling web tier, application tier, RDS database tier, and bastion host.",
            "deliverables": [
                "Architecture diagram",
                "VPC configuration documentation",
                "Security group rules matrix",
                "Cost estimation",
                "Disaster recovery plan",
            ],
            "xp_reward": 1000,
            "estimated_hours": 12.0,
        },
    },
    {
        "track_slug": "cloud-infrastructure",
        "order_index": 7,
        "name": "Infrastructure as Code (Terraform)",
        "slug": "infrastructure-as-code-terraform",
        "description": "Infrastructure as code with Terraform — the industry standard for cloud provisioning. Manage complex infrastructure reproducibly and safely.",
        "difficulty": "advanced",
        "estimated_hours": 25.0,
        "prerequisites": ["aws-core-services"],
        "tasks": [
            {"title": "Declarative vs imperative IaC", "difficulty": "easy"},
            {"title": "Provider architecture", "difficulty": "medium"},
            {"title": "Resources and data sources", "difficulty": "medium"},
            {"title": "Variables and outputs", "difficulty": "medium"},
            {"title": "terraform init, plan, apply, destroy", "difficulty": "easy"},
            {"title": "Expressions and functions", "difficulty": "medium"},
            {"title": "Conditionals and loops (count, for_each)", "difficulty": "hard"},
            {"title": "Dynamic blocks", "difficulty": "hard"},
            {"title": "Local values", "difficulty": "medium"},
            {"title": "Type constraints", "difficulty": "medium"},
            {"title": "Local vs remote state", "difficulty": "medium"},
            {"title": "S3 + DynamoDB backend", "difficulty": "hard"},
            {"title": "State locking", "difficulty": "hard"},
            {"title": "terraform state commands", "difficulty": "hard"},
            {"title": "Importing existing resources", "difficulty": "hard"},
            {"title": "Module structure", "difficulty": "medium"},
            {"title": "Module sources (local, registry, git)", "difficulty": "medium"},
            {"title": "Module versioning", "difficulty": "medium"},
            {"title": "Workspace concept", "difficulty": "medium"},
            {"title": "Environment separation strategies", "difficulty": "hard"},
            {"title": "terraform validate", "difficulty": "easy"},
            {"title": "tflint and tfsec", "difficulty": "medium"},
            {"title": "Terratest basics", "difficulty": "hard"},
            {"title": "GitHub Actions integration", "difficulty": "hard"},
        ],
        "labs": [
            {"title": "First Terraform Project", "slug": "lab-7-1-first-terraform", "hours": 3.0},
            {"title": "Variables and Outputs", "slug": "lab-7-2-variables", "hours": 2.0},
            {"title": "Remote State Setup", "slug": "lab-7-3-remote-state", "hours": 2.0},
            {"title": "Creating Modules", "slug": "lab-7-4-modules", "hours": 4.0},
            {"title": "Multi-Environment Setup", "slug": "lab-7-5-multi-env", "hours": 4.0},
            {"title": "CI/CD Pipeline for Terraform", "slug": "lab-7-6-cicd", "hours": 4.0},
        ],
        "project": {
            "title": "Complete AWS Infrastructure with Terraform",
            "slug": "project-terraform-aws",
            "description": "Build Module 06 architecture with Terraform: reusable VPC module, EC2 module with ASG, ALB module, RDS module, multi-environment (dev, staging, prod), remote state, and GitHub Actions deployment.",
            "deliverables": [
                "Terraform module library",
                "Environment configurations",
                "CI/CD pipeline",
                "Documentation (README per module)",
                "Cost tagging strategy",
            ],
            "xp_reward": 1000,
            "estimated_hours": 12.0,
        },
    },
    {
        "track_slug": "cloud-infrastructure",
        "order_index": 8,
        "name": "Serverless Architecture",
        "slug": "serverless-architecture",
        "description": "Build event-driven, serverless applications with AWS Lambda. Design cost-effective, scalable solutions without server management.",
        "difficulty": "advanced",
        "estimated_hours": 20.0,
        "prerequisites": ["infrastructure-as-code-terraform"],
        "tasks": [
            {"title": "Serverless vs traditional", "difficulty": "easy"},
            {"title": "AWS Lambda architecture", "difficulty": "medium"},
            {"title": "Execution model and cold starts", "difficulty": "medium"},
            {"title": "Lambda pricing model", "difficulty": "easy"},
            {"title": "Function handlers", "difficulty": "medium"},
            {"title": "Event and context objects", "difficulty": "medium"},
            {"title": "Environment variables", "difficulty": "easy"},
            {"title": "Lambda layers", "difficulty": "hard"},
            {"title": "Packaging and dependencies", "difficulty": "medium"},
            {"title": "Local development (SAM, LocalStack)", "difficulty": "hard"},
            {"title": "API Gateway integration", "difficulty": "medium"},
            {"title": "S3 triggers", "difficulty": "medium"},
            {"title": "SQS triggers", "difficulty": "medium"},
            {"title": "SNS triggers", "difficulty": "medium"},
            {"title": "EventBridge rules", "difficulty": "hard"},
            {"title": "DynamoDB Streams", "difficulty": "hard"},
            {"title": "Step Functions orchestration", "difficulty": "hard"},
            {"title": "Fan-out/fan-in patterns", "difficulty": "hard"},
            {"title": "Dead letter queues", "difficulty": "medium"},
            {"title": "Idempotency", "difficulty": "hard"},
            {"title": "IAM execution roles", "difficulty": "medium"},
            {"title": "Secrets Manager integration", "difficulty": "medium"},
            {"title": "CloudWatch Logs and X-Ray", "difficulty": "medium"},
        ],
        "labs": [
            {"title": "First Lambda Function", "slug": "lab-8-1-first-lambda", "hours": 2.0},
            {"title": "API Gateway + Lambda", "slug": "lab-8-2-api-gateway", "hours": 3.0},
            {"title": "S3 Event Processing", "slug": "lab-8-3-s3-events", "hours": 3.0},
            {"title": "Step Functions Workflow", "slug": "lab-8-4-step-functions", "hours": 4.0},
            {"title": "SQS Message Processing", "slug": "lab-8-5-sqs", "hours": 3.0},
            {"title": "Lambda with Terraform", "slug": "lab-8-6-lambda-terraform", "hours": 3.0},
        ],
        "project": {
            "title": "Serverless Data Pipeline",
            "slug": "project-serverless-pipeline",
            "description": "Build a complete data processing pipeline: S3 trigger for file upload, Lambda for transformation, Step Functions for orchestration, DynamoDB for state, SNS for notifications, all with Terraform.",
            "deliverables": [
                "Architecture diagram",
                "Lambda functions",
                "Step Functions definition",
                "Terraform code",
                "Monitoring dashboard",
                "Cost analysis",
            ],
            "xp_reward": 1000,
            "estimated_hours": 10.0,
        },
    },
    {
        "track_slug": "cloud-infrastructure",
        "order_index": 9,
        "name": "Networking & Security",
        "slug": "networking-security",
        "description": "Deep dive into network architecture and security practices critical for enterprise-grade infrastructure.",
        "difficulty": "advanced",
        "estimated_hours": 20.0,
        "prerequisites": ["aws-core-services"],
        "tasks": [
            {"title": "Transit Gateway", "difficulty": "hard"},
            {"title": "PrivateLink", "difficulty": "hard"},
            {"title": "Direct Connect basics", "difficulty": "hard"},
            {"title": "VPN connections", "difficulty": "hard"},
            {"title": "Route 53 DNS", "difficulty": "medium"},
            {"title": "CloudFront CDN", "difficulty": "medium"},
            {"title": "Security groups deep dive", "difficulty": "medium"},
            {"title": "Network ACLs", "difficulty": "medium"},
            {"title": "WAF (Web Application Firewall)", "difficulty": "hard"},
            {"title": "Shield (DDoS protection)", "difficulty": "hard"},
            {"title": "AWS SSO", "difficulty": "hard"},
            {"title": "Federation (SAML, OIDC)", "difficulty": "hard"},
            {"title": "Cognito basics", "difficulty": "medium"},
            {"title": "Service Control Policies", "difficulty": "hard"},
            {"title": "Permission boundaries", "difficulty": "hard"},
            {"title": "KMS (Key Management Service)", "difficulty": "hard"},
            {"title": "Encryption at rest and in transit", "difficulty": "medium"},
            {"title": "Certificate Manager (ACM)", "difficulty": "medium"},
            {"title": "Secrets Manager vs Parameter Store", "difficulty": "medium"},
            {"title": "AWS Config", "difficulty": "medium"},
            {"title": "CloudTrail", "difficulty": "medium"},
            {"title": "Security Hub", "difficulty": "hard"},
            {"title": "GuardDuty", "difficulty": "medium"},
            {"title": "Compliance frameworks (SOC2, HIPAA, PCI)", "difficulty": "hard"},
        ],
        "labs": [
            {"title": "Advanced VPC Design", "slug": "lab-9-1-advanced-vpc", "hours": 3.0},
            {"title": "WAF Configuration", "slug": "lab-9-2-waf", "hours": 3.0},
            {"title": "KMS and Encryption", "slug": "lab-9-3-kms", "hours": 3.0},
            {"title": "CloudTrail and Config", "slug": "lab-9-4-cloudtrail", "hours": 3.0},
            {"title": "Security Hub Setup", "slug": "lab-9-5-security-hub", "hours": 2.0},
            {"title": "Automated Security Response", "slug": "lab-9-6-auto-response", "hours": 3.0},
        ],
        "project": {
            "title": "Secure Reference Architecture",
            "slug": "project-secure-architecture",
            "description": "Implement a secure architecture: multi-account strategy, Transit Gateway connectivity, centralized logging, Security Hub aggregation, automated compliance checks, incident response automation.",
            "deliverables": [
                "Security architecture diagram",
                "Network topology diagram",
                "Security controls documentation",
                "Compliance checklist",
                "Incident response playbook",
            ],
            "xp_reward": 1000,
            "estimated_hours": 10.0,
        },
    },

    # =========================================================================
    # TRACK 3: CONTAINERS & ORCHESTRATION (Modules 10-12)
    # =========================================================================
    {
        "track_slug": "containers-orchestration",
        "order_index": 10,
        "name": "Docker Fundamentals",
        "slug": "docker-fundamentals",
        "description": "Master Docker — the container technology that revolutionized how we build and deploy applications.",
        "difficulty": "intermediate",
        "estimated_hours": 15.0,
        "prerequisites": ["linux-mastery"],
        "tasks": [
            {"title": "Containers vs VMs", "difficulty": "easy"},
            {"title": "Docker architecture", "difficulty": "medium"},
            {"title": "Images and layers", "difficulty": "medium"},
            {"title": "Container lifecycle", "difficulty": "medium"},
            {"title": "Docker CLI basics", "difficulty": "easy"},
            {"title": "Dockerfile instruction reference", "difficulty": "medium"},
            {"title": "Build context", "difficulty": "medium"},
            {"title": "Layer caching", "difficulty": "hard"},
            {"title": "Multi-stage builds", "difficulty": "hard"},
            {"title": "Build arguments", "difficulty": "medium"},
            {"title": "Tagging strategies", "difficulty": "medium"},
            {"title": "Registry basics (Docker Hub, ECR)", "difficulty": "medium"},
            {"title": "Image scanning", "difficulty": "medium"},
            {"title": "Base image selection", "difficulty": "medium"},
            {"title": "Size optimization", "difficulty": "hard"},
            {"title": "Resource limits", "difficulty": "medium"},
            {"title": "Environment variables", "difficulty": "easy"},
            {"title": "Volume management", "difficulty": "medium"},
            {"title": "Network basics", "difficulty": "medium"},
            {"title": "Docker Compose syntax", "difficulty": "medium"},
            {"title": "Compose service definition", "difficulty": "medium"},
            {"title": "Non-root containers", "difficulty": "hard"},
            {"title": "Read-only filesystems", "difficulty": "hard"},
            {"title": "Secrets handling", "difficulty": "hard"},
        ],
        "labs": [
            {"title": "Docker CLI Fundamentals", "slug": "lab-10-1-docker-cli", "hours": 2.0},
            {"title": "Dockerfile Best Practices", "slug": "lab-10-2-dockerfile", "hours": 3.0},
            {"title": "Multi-Stage Builds", "slug": "lab-10-3-multistage", "hours": 2.0},
            {"title": "Docker Compose Application", "slug": "lab-10-4-compose", "hours": 3.0},
            {"title": "Container Security Hardening", "slug": "lab-10-5-security", "hours": 2.0},
        ],
        "project": {
            "title": "Containerized Full-Stack App",
            "slug": "project-containerized-fullstack",
            "description": "Containerize a complete application: Frontend (React/Next.js), Backend API (Python/Node), Database (PostgreSQL), Redis cache, Nginx reverse proxy.",
            "deliverables": [
                "Optimized Dockerfiles",
                "docker-compose.yml (dev + prod)",
                "Documentation",
                "Size comparison report",
                "Security scan results",
            ],
            "xp_reward": 750,
            "estimated_hours": 8.0,
        },
    },
    {
        "track_slug": "containers-orchestration",
        "order_index": 11,
        "name": "Docker Advanced & Production",
        "slug": "docker-advanced-production",
        "description": "Take Docker to production with advanced patterns, monitoring, and enterprise-grade practices.",
        "difficulty": "advanced",
        "estimated_hours": 15.0,
        "prerequisites": ["docker-fundamentals"],
        "tasks": [
            {"title": "BuildKit features", "difficulty": "hard"},
            {"title": "Cache mounts", "difficulty": "hard"},
            {"title": "Secret mounts", "difficulty": "hard"},
            {"title": "Build attestations", "difficulty": "hard"},
            {"title": "SBOM generation", "difficulty": "hard"},
            {"title": "Reproducible builds", "difficulty": "hard"},
            {"title": "ECR setup and policies", "difficulty": "medium"},
            {"title": "Image lifecycle management", "difficulty": "medium"},
            {"title": "Cross-region replication", "difficulty": "hard"},
            {"title": "Image signing (cosign)", "difficulty": "hard"},
            {"title": "Health checks", "difficulty": "medium"},
            {"title": "Graceful shutdown", "difficulty": "hard"},
            {"title": "Signal handling", "difficulty": "hard"},
            {"title": "Init systems (tini, dumb-init)", "difficulty": "medium"},
            {"title": "Sidecar containers", "difficulty": "hard"},
            {"title": "Container metrics", "difficulty": "medium"},
            {"title": "Log aggregation", "difficulty": "medium"},
            {"title": "cAdvisor", "difficulty": "medium"},
            {"title": "Prometheus metrics", "difficulty": "hard"},
            {"title": "ECS task definitions", "difficulty": "hard"},
            {"title": "ECS services", "difficulty": "hard"},
            {"title": "Fargate vs EC2", "difficulty": "medium"},
        ],
        "labs": [
            {"title": "BuildKit Advanced Features", "slug": "lab-11-1-buildkit", "hours": 2.0},
            {"title": "ECR Lifecycle Management", "slug": "lab-11-2-ecr", "hours": 2.0},
            {"title": "Container Monitoring Setup", "slug": "lab-11-3-monitoring", "hours": 3.0},
            {"title": "CI/CD Pipeline for Containers", "slug": "lab-11-4-cicd", "hours": 4.0},
            {"title": "ECS Deployment", "slug": "lab-11-5-ecs", "hours": 4.0},
        ],
        "project": {
            "title": "Production Container Platform",
            "slug": "project-production-containers",
            "description": "Build a complete container platform: multi-stage builds with SBOM, ECR with scanning and signing, GitHub Actions pipeline, ECS deployment, Prometheus monitoring, log aggregation.",
            "deliverables": [
                "Production Dockerfiles",
                "CI/CD pipeline",
                "ECS infrastructure (Terraform)",
                "Monitoring dashboards",
                "Runbook documentation",
            ],
            "xp_reward": 1000,
            "estimated_hours": 10.0,
        },
    },
    {
        "track_slug": "containers-orchestration",
        "order_index": 12,
        "name": "Kubernetes Core",
        "slug": "kubernetes-core",
        "description": "Kubernetes — the container orchestration standard. Deploy, scale, and manage containerized applications in production.",
        "difficulty": "advanced",
        "estimated_hours": 25.0,
        "prerequisites": ["docker-advanced-production"],
        "tasks": [
            {"title": "Control plane components", "difficulty": "medium"},
            {"title": "Worker node components", "difficulty": "medium"},
            {"title": "etcd and cluster state", "difficulty": "hard"},
            {"title": "API server", "difficulty": "medium"},
            {"title": "kubectl basics", "difficulty": "easy"},
            {"title": "Pods", "difficulty": "medium"},
            {"title": "ReplicaSets", "difficulty": "medium"},
            {"title": "Deployments", "difficulty": "medium"},
            {"title": "StatefulSets", "difficulty": "hard"},
            {"title": "DaemonSets", "difficulty": "medium"},
            {"title": "Jobs and CronJobs", "difficulty": "medium"},
            {"title": "Service types (ClusterIP, NodePort, LoadBalancer)", "difficulty": "medium"},
            {"title": "Ingress controllers", "difficulty": "hard"},
            {"title": "DNS (CoreDNS)", "difficulty": "medium"},
            {"title": "Network policies basics", "difficulty": "hard"},
            {"title": "Volumes", "difficulty": "medium"},
            {"title": "PersistentVolumes", "difficulty": "hard"},
            {"title": "PersistentVolumeClaims", "difficulty": "hard"},
            {"title": "Storage classes", "difficulty": "hard"},
            {"title": "ConfigMaps", "difficulty": "medium"},
            {"title": "Secrets", "difficulty": "medium"},
            {"title": "Resource limits", "difficulty": "medium"},
            {"title": "QoS classes", "difficulty": "hard"},
            {"title": "Rolling updates and rollbacks", "difficulty": "medium"},
            {"title": "Health checks (liveness, readiness, startup)", "difficulty": "medium"},
            {"title": "Horizontal Pod Autoscaler", "difficulty": "hard"},
        ],
        "labs": [
            {"title": "Cluster Setup (Minikube/kind)", "slug": "lab-12-1-cluster-setup", "hours": 2.0},
            {"title": "Deploying Applications", "slug": "lab-12-2-deployments", "hours": 3.0},
            {"title": "Services and Ingress", "slug": "lab-12-3-services", "hours": 3.0},
            {"title": "Storage Configuration", "slug": "lab-12-4-storage", "hours": 3.0},
            {"title": "ConfigMaps and Secrets", "slug": "lab-12-5-config", "hours": 2.0},
            {"title": "Scaling and Updates", "slug": "lab-12-6-scaling", "hours": 3.0},
        ],
        "project": {
            "title": "Microservices on Kubernetes",
            "slug": "project-k8s-microservices",
            "description": "Deploy a microservices application: Frontend service, API services (2-3), Database (StatefulSet), Redis cache, Ingress with TLS, ConfigMaps and Secrets, HPA configuration.",
            "deliverables": [
                "Kubernetes manifests",
                "Deployment documentation",
                "Architecture diagram",
                "Troubleshooting guide",
                "Scaling strategy",
            ],
            "xp_reward": 1000,
            "estimated_hours": 12.0,
        },
    },

    # =========================================================================
    # TRACK 4: PLATFORM ENGINEERING (Modules 13-15)
    # =========================================================================
    {
        "track_slug": "platform-engineering",
        "order_index": 13,
        "name": "Kubernetes Advanced & GitOps",
        "slug": "kubernetes-advanced-gitops",
        "description": "Advanced Kubernetes patterns and GitOps for enterprise-grade platform engineering.",
        "difficulty": "expert",
        "estimated_hours": 25.0,
        "prerequisites": ["kubernetes-core"],
        "tasks": [
            {"title": "EKS architecture", "difficulty": "hard"},
            {"title": "Managed node groups", "difficulty": "medium"},
            {"title": "Fargate profiles", "difficulty": "hard"},
            {"title": "EKS add-ons", "difficulty": "medium"},
            {"title": "IAM integration (IRSA)", "difficulty": "hard"},
            {"title": "EKS Terraform modules", "difficulty": "hard"},
            {"title": "Helm chart structure", "difficulty": "medium"},
            {"title": "Helm templates and values", "difficulty": "hard"},
            {"title": "Helm hooks", "difficulty": "hard"},
            {"title": "Chart dependencies", "difficulty": "hard"},
            {"title": "Creating custom charts", "difficulty": "hard"},
            {"title": "Kustomize base and overlays", "difficulty": "medium"},
            {"title": "Kustomize patches", "difficulty": "hard"},
            {"title": "ConfigMap/Secret generators", "difficulty": "medium"},
            {"title": "ArgoCD architecture", "difficulty": "hard"},
            {"title": "Application CRD", "difficulty": "hard"},
            {"title": "Sync policies", "difficulty": "medium"},
            {"title": "ArgoCD rollbacks", "difficulty": "medium"},
            {"title": "ApplicationSets", "difficulty": "hard"},
            {"title": "Multi-cluster management", "difficulty": "hard"},
            {"title": "Pod Security Standards", "difficulty": "hard"},
            {"title": "OPA/Gatekeeper", "difficulty": "hard"},
            {"title": "Admission controllers", "difficulty": "hard"},
            {"title": "Network policies advanced", "difficulty": "hard"},
            {"title": "Service mesh intro (Istio/Linkerd)", "difficulty": "hard"},
        ],
        "labs": [
            {"title": "EKS Cluster with Terraform", "slug": "lab-13-1-eks-terraform", "hours": 4.0},
            {"title": "Helm Chart Development", "slug": "lab-13-2-helm", "hours": 3.0},
            {"title": "Kustomize Overlays", "slug": "lab-13-3-kustomize", "hours": 2.0},
            {"title": "ArgoCD Setup and GitOps", "slug": "lab-13-4-argocd", "hours": 4.0},
            {"title": "Advanced Security Policies", "slug": "lab-13-5-security", "hours": 3.0},
            {"title": "Multi-Environment GitOps", "slug": "lab-13-6-multi-env", "hours": 4.0},
        ],
        "project": {
            "title": "GitOps Platform",
            "slug": "project-gitops-platform",
            "description": "Build a complete GitOps platform: EKS cluster (Terraform), ArgoCD installation, app-of-apps pattern, Helm charts for services, environment promotion (dev→staging→prod), security policies, automated sync.",
            "deliverables": [
                "EKS Terraform modules",
                "Helm chart library",
                "ArgoCD applications",
                "GitOps repository structure",
                "Promotion workflow documentation",
            ],
            "xp_reward": 1250,
            "estimated_hours": 15.0,
        },
    },
    {
        "track_slug": "platform-engineering",
        "order_index": 14,
        "name": "Observability & Monitoring",
        "slug": "observability-monitoring",
        "description": "Implement full observability stack — metrics, logs, and traces — to drive reliable infrastructure.",
        "difficulty": "expert",
        "estimated_hours": 20.0,
        "prerequisites": ["kubernetes-advanced-gitops"],
        "tasks": [
            {"title": "Three pillars (metrics, logs, traces)", "difficulty": "easy"},
            {"title": "SLIs, SLOs, SLAs", "difficulty": "medium"},
            {"title": "Error budgets", "difficulty": "hard"},
            {"title": "Observability vs monitoring", "difficulty": "easy"},
            {"title": "Prometheus architecture", "difficulty": "hard"},
            {"title": "Data model (metrics, labels)", "difficulty": "medium"},
            {"title": "PromQL", "difficulty": "hard"},
            {"title": "Scrape configuration", "difficulty": "medium"},
            {"title": "Service discovery", "difficulty": "hard"},
            {"title": "Recording rules", "difficulty": "hard"},
            {"title": "Alerting rules", "difficulty": "hard"},
            {"title": "Grafana dashboard design", "difficulty": "medium"},
            {"title": "Variables and templating", "difficulty": "medium"},
            {"title": "Grafana alerting", "difficulty": "medium"},
            {"title": "Dashboard provisioning", "difficulty": "hard"},
            {"title": "Loki architecture", "difficulty": "hard"},
            {"title": "Log aggregation patterns", "difficulty": "hard"},
            {"title": "LogQL", "difficulty": "hard"},
            {"title": "Structured logging", "difficulty": "medium"},
            {"title": "Distributed tracing concepts", "difficulty": "hard"},
            {"title": "OpenTelemetry", "difficulty": "hard"},
            {"title": "Tempo/Jaeger", "difficulty": "hard"},
            {"title": "Alert design principles", "difficulty": "hard"},
            {"title": "Severity levels", "difficulty": "medium"},
            {"title": "PagerDuty/OpsGenie integration", "difficulty": "medium"},
        ],
        "labs": [
            {"title": "Prometheus Installation", "slug": "lab-14-1-prometheus", "hours": 3.0},
            {"title": "Grafana Dashboards", "slug": "lab-14-2-grafana", "hours": 3.0},
            {"title": "Loki Log Aggregation", "slug": "lab-14-3-loki", "hours": 3.0},
            {"title": "Application Metrics", "slug": "lab-14-4-app-metrics", "hours": 3.0},
            {"title": "Alerting Configuration", "slug": "lab-14-5-alerting", "hours": 2.0},
            {"title": "Full Stack Observability", "slug": "lab-14-6-full-stack", "hours": 4.0},
        ],
        "project": {
            "title": "Production Observability Stack",
            "slug": "project-observability-stack",
            "description": "Implement complete observability: Prometheus + Alertmanager, Grafana dashboards, Loki for logs, application instrumentation, custom metrics, SLO tracking, incident response integration.",
            "deliverables": [
                "Observability architecture diagram",
                "Prometheus configuration",
                "Grafana dashboards (5+)",
                "Alert definitions",
                "Runbooks",
                "SLO documentation",
            ],
            "xp_reward": 1000,
            "estimated_hours": 12.0,
        },
    },
    {
        "track_slug": "platform-engineering",
        "order_index": 15,
        "name": "SRE, DevSecOps & Capstone",
        "slug": "sre-devsecops-capstone",
        "description": "Final module combining SRE practices, DevSecOps, and a capstone project demonstrating all knowledge.",
        "difficulty": "expert",
        "estimated_hours": 30.0,
        "prerequisites": ["observability-monitoring"],
        "tasks": [
            {"title": "SRE vs DevOps", "difficulty": "easy"},
            {"title": "Service Level Objectives", "difficulty": "hard"},
            {"title": "Error budgets deep dive", "difficulty": "hard"},
            {"title": "Toil reduction", "difficulty": "medium"},
            {"title": "Capacity planning", "difficulty": "hard"},
            {"title": "Reliability engineering", "difficulty": "hard"},
            {"title": "Incident response process", "difficulty": "hard"},
            {"title": "On-call practices", "difficulty": "medium"},
            {"title": "Communication during incidents", "difficulty": "medium"},
            {"title": "Postmortems (blameless)", "difficulty": "medium"},
            {"title": "Root cause analysis", "difficulty": "hard"},
            {"title": "Security shift-left", "difficulty": "medium"},
            {"title": "SAST (Static Analysis)", "difficulty": "hard"},
            {"title": "DAST (Dynamic Analysis)", "difficulty": "hard"},
            {"title": "SCA (Software Composition Analysis)", "difficulty": "hard"},
            {"title": "Container scanning", "difficulty": "medium"},
            {"title": "Infrastructure scanning", "difficulty": "hard"},
            {"title": "Secret scanning", "difficulty": "medium"},
            {"title": "Dependency checks", "difficulty": "medium"},
            {"title": "Compliance as code", "difficulty": "hard"},
            {"title": "Policy enforcement", "difficulty": "hard"},
            {"title": "ChatOps", "difficulty": "medium"},
            {"title": "Self-healing infrastructure", "difficulty": "hard"},
            {"title": "Chaos engineering intro", "difficulty": "hard"},
        ],
        "labs": [
            {"title": "SLO Implementation", "slug": "lab-15-1-slo", "hours": 3.0},
            {"title": "Incident Simulation", "slug": "lab-15-2-incident", "hours": 3.0},
            {"title": "Security Scanning Pipeline", "slug": "lab-15-3-security-scan", "hours": 4.0},
            {"title": "Compliance Automation", "slug": "lab-15-4-compliance", "hours": 3.0},
            {"title": "Chaos Engineering Basics", "slug": "lab-15-5-chaos", "hours": 3.0},
        ],
        "project": {
            "title": "Complete DevOps Platform (Capstone)",
            "slug": "project-capstone-platform",
            "description": "Build a complete, production-ready platform demonstrating all 15 modules' knowledge: EKS infrastructure, microservices application, CI/CD with security scanning, GitOps deployment, full observability stack, security policies, documentation, and runbooks.",
            "deliverables": [
                "Complete GitHub repository",
                "Working deployed application",
                "Infrastructure as Code",
                "CI/CD pipelines",
                "Observability stack",
                "Security documentation",
                "Architecture documentation",
                "Video walkthrough (optional)",
            ],
            "xp_reward": 2000,
            "estimated_hours": 25.0,
        },
    },
]


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_tracks() -> list[dict]:
    """Returns all 4 tracks."""
    return BOOTCAMP_TRACKS


def get_modules() -> list[dict]:
    """Returns all 15 modules."""
    return BOOTCAMP_MODULES


def get_track_count() -> int:
    """Returns the total number of tracks."""
    return len(BOOTCAMP_TRACKS)


def get_module_count() -> int:
    """Returns the total number of modules."""
    return len(BOOTCAMP_MODULES)


def get_task_count() -> int:
    """Returns the total number of tasks across all modules."""
    return sum(len(module["tasks"]) for module in BOOTCAMP_MODULES)


def get_lab_count() -> int:
    """Returns the total number of labs across all modules."""
    return sum(len(module["labs"]) for module in BOOTCAMP_MODULES)


def get_project_count() -> int:
    """Returns the total number of projects."""
    return len([m for m in BOOTCAMP_MODULES if m.get("project")])


def get_total_hours() -> float:
    """Returns the total estimated hours for the bootcamp."""
    return sum(module["estimated_hours"] for module in BOOTCAMP_MODULES)


def get_modules_by_track(track_slug: str) -> list[dict]:
    """Returns all modules for a specific track."""
    return [m for m in BOOTCAMP_MODULES if m["track_slug"] == track_slug]


def get_bootcamp_summary() -> dict:
    """Returns a summary of the bootcamp content."""
    return {
        "tracks": get_track_count(),
        "modules": get_module_count(),
        "tasks": get_task_count(),
        "labs": get_lab_count(),
        "projects": get_project_count(),
        "total_hours": get_total_hours(),
    }
