"""
Git & GitHub Mastery - Study Data
=================================

90 Flashcards (30 easy, 30 medium, 30 hard)
60 Quiz Questions (20 easy, 20 medium, 20 hard)
"""

GIT_STUDY_DATA = {
    "module_slug": "git-github-mastery",
    "module_title": "Git & GitHub",
    "module_description": "Versionshantering och samarbete med Git",
    "icon": "GitBranch",

    "flashcards": {
        "easy": [
            {"front": "Vad är Git?", "back": "Distribuerat versionshanteringssystem. Spårar ändringar i kod och möjliggör samarbete."},
            {"front": "Vad är ett repository?", "back": "Ett projekt med all kod och versionshistorik. Kan vara lokalt eller remote (GitHub)."},
            {"front": "Hur skapar du ett nytt repo?", "back": "git init - skapar .git-katalog och initierar tomt repository."},
            {"front": "Vad gör git clone?", "back": "Kopierar ett remote repository till din lokala maskin med all historik."},
            {"front": "Vad är staging area?", "back": "Mellansteg där du väljer vilka ändringar som ska ingå i nästa commit."},
            {"front": "Hur lägger du till filer för commit?", "back": "git add fil.txt - lägger till i staging. git add . lägger till allt."},
            {"front": "Vad gör git commit?", "back": "Sparar staged ändringar med ett meddelande. git commit -m 'beskrivning'"},
            {"front": "Hur ser du historik?", "back": "git log - visar commits. git log --oneline för kompakt vy."},
            {"front": "Vad gör git status?", "back": "Visar aktuell status: modified, staged, untracked filer."},
            {"front": "Vad är en branch?", "back": "En oberoende utvecklingslinje. Låter dig jobba isolerat utan att påverka main."},
            {"front": "Hur skapar du ny branch?", "back": "git branch branchname - skapar. git checkout -b branchname skapar och byter."},
            {"front": "Hur byter du branch?", "back": "git checkout branchname eller git switch branchname"},
            {"front": "Vad gör git merge?", "back": "Slår ihop ändringar från en branch till en annan."},
            {"front": "Vad är ett remote?", "back": "En version av repot på annan plats (GitHub). origin är standard-namnet."},
            {"front": "Vad gör git push?", "back": "Skickar lokala commits till remote repository."},
            {"front": "Vad gör git pull?", "back": "Hämtar och mergar ändringar från remote. Kombination av fetch + merge."},
            {"front": "Vad gör git fetch?", "back": "Hämtar ändringar från remote utan att merga. Säkrare att granska först."},
            {"front": "Vad är .gitignore?", "back": "Fil som anger vilka filer Git ska ignorera. node_modules/, *.log, etc."},
            {"front": "Hur ångrar du ändringar i working directory?", "back": "git checkout -- fil.txt eller git restore fil.txt"},
            {"front": "Vad är HEAD?", "back": "Pekare till aktuell commit/branch. HEAD~1 är förra commit."},
            {"front": "Hur ser du skillnader?", "back": "git diff - visar ändringar mot staging. git diff --staged för staged."},
            {"front": "Vad är GitHub?", "back": "Plattform för att hosta Git-repos, samarbeta, code review, issues, CI/CD."},
            {"front": "Vad är en Pull Request?", "back": "Begäran om att merga din branch till annan branch. Möjliggör code review."},
            {"front": "Hur listar du branches?", "back": "git branch - lokala. git branch -r remote. git branch -a alla."},
            {"front": "Vad gör git remote -v?", "back": "Visar konfigurerade remotes med URL:er för fetch och push."},
            {"front": "Hur tar du bort en branch?", "back": "git branch -d branchname (safe) eller -D (force delete)."},
            {"front": "Vad är en merge conflict?", "back": "När Git inte automatiskt kan slå ihop ändringar. Kräver manuell lösning."},
            {"front": "Hur ser du vem som ändrat en rad?", "back": "git blame fil.txt - visar commit och författare per rad."},
            {"front": "Vad gör git stash?", "back": "Sparar undan pågående ändringar temporärt. git stash pop återställer."},
            {"front": "Hur klonar du med SSH?", "back": "git clone git@github.com:user/repo.git - kräver SSH-nyckel konfigurerad."},
        ],
        "medium": [
            {"front": "Vad är git rebase?", "back": "Flyttar commits till ny bas. Ger linjär historik. Använd aldrig på publika branches."},
            {"front": "Skillnad mellan merge och rebase?", "back": "Merge bevarar historik med merge commit. Rebase skriver om historik linjärt."},
            {"front": "Vad är interactive rebase?", "back": "git rebase -i HEAD~3 - redigera, squash, reorder commits interaktivt."},
            {"front": "Hur squashar du commits?", "back": "git rebase -i HEAD~n, byt pick till squash för commits att slå ihop."},
            {"front": "Vad gör git cherry-pick?", "back": "Kopierar specifik commit till nuvarande branch. git cherry-pick commit-hash"},
            {"front": "Hur ångrar du senaste commit?", "back": "git reset --soft HEAD~1 behåller ändringar staged. --hard tar bort allt."},
            {"front": "Skillnad mellan reset och revert?", "back": "Reset ändrar historik (farligt för pushad kod). Revert skapar ny commit som ångrar."},
            {"front": "Vad är git reflog?", "back": "Loggar alla HEAD-rörelser. Räddar 'förlorade' commits efter reset."},
            {"front": "Hur fixar du senaste commit-meddelande?", "back": "git commit --amend -m 'nytt meddelande' - ändrar senaste commit."},
            {"front": "Vad är tagging?", "back": "Markerar specifika commits. git tag v1.0.0 för releases."},
            {"front": "Skillnad mellan lightweight och annotated tag?", "back": "Annotated har metadata (author, date, message). git tag -a v1.0 -m 'msg'"},
            {"front": "Hur pushar du tags?", "back": "git push --tags eller git push origin v1.0.0"},
            {"front": "Vad är git bisect?", "back": "Binärsökning för att hitta commit som introducerade bug."},
            {"front": "Hur fungerar git bisect?", "back": "git bisect start, bisect bad, bisect good commit. Git väljer mitt-commit."},
            {"front": "Vad är fast-forward merge?", "back": "När target branch inte har nya commits. Git flyttar bara pekaren framåt."},
            {"front": "Hur tvingar du non-fast-forward?", "back": "git merge --no-ff skapar alltid merge commit för tydlig historik."},
            {"front": "Vad är upstream tracking?", "back": "Koppling mellan lokal och remote branch. git push -u origin branch sätter."},
            {"front": "Vad gör git clean?", "back": "Tar bort untracked filer. git clean -fd för force inkl. dirs."},
            {"front": "Hur hittar du en commit med grep?", "back": "git log --grep='sökord' söker i commit-meddelanden."},
            {"front": "Vad är git submodule?", "back": "Inkluderar annat repo som subdirectory. Egen historik."},
            {"front": "Hur uppdaterar du submodules?", "back": "git submodule update --init --recursive"},
            {"front": "Vad är GitHub Actions?", "back": "CI/CD plattform integrerad i GitHub. Workflows definieras i YAML."},
            {"front": "Var ligger Actions workflows?", "back": ".github/workflows/ - YAML-filer som triggas på events."},
            {"front": "Vad är GitHub Issues?", "back": "Bug tracking och feature requests. Kan länkas till PRs och commits."},
            {"front": "Hur stänger du issue via commit?", "back": "Fixes #123 eller Closes #123 i commit-meddelande."},
            {"front": "Vad är protected branches?", "back": "Regler som kräver PR, reviews, status checks innan merge."},
            {"front": "Vad är GitHub Pages?", "back": "Gratis hosting för statiska webbplatser direkt från repo."},
            {"front": "Hur konfigurerar du Git globalt?", "back": "git config --global user.name 'namn' och user.email 'email'"},
            {"front": "Vad är pre-commit hooks?", "back": "Scripts som körs automatiskt före commit. Lint, tester, formatering."},
            {"front": "Var ligger hooks?", "back": ".git/hooks/ eller .husky/ med husky för delade hooks."},
        ],
        "hard": [
            {"front": "Hur fungerar Git internals (objects)?", "back": "Blob (fil), Tree (katalog), Commit (snapshot + metadata), Tag. SHA-1 hashar."},
            {"front": "Vad är packfiles?", "back": "Git komprimerar loose objects till packfiles. Delta compression."},
            {"front": "Hur fungerar Git garbage collection?", "back": "git gc packar objects, tar bort unreachable. Körs automatiskt."},
            {"front": "Vad är rerere?", "back": "Reuse Recorded Resolution - Git minns hur du löste konflikter förut."},
            {"front": "Hur aktiverar du rerere?", "back": "git config --global rerere.enabled true"},
            {"front": "Vad är git worktree?", "back": "Flera working directories för samma repo. Jobba på branches parallellt."},
            {"front": "Hur skapar du worktree?", "back": "git worktree add ../path branch - separat checkout."},
            {"front": "Vad är sparse checkout?", "back": "Checka bara ut delar av repo. Användbart för monorepos."},
            {"front": "Hur konfigurerar du sparse checkout?", "back": "git sparse-checkout init --cone, git sparse-checkout set dir/"},
            {"front": "Vad är git filter-branch?", "back": "Skriver om historik. Ta bort filer, ändra author. Ersatt av filter-repo."},
            {"front": "Hur tar du bort känslig fil från historik?", "back": "git filter-repo --invert-paths --path secrets.txt"},
            {"front": "Vad är shallow clone?", "back": "git clone --depth 1 - klonar bara senaste commit. Snabbare, mindre."},
            {"front": "Hur hämtar du mer historik?", "back": "git fetch --unshallow eller --deepen=n"},
            {"front": "Vad är Git LFS?", "back": "Large File Storage - lagrar stora filer separat, pekar via text."},
            {"front": "Hur installerar du LFS?", "back": "git lfs install, git lfs track '*.psd', commit .gitattributes"},
            {"front": "Vad är signed commits?", "back": "Commits signerade med GPG/SSH-nyckel. git commit -S"},
            {"front": "Hur verifierar du signatur?", "back": "git log --show-signature eller git verify-commit hash"},
            {"front": "Vad är replace refs?", "back": "git replace skapar alternativa commits. Användbart för grafting historik."},
            {"front": "Vad är git bundle?", "back": "Packar repo till en fil för offline-transfer. git bundle create repo.bundle --all"},
            {"front": "Hur applicerar du bundle?", "back": "git clone repo.bundle eller git fetch repo.bundle main"},
            {"front": "Vad är git notes?", "back": "Extra metadata kopplat till commits utan att ändra dem. git notes add"},
            {"front": "Hur fungerar merge strategies?", "back": "recursive (default), ours (behåll vårt), subtree (prefix paths)."},
            {"front": "Vad är octopus merge?", "back": "Mergar flera branches samtidigt. Default för >2 branches utan konflikt."},
            {"front": "Vad är credential.helper?", "back": "Lagrar credentials. cache (minne), store (disk), manager (OS keychain)."},
            {"front": "Hur konfigurerar du multiple remotes?", "back": "git remote add upstream url - t.ex. för fork workflow."},
            {"front": "Vad är fork workflow?", "back": "Fork på GitHub, klon lokalt, upstream remote. PR från fork."},
            {"front": "Hur synkar du fork?", "back": "git fetch upstream, git merge upstream/main, push till origin."},
            {"front": "Vad är git blame -w?", "back": "-w ignorerar whitespace-ändringar. -M detectar flyttade rader."},
            {"front": "Hur hittar du vem som tog bort en rad?", "back": "git log -S 'text' --oneline - söker efter text som lagts till/tagits bort."},
            {"front": "Vad är git maintenance?", "back": "Automatiska optimeringar. git maintenance start sätter upp cron/task."},
        ],
    },

    "quiz": {
        "easy": [
            {"question": "Vad gör 'git init'?", "options": ["Klonar repo", "Skapar nytt repository", "Initerar remote", "Skapar branch"], "correct": 1, "explanation": "git init skapar ett nytt Git-repository i nuvarande katalog."},
            {"question": "Hur lägger du till alla filer för commit?", "options": ["git add all", "git add .", "git commit all", "git stage ."], "correct": 1, "explanation": "git add . lägger till alla ändringar i staging area."},
            {"question": "Vad sparar en commit?", "options": ["Enstaka fil", "Snapshot av staged ändringar", "Hela repot", "Remote ändringar"], "correct": 1, "explanation": "Commit sparar snapshot av allt som är staged med meddelande."},
            {"question": "Hur klonar du ett repo?", "options": ["git copy url", "git clone url", "git download url", "git fetch url"], "correct": 1, "explanation": "git clone kopierar remote repo med all historik lokalt."},
            {"question": "Vad är en branch?", "options": ["Backup", "Oberoende utvecklingslinje", "Remote server", "Tag"], "correct": 1, "explanation": "Branch är en separat linje för utveckling utan att påverka andra."},
            {"question": "Hur skapar och byter du till ny branch?", "options": ["git branch new", "git checkout -b new", "git switch new", "git create new"], "correct": 1, "explanation": "git checkout -b skapar och byter i ett steg. git switch -c fungerar också."},
            {"question": "Vad gör 'git push'?", "options": ["Hämtar ändringar", "Skickar commits till remote", "Skapar branch", "Mergar branches"], "correct": 1, "explanation": "git push skickar lokala commits till remote repository."},
            {"question": "Vad gör 'git pull'?", "options": ["Bara hämtar", "Hämtar och mergar", "Pushar ändringar", "Skapar PR"], "correct": 1, "explanation": "git pull = git fetch + git merge. Hämtar och slår ihop."},
            {"question": "Vad är .gitignore?", "options": ["Git-konfiguration", "Lista filer Git ska ignorera", "Commit-historik", "Branch-lista"], "correct": 1, "explanation": ".gitignore anger filer och kataloger som Git ska strunta i."},
            {"question": "Hur ser du status på repot?", "options": ["git info", "git status", "git check", "git show"], "correct": 1, "explanation": "git status visar modified, staged och untracked filer."},
            {"question": "Vad är GitHub?", "options": ["Git CLI", "Plattform för hosting och samarbete", "Lokal Git GUI", "Backup-tjänst"], "correct": 1, "explanation": "GitHub är plattform för att hosta repos, PRs, issues, CI/CD."},
            {"question": "Vad är en Pull Request?", "options": ["Git-kommando", "Begäran att hämta", "Begäran att merga kod", "Remote fetch"], "correct": 2, "explanation": "PR är begäran att merga din branch, möjliggör code review."},
            {"question": "Hur ser du commit-historik?", "options": ["git history", "git log", "git commits", "git show all"], "correct": 1, "explanation": "git log visar commits. --oneline för kompakt vy."},
            {"question": "Vad är HEAD?", "options": ["Första commit", "Pekare till aktuell position", "Remote branch", "Main branch"], "correct": 1, "explanation": "HEAD pekar på aktuell commit/branch du arbetar på."},
            {"question": "Hur slår du ihop branches?", "options": ["git combine", "git merge", "git join", "git unite"], "correct": 1, "explanation": "git merge branchname slår ihop branch till nuvarande."},
            {"question": "Vad händer vid merge conflict?", "options": ["Automatisk lösning", "Git väljer senaste", "Kräver manuell lösning", "Merge avbryts permanent"], "correct": 2, "explanation": "Vid konflikt måste du manuellt välja vilken kod som ska behållas."},
            {"question": "Hur listar du branches?", "options": ["git list branches", "git branch", "git show branches", "git branches"], "correct": 1, "explanation": "git branch listar lokala branches. -a visar alla inkl. remote."},
            {"question": "Hur tar du bort en branch?", "options": ["git remove branch", "git branch -d name", "git delete branch", "git drop branch"], "correct": 1, "explanation": "git branch -d tar bort branch (safe). -D force delete."},
            {"question": "Vad gör git diff?", "options": ["Visar branches", "Visar skillnader", "Visar historik", "Visar status"], "correct": 1, "explanation": "git diff visar ändringar mellan working dir och staging."},
            {"question": "Hur ångrar du unstaged ändringar?", "options": ["git undo", "git restore fil", "git revert fil", "git reset fil"], "correct": 1, "explanation": "git restore fil återställer till senaste commit."},
        ],
        "medium": [
            {"question": "Vad är skillnaden mellan merge och rebase?", "options": ["Ingen skillnad", "Merge bevarar historik, rebase skriver om", "Rebase är säkrare", "Merge är snabbare"], "correct": 1, "explanation": "Merge bevarar förgreningar med merge commit. Rebase ger linjär historik."},
            {"question": "Hur squashar du 3 commits?", "options": ["git squash 3", "git rebase -i HEAD~3", "git merge --squash", "git commit --squash 3"], "correct": 1, "explanation": "Interactive rebase låter dig squash (slå ihop) commits."},
            {"question": "Vad gör git cherry-pick?", "options": ["Väljer branch", "Kopierar specifik commit", "Väljer filer", "Väljer remote"], "correct": 1, "explanation": "cherry-pick kopierar en specifik commit till din nuvarande branch."},
            {"question": "Hur ångrar du pushad commit säkert?", "options": ["git reset", "git revert", "git undo", "git delete"], "correct": 1, "explanation": "git revert skapar ny commit som ångrar. Säkert för delad historik."},
            {"question": "Vad gör git reflog?", "options": ["Remote log", "Visar alla HEAD-rörelser", "Filterar loggar", "Referens-lista"], "correct": 1, "explanation": "reflog loggar alla HEAD-ändringar. Räddar 'förlorade' commits."},
            {"question": "Hur skapar du annotated tag?", "options": ["git tag v1.0", "git tag -a v1.0 -m 'msg'", "git tag --annotate v1.0", "git tag -m v1.0"], "correct": 1, "explanation": "Annotated tags har metadata. -a för annotated, -m för meddelande."},
            {"question": "Vad är git stash?", "options": ["Permanent lagring", "Temporär lagring av ändringar", "Remote cache", "Commit-cache"], "correct": 1, "explanation": "Stash sparar undan pågående ändringar så du kan byta branch."},
            {"question": "Hur applicerar du stash?", "options": ["git stash apply", "git stash pop", "Båda fungerar", "git unstash"], "correct": 2, "explanation": "apply behåller i stash, pop tar bort. Båda applicerar."},
            {"question": "Vad gör git bisect?", "options": ["Delar branch", "Binärsökning för buggy commit", "Halverar repo", "Delar commits"], "correct": 1, "explanation": "bisect gör binärsökning för att hitta commit som introducerade bug."},
            {"question": "Vad är fast-forward merge?", "options": ["Snabb merge", "Git flyttar pekaren utan merge commit", "Parallell merge", "Force merge"], "correct": 1, "explanation": "Fast-forward sker när target inte har nya commits - bara pekarflytt."},
            {"question": "Vad gör --no-ff?", "options": ["Inaktiverar fetch", "Tvingar merge commit", "No force flag", "Inaktiverar filter"], "correct": 1, "explanation": "--no-ff skapar alltid merge commit för tydlig historik."},
            {"question": "Hur sätter du upstream tracking?", "options": ["git track upstream", "git push -u origin branch", "git upstream set", "git branch --track"], "correct": 1, "explanation": "-u (--set-upstream) kopplar lokal branch till remote."},
            {"question": "Vad är git submodule?", "options": ["Git-modul", "Repo inuti repo", "Subversion-modul", "Modulär Git"], "correct": 1, "explanation": "Submodule inkluderar annat repo som subdirectory med egen historik."},
            {"question": "Var ligger GitHub Actions workflows?", "options": [".github/actions/", ".github/workflows/", ".actions/", "workflows/"], "correct": 1, "explanation": "Workflows definieras i YAML-filer under .github/workflows/"},
            {"question": "Hur stänger du issue via commit?", "options": ["Close #123", "Fixes #123 i meddelandet", "git close #123", "Done #123"], "correct": 1, "explanation": "Fixes #123, Closes #123 i commit-meddelande stänger automatiskt."},
            {"question": "Vad är protected branches?", "options": ["Backup-branches", "Branches med regler före merge", "Krypterade branches", "Låsta branches"], "correct": 1, "explanation": "Protected branches kräver PR, reviews, status checks."},
            {"question": "Hur ändrar du senaste commit-meddelande?", "options": ["git edit last", "git commit --amend", "git reword", "git message edit"], "correct": 1, "explanation": "git commit --amend -m 'nytt msg' ändrar senaste commit."},
            {"question": "Vad är pre-commit hooks?", "options": ["Pre-release commits", "Scripts som körs före commit", "Commit-krav", "Föregående commits"], "correct": 1, "explanation": "Hooks är scripts som körs automatiskt vid Git-events."},
            {"question": "Hur tar du bort untracked filer?", "options": ["git remove untracked", "git clean -fd", "git delete new", "git purge"], "correct": 1, "explanation": "git clean -fd tar bort untracked filer och directories."},
            {"question": "Vad gör git fetch vs pull?", "options": ["Samma sak", "fetch bara hämtar, pull hämtar+mergar", "fetch är snabbare", "pull är säkrare"], "correct": 1, "explanation": "fetch hämtar utan merge - säkrare att granska först. pull mergar direkt."},
        ],
        "hard": [
            {"question": "Vilka Git object-typer finns?", "options": ["file, dir, commit", "blob, tree, commit, tag", "data, meta, history", "source, binary, text"], "correct": 1, "explanation": "Git har blob (fil), tree (dir), commit (snapshot), tag objects."},
            {"question": "Vad gör git gc?", "options": ["Get commits", "Garbage Collection - packar objects", "Generate config", "Git clone"], "correct": 1, "explanation": "gc packar loose objects, tar bort unreachable data."},
            {"question": "Vad är rerere?", "options": ["Redo operation", "Reuse Recorded Resolution", "Remote reference", "Recursive resolve"], "correct": 1, "explanation": "rerere minns konfliktlösningar för återanvändning."},
            {"question": "Vad är git worktree?", "options": ["Katalogstruktur", "Flera working directories för samma repo", "Work history", "Tree view"], "correct": 1, "explanation": "Worktree låter dig ha flera checkouts av samma repo parallellt."},
            {"question": "Vad är sparse checkout?", "options": ["Partial clone", "Checka ut bara delar av repo", "Sparse commits", "Checkout cache"], "correct": 1, "explanation": "Sparse checkout laddar bara utvalda kataloger - bra för monorepos."},
            {"question": "Hur tar du bort fil från all historik?", "options": ["git rm --history", "git filter-repo --path fil", "git delete --all", "git purge fil"], "correct": 1, "explanation": "filter-repo (eller filter-branch) skriver om historik."},
            {"question": "Vad är shallow clone?", "options": ["Ytlig kopia", "Clone med begränsad historik", "Snabb clone", "Light clone"], "correct": 1, "explanation": "git clone --depth 1 hämtar bara senaste commit."},
            {"question": "Vad gör Git LFS?", "options": ["Large File System", "Lagrar stora filer separat", "Local File Sync", "Linked File Storage"], "correct": 1, "explanation": "LFS lagrar stora filer i separat storage, sparar pekare i repo."},
            {"question": "Hur signerar du commits?", "options": ["git commit --sign", "git commit -S", "git commit --gpg", "git sign commit"], "correct": 1, "explanation": "git commit -S signerar med din GPG/SSH-nyckel."},
            {"question": "Vad är git bundle?", "options": ["Package manager", "Packar repo till fil för offline", "Bundle branches", "Zip-arkiv"], "correct": 1, "explanation": "bundle skapar portabel fil av repo för offline-transfer."},
            {"question": "Vad är git notes?", "options": ["Commit comments", "Extra metadata utan att ändra commits", "Release notes", "Branch notes"], "correct": 1, "explanation": "notes lägger till metadata till commits utan att ändra dem."},
            {"question": "Vilken merge strategy är default?", "options": ["ours", "recursive/ort", "theirs", "octopus"], "correct": 1, "explanation": "recursive (nu ort) är default för 2-branch merge."},
            {"question": "Vad är octopus merge?", "options": ["8-vägs merge", "Merge av flera branches samtidigt", "Complex merge", "Parallel merge"], "correct": 1, "explanation": "octopus mergar >2 branches om inga konflikter finns."},
            {"question": "Vad lagrar credential.helper store?", "options": ["I minnet", "Plaintext på disk", "Krypterat", "I keychain"], "correct": 1, "explanation": "store sparar okrypterat på disk. manager använder OS keychain."},
            {"question": "Vad är fork workflow?", "options": ["Branch workflow", "Fork repo, upstream remote, PR från fork", "Feature flags", "Trunk-based"], "correct": 1, "explanation": "Fork workflow: fork på GitHub, lokal klon, upstream för sync."},
            {"question": "Vad gör git blame -w?", "options": ["Visa warnings", "Ignorera whitespace", "Wide output", "Watch mode"], "correct": 1, "explanation": "-w ignorerar whitespace-ändringar i blame."},
            {"question": "Hur hittar du commit som tog bort text?", "options": ["git log --grep", "git log -S 'text'", "git search text", "git find deleted"], "correct": 1, "explanation": "-S (pickaxe) söker efter ändringar som lade till/tog bort text."},
            {"question": "Vad är git maintenance?", "options": ["Cleanup command", "Automatiska optimeringar", "Manual gc", "Maintenance mode"], "correct": 1, "explanation": "git maintenance sätter upp automatiska optimerings-tasks."},
            {"question": "Vad är replace refs?", "options": ["Branch replacement", "Skapar alternativa commits", "Remote replacement", "Tag replacement"], "correct": 1, "explanation": "git replace skapar alternativa commits för grafting historik."},
            {"question": "Vad är packfiles?", "options": ["Backup-filer", "Komprimerade Git objects", "Package files", "Packed branches"], "correct": 1, "explanation": "Git packar loose objects till packfiles med delta compression."},
        ],
    },

    "nodes": [
        {"id": 1, "title": "Git Introduktion", "slug": "git-intro"},
        {"id": 2, "title": "Repository Basics", "slug": "repo-basics"},
        {"id": 3, "title": "Commits & Staging", "slug": "commits-staging"},
        {"id": 4, "title": "Branches Grunderna", "slug": "branches-basics"},
        {"id": 5, "title": "Merging", "slug": "merging"},
        {"id": 6, "title": "Remote Repositories", "slug": "remote-repos"},
        {"id": 7, "title": "GitHub Fundamentals", "slug": "github-fundamentals"},
        {"id": 8, "title": "Pull Requests", "slug": "pull-requests"},
        {"id": 9, "title": "Merge Conflicts", "slug": "merge-conflicts"},
        {"id": 10, "title": "Git Stash", "slug": "git-stash"},
        {"id": 11, "title": "Git Rebase", "slug": "git-rebase"},
        {"id": 12, "title": "Interactive Rebase", "slug": "interactive-rebase"},
        {"id": 13, "title": "Tags & Releases", "slug": "tags-releases"},
        {"id": 14, "title": "Git Bisect", "slug": "git-bisect"},
        {"id": 15, "title": "GitHub Actions Intro", "slug": "github-actions-intro"},
        {"id": 16, "title": "Advanced Workflows", "slug": "advanced-workflows"},
        {"id": 17, "title": "Git Hooks", "slug": "git-hooks"},
        {"id": 18, "title": "Git Internals", "slug": "git-internals"},
        {"id": 19, "title": "Monorepo Strategies", "slug": "monorepo-strategies"},
        {"id": 20, "title": "Git Best Practices", "slug": "git-best-practices"},
    ],
}
