#!/usr/bin/env python3
"""
Översätter alla frågor och svar i manpage-tenta-quiz.ts till svenska
"""

import re

# Läs filen
with open('apps/frontend/src/data/manpage-tenta-quiz.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Översättningslexikon för vanliga termer och fraser
translations = {
    # Frågor - What does X do?
    "What does": "Vad gör",
    "What is": "Vad är",
    "Which": "Vilken",
    "How do you": "Hur",
    "How to": "Hur",
    "Where": "Var",
    "Why": "Varför",
    "When": "När",
    "Who": "Vem",
    " do?": "?",
    " do in bash?": " i bash?",
    " used for?": " till för?",
    "redirect?": "omdirigerar?",

    # Svar - tekniska termer
    "Appends output to a file": "Lägger till output i en fil",
    "Redirects stderr": "Omdirigerar stderr",
    "Sends output of one command as input to another": "Skickar output från ett kommando som input till ett annat",
    "Redirects output to a file": "Omdirigerar output till en fil",
    "Pipe output": "Pipe output",
    "Overwrite a file with output": "Skriver över en fil med output",
    "Redirect stderr": "Omdirigerar stderr",
    "Append output": "Lägger till output",
    "Append": "Lägger till",
    "Redirect stdin": "Omdirigerar stdin",
    "Pipe": "Pipe",
    "Overwrite": "Skriver över",
    "stderr": "stderr",
    "stdout": "stdout",
    "stdin": "stdin",
    "all output": "all output",
    "Last command exit status": "Senaste kommandots exit-status",
    "Shell version": "Shell-version",
    "User ID": "Användar-ID",
    "PID": "PID",
    "Process ID of current shell": "Process-ID för aktuellt shell",
    "Home directory": "Hemkatalog",
    "Current user": "Aktuell användare",
    "Current directory": "Aktuell katalog",
    "All arguments": "Alla argument",
    "Script name": "Skriptnamn",
    "Number of arguments": "Antal argument",
    "List files": "Lista filer",
    "Change directory": "Byt katalog",
    "Print working directory": "Skriv ut arbetskatalog",
    "Copy files": "Kopiera filer",
    "Move files": "Flytta filer",
    "Remove files": "Ta bort filer",
    "Create directory": "Skapa katalog",
    "Remove directory": "Ta bort katalog",
    "Display file content": "Visa filinnehåll",
    "Show first lines": "Visa första raderna",
    "Show last lines": "Visa sista raderna",
    "Search text": "Sök text",
    "Find files": "Hitta filer",
    "Change permissions": "Ändra rättigheter",
    "Change owner": "Ändra ägare",
    "Show processes": "Visa processer",
    "Kill process": "Döda process",
    "Background process": "Bakgrundsprocess",
    "Foreground process": "Förgrundsprocess",
    "Network configuration": "Nätverkskonfiguration",
    "Show network interfaces": "Visa nätverksgränssnitt",
    "Test connectivity": "Testa anslutning",
    "Download files": "Ladda ner filer",
    "Transfer files": "Överför filer",
    "Secure shell": "Säkert skal",
    "Archive files": "Arkivera filer",
    "Compress files": "Komprimera filer",
    "Extract files": "Extrahera filer",
    "Package manager": "Pakethanterare",
    "Install package": "Installera paket",
    "Update packages": "Uppdatera paket",
    "Remove package": "Ta bort paket",
    "System information": "Systeminformation",
    "Disk usage": "Diskanvändning",
    "Memory usage": "Minnesanvändning",
    "CPU information": "CPU-information",
    "User management": "Användarhantering",
    "Group management": "Grupphantering",
    "File permissions": "Filrättigheter",
    "Directory permissions": "Katalogrättigheter",
    "Execute permission": "Körrättighet",
    "Read permission": "Läsrättighet",
    "Write permission": "Skrivrättighet",
    "Owner": "Ägare",
    "Group": "Grupp",
    "Others": "Andra",
    "All users": "Alla användare",
    "Root user": "Root-användare",
    "Regular user": "Vanlig användare",
    "Super user": "Superanvändare",
    "Daemon": "Daemon",
    "Service": "Tjänst",
    "Process": "Process",
    "Thread": "Tråd",
    "Signal": "Signal",
    "Environment variable": "Miljövariabel",
    "Shell variable": "Shellvariabel",
    "Local variable": "Lokal variabel",
    "Global variable": "Global variabel",
    "Configuration file": "Konfigurationsfil",
    "Log file": "Loggfil",
    "Temporary file": "Temporär fil",
    "Hidden file": "Dold fil",
    "Symbolic link": "Symbolisk länk",
    "Hard link": "Hård länk",
    "Mount point": "Monteringspunkt",
    "File system": "Filsystem",
    "Partition": "Partition",
    "Volume": "Volym",
    "Block device": "Blockenhet",
    "Character device": "Teckenenhet",
    "Device file": "Enhetsfil",
    "Special file": "Specialfil",
    "Regular file": "Vanlig fil",
    "Directory": "Katalog",
    "Socket": "Socket",
    "Named pipe": "Namngiven pipe",
    "FIFO": "FIFO",

    # Kategorier
    "Pipes & Redirection": "Pipes & Omdirigering",
    "Variables": "Variabler",
    "File Operations": "Filoperationer",
    "Process Management": "Processhantering",
    "Network": "Nätverk",
    "Permissions": "Rättigheter",
    "User Management": "Användarhantering",
    "System Administration": "Systemadministration",
    "Text Processing": "Textbearbetning",
    "Scripting": "Skript",
    "Containers": "Containers",
    "Package Management": "Pakethantering",
}

# Mer omfattande översättningar för hela frågor
question_translations = {
    # G-frågor
    "What does | do in bash?": "Vad gör | i bash?",
    "What does > do?": "Vad gör >?",
    "What does >> do?": "Vad gör >>?",
    "What does 2> redirect?": "Vad omdirigerar 2>?",
    "Which file descriptor is stdout?": "Vilken fildeskriptor är stdout?",
    "What is $?": "Vad är $??",
    "What is $$?": "Vad är $$?",
    "What is $HOME?": "Vad är $HOME?",
    "What is $USER?": "Vad är $USER?",
    "What is $PWD?": "Vad är $PWD?",
    "What is $@?": "Vad är $@?",
    "What is $0?": "Vad är $0?",
    "What is $#?": "Vad är $#?",
    "What does ls do?": "Vad gör ls?",
    "What does cd do?": "Vad gör cd?",
    "What does pwd do?": "Vad gör pwd?",
    "What does cp do?": "Vad gör cp?",
    "What does mv do?": "Vad gör mv?",
    "What does rm do?": "Vad gör rm?",
    "What does mkdir do?": "Vad gör mkdir?",
    "What does rmdir do?": "Vad gör rmdir?",
    "What does cat do?": "Vad gör cat?",
    "What does head do?": "Vad gör head?",
    "What does tail do?": "Vad gör tail?",
    "What does grep do?": "Vad gör grep?",
    "What does find do?": "Vad gör find?",
    "What does chmod do?": "Vad gör chmod?",
    "What does chown do?": "Vad gör chown?",
    "What does ps do?": "Vad gör ps?",
    "What does kill do?": "Vad gör kill?",
    "What does top do?": "Vad gör top?",
    "What does htop do?": "Vad gör htop?",
    "What does df do?": "Vad gör df?",
    "What does du do?": "Vad gör du?",
    "What does free do?": "Vad gör free?",
    "What does uname do?": "Vad gör uname?",
    "What does whoami do?": "Vad gör whoami?",
    "What does id do?": "Vad gör id?",
    "What does which do?": "Vad gör which?",
    "What does whereis do?": "Vad gör whereis?",
    "What does locate do?": "Vad gör locate?",
    "What does man do?": "Vad gör man?",
    "What does echo do?": "Vad gör echo?",
    "What does printf do?": "Vad gör printf?",
    "What does read do?": "Vad gör read?",
    "What does export do?": "Vad gör export?",
    "What does source do?": "Vad gör source?",
    "What does alias do?": "Vad gör alias?",
    "What does unalias do?": "Vad gör unalias?",
    "What does history do?": "Vad gör history?",
    "What does clear do?": "Vad gör clear?",
    "What does exit do?": "Vad gör exit?",
    "What does sudo do?": "Vad gör sudo?",
    "What does su do?": "Vad gör su?",
    "What does passwd do?": "Vad gör passwd?",
    "What does useradd do?": "Vad gör useradd?",
    "What does userdel do?": "Vad gör userdel?",
    "What does usermod do?": "Vad gör usermod?",
    "What does groupadd do?": "Vad gör groupadd?",
    "What does groupdel do?": "Vad gör groupdel?",
    "What does groups do?": "Vad gör groups?",
    "What does chgrp do?": "Vad gör chgrp?",
    "What does umask do?": "Vad gör umask?",
    "What does ln do?": "Vad gör ln?",
    "What does touch do?": "Vad gör touch?",
    "What does file do?": "Vad gör file?",
    "What does stat do?": "Vad gör stat?",
    "What does wc do?": "Vad gör wc?",
    "What does sort do?": "Vad gör sort?",
    "What does uniq do?": "Vad gör uniq?",
    "What does cut do?": "Vad gör cut?",
    "What does paste do?": "Vad gör paste?",
    "What does tr do?": "Vad gör tr?",
    "What does sed do?": "Vad gör sed?",
    "What does awk do?": "Vad gör awk?",
    "What does diff do?": "Vad gör diff?",
    "What does patch do?": "Vad gör patch?",
    "What does tar do?": "Vad gör tar?",
    "What does gzip do?": "Vad gör gzip?",
    "What does gunzip do?": "Vad gör gunzip?",
    "What does zip do?": "Vad gör zip?",
    "What does unzip do?": "Vad gör unzip?",
    "What does ping do?": "Vad gör ping?",
    "What does curl do?": "Vad gör curl?",
    "What does wget do?": "Vad gör wget?",
    "What does ssh do?": "Vad gör ssh?",
    "What does scp do?": "Vad gör scp?",
    "What does rsync do?": "Vad gör rsync?",
    "What does netstat do?": "Vad gör netstat?",
    "What does ss do?": "Vad gör ss?",
    "What does ifconfig do?": "Vad gör ifconfig?",
    "What does ip do?": "Vad gör ip?",
    "What does hostname do?": "Vad gör hostname?",
    "What does nslookup do?": "Vad gör nslookup?",
    "What does dig do?": "Vad gör dig?",
    "What does traceroute do?": "Vad gör traceroute?",
    "What does mount do?": "Vad gör mount?",
    "What does umount do?": "Vad gör umount?",
    "What does fdisk do?": "Vad gör fdisk?",
    "What does mkfs do?": "Vad gör mkfs?",
    "What does fsck do?": "Vad gör fsck?",
    "What does apt do?": "Vad gör apt?",
    "What does apt-get do?": "Vad gör apt-get?",
    "What does dpkg do?": "Vad gör dpkg?",
    "What does yum do?": "Vad gör yum?",
    "What does dnf do?": "Vad gör dnf?",
    "What does rpm do?": "Vad gör rpm?",
    "What does systemctl do?": "Vad gör systemctl?",
    "What does service do?": "Vad gör service?",
    "What does journalctl do?": "Vad gör journalctl?",
    "What does crontab do?": "Vad gör crontab?",
    "What does at do?": "Vad gör at?",
    "What does jobs do?": "Vad gör jobs?",
    "What does bg do?": "Vad gör bg?",
    "What does fg do?": "Vad gör fg?",
    "What does nohup do?": "Vad gör nohup?",
    "What does screen do?": "Vad gör screen?",
    "What does tmux do?": "Vad gör tmux?",
    "What does docker do?": "Vad gör docker?",
    "What does docker-compose do?": "Vad gör docker-compose?",
    "What does kubectl do?": "Vad gör kubectl?",

    # Mer komplexa frågor
    "What does ls -la show?": "Vad visar ls -la?",
    "What does chmod 755 do?": "Vad gör chmod 755?",
    "What does chmod 644 do?": "Vad gör chmod 644?",
    "What does chmod +x do?": "Vad gör chmod +x?",
    "What does grep -r do?": "Vad gör grep -r?",
    "What does grep -i do?": "Vad gör grep -i?",
    "What does grep -v do?": "Vad gör grep -v?",
    "What does find . -name do?": "Vad gör find . -name?",
    "What does ps aux show?": "Vad visar ps aux?",
    "What does kill -9 do?": "Vad gör kill -9?",
    "What does tar -xvf do?": "Vad gör tar -xvf?",
    "What does tar -cvf do?": "Vad gör tar -cvf?",
    "What does df -h show?": "Vad visar df -h?",
    "What does du -sh do?": "Vad gör du -sh?",
    "What does apt update do?": "Vad gör apt update?",
    "What does apt upgrade do?": "Vad gör apt upgrade?",
    "What does apt install do?": "Vad gör apt install?",
    "What does systemctl start do?": "Vad gör systemctl start?",
    "What does systemctl stop do?": "Vad gör systemctl stop?",
    "What does systemctl status do?": "Vad gör systemctl status?",
    "What does systemctl enable do?": "Vad gör systemctl enable?",
    "What does docker ps show?": "Vad visar docker ps?",
    "What does docker run do?": "Vad gör docker run?",
    "What does docker build do?": "Vad gör docker build?",
    "What does docker pull do?": "Vad gör docker pull?",
    "What does docker push do?": "Vad gör docker push?",
    "What does docker exec do?": "Vad gör docker exec?",
    "What does docker logs show?": "Vad visar docker logs?",
    "What does kubectl get pods show?": "Vad visar kubectl get pods?",
    "What does kubectl apply do?": "Vad gör kubectl apply?",
    "What does kubectl delete do?": "Vad gör kubectl delete?",
}

# Svar-översättningar
answer_translations = {
    # Tekniska termer (behåll vissa engelska)
    "Appends output to a file": "Lägger till output i en fil",
    "Redirects stderr": "Omdirigerar stderr",
    "Sends output of one command as input to another": "Skickar output från ett kommando som input till ett annat",
    "Redirects output to a file": "Omdirigerar output till en fil",
    "Pipe output": "Skickar output via pipe",
    "Overwrite a file with output": "Skriver över en fil med output",
    "Redirect stderr": "Omdirigera stderr",
    "Append output": "Lägg till output",
    "Append": "Lägg till",
    "Redirect stdin": "Omdirigera stdin",
    "Pipe": "Pipe",
    "Overwrite": "Skriv över",
    "all output": "all output",
    "Last command exit status": "Senaste kommandots exit-status",
    "Shell version": "Shell-version",
    "User ID": "Användar-ID",
    "Process ID of current shell": "Process-ID för aktuellt shell",
    "Home directory": "Hemkatalog",
    "Current user": "Aktuell användare",
    "Current directory": "Aktuell katalog",
    "All arguments": "Alla argument",
    "Script name": "Skriptnamn",
    "Number of arguments": "Antal argument",
    "List files": "Lista filer",
    "List directory contents": "Lista kataloginnehåll",
    "Change directory": "Byt katalog",
    "Print working directory": "Skriv ut arbetskatalog",
    "Show current directory": "Visa aktuell katalog",
    "Copy files": "Kopiera filer",
    "Copy files and directories": "Kopiera filer och kataloger",
    "Move files": "Flytta filer",
    "Move or rename files": "Flytta eller byt namn på filer",
    "Rename files": "Byt namn på filer",
    "Remove files": "Ta bort filer",
    "Delete files": "Ta bort filer",
    "Remove files and directories": "Ta bort filer och kataloger",
    "Create directory": "Skapa katalog",
    "Make directories": "Skapa kataloger",
    "Remove directory": "Ta bort katalog",
    "Remove empty directories": "Ta bort tomma kataloger",
    "Display file content": "Visa filinnehåll",
    "Concatenate and display files": "Sammanfoga och visa filer",
    "Show first lines": "Visa första raderna",
    "Show first lines of a file": "Visa första raderna i en fil",
    "Show last lines": "Visa sista raderna",
    "Show last lines of a file": "Visa sista raderna i en fil",
    "Follow file in real-time": "Följ fil i realtid",
    "Search text": "Sök text",
    "Search for patterns in files": "Sök efter mönster i filer",
    "Search text patterns": "Sök textmönster",
    "Find files": "Hitta filer",
    "Search for files": "Sök efter filer",
    "Search for files in directory hierarchy": "Sök efter filer i kataloghierarki",
    "Change permissions": "Ändra rättigheter",
    "Change file permissions": "Ändra filrättigheter",
    "Change file mode": "Ändra filläge",
    "Change owner": "Ändra ägare",
    "Change file owner": "Ändra filägare",
    "Change file owner and group": "Ändra filägare och grupp",
    "Show processes": "Visa processer",
    "Display processes": "Visa processer",
    "Report process status": "Rapportera processstatus",
    "List running processes": "Lista körande processer",
    "Kill process": "Döda process",
    "Terminate process": "Avsluta process",
    "Send signal to process": "Skicka signal till process",
    "Real-time process viewer": "Realtidsprocessvisare",
    "Interactive process viewer": "Interaktiv processvisare",
    "Display disk usage": "Visa diskanvändning",
    "Show disk space usage": "Visa diskutrymmesanvändning",
    "Report file system disk space": "Rapportera filsystemets diskutrymme",
    "Estimate file space usage": "Uppskatta filutrymme",
    "Display memory usage": "Visa minnesanvändning",
    "Show memory usage": "Visa minnesanvändning",
    "Display system information": "Visa systeminformation",
    "Print system information": "Skriv ut systeminformation",
    "Show current username": "Visa aktuellt användarnamn",
    "Print effective user ID": "Skriv ut effektivt användar-ID",
    "Show user and group IDs": "Visa användar- och grupp-ID",
    "Print user identity": "Skriv ut användaridentitet",
    "Locate a command": "Lokalisera ett kommando",
    "Show command path": "Visa kommandosökväg",
    "Locate binary, source, manual": "Lokalisera binär, källa, manual",
    "Find files by name": "Hitta filer via namn",
    "Display manual pages": "Visa manualsidor",
    "Show command manual": "Visa kommandomanual",
    "Display a line of text": "Visa en textrad",
    "Print text": "Skriv ut text",
    "Format and print text": "Formatera och skriv ut text",
    "Read input": "Läs indata",
    "Read a line of input": "Läs en rad indata",
    "Export environment variable": "Exportera miljövariabel",
    "Set environment variable": "Sätt miljövariabel",
    "Execute commands from file": "Kör kommandon från fil",
    "Run script in current shell": "Kör skript i aktuellt shell",
    "Create command alias": "Skapa kommandoalias",
    "Define command shortcut": "Definiera kommandogenväg",
    "Remove alias": "Ta bort alias",
    "Show command history": "Visa kommandohistorik",
    "Display command history": "Visa kommandohistorik",
    "Clear terminal screen": "Rensa terminalskärm",
    "Clear the screen": "Rensa skärmen",
    "Exit shell": "Avsluta shell",
    "Exit the shell": "Avsluta shell",
    "Run as superuser": "Kör som superanvändare",
    "Execute as root": "Kör som root",
    "Execute command as another user": "Kör kommando som annan användare",
    "Switch user": "Byt användare",
    "Switch to another user": "Byt till annan användare",
    "Change password": "Ändra lösenord",
    "Update user password": "Uppdatera användarlösenord",
    "Create new user": "Skapa ny användare",
    "Add user account": "Lägg till användarkonto",
    "Delete user": "Ta bort användare",
    "Remove user account": "Ta bort användarkonto",
    "Modify user": "Ändra användare",
    "Modify user account": "Ändra användarkonto",
    "Create new group": "Skapa ny grupp",
    "Add group": "Lägg till grupp",
    "Delete group": "Ta bort grupp",
    "Remove group": "Ta bort grupp",
    "Show user groups": "Visa användargrupper",
    "Print group memberships": "Skriv ut gruppmedlemskap",
    "Change group ownership": "Ändra gruppägande",
    "Change file group": "Ändra filgrupp",
    "Set default permissions": "Sätt standardrättigheter",
    "Set file creation mask": "Sätt filskapningsmask",
    "Create links": "Skapa länkar",
    "Make links between files": "Skapa länkar mellan filer",
    "Create symbolic link": "Skapa symbolisk länk",
    "Create empty file": "Skapa tom fil",
    "Update file timestamp": "Uppdatera filtidsstämpel",
    "Change file timestamps": "Ändra filtidsstämplar",
    "Determine file type": "Bestäm filtyp",
    "Show file type": "Visa filtyp",
    "Display file status": "Visa filstatus",
    "Show file information": "Visa filinformation",
    "Count words": "Räkna ord",
    "Count lines, words, bytes": "Räkna rader, ord, bytes",
    "Word, line, character count": "Ord-, rad-, teckenräkning",
    "Sort lines": "Sortera rader",
    "Sort text file lines": "Sortera textfilrader",
    "Sort lines of text": "Sortera textrader",
    "Remove duplicates": "Ta bort dubletter",
    "Report or omit repeated lines": "Rapportera eller utelämna upprepade rader",
    "Filter unique lines": "Filtrera unika rader",
    "Cut sections": "Klipp ut sektioner",
    "Remove sections from lines": "Ta bort sektioner från rader",
    "Extract columns": "Extrahera kolumner",
    "Merge lines": "Slå ihop rader",
    "Merge lines of files": "Slå ihop rader från filer",
    "Join file lines": "Sammanfoga filrader",
    "Translate characters": "Översätt tecken",
    "Translate or delete characters": "Översätt eller ta bort tecken",
    "Replace characters": "Ersätt tecken",
    "Stream editor": "Strömredigerare",
    "Edit text stream": "Redigera textström",
    "Pattern scanning": "Mönstersökning",
    "Text processing language": "Textbearbetningsspråk",
    "Process text patterns": "Bearbeta textmönster",
    "Compare files": "Jämför filer",
    "Show file differences": "Visa filskillnader",
    "Find differences between files": "Hitta skillnader mellan filer",
    "Apply patches": "Tillämpa patchar",
    "Apply diff output": "Tillämpa diff-output",
    "Archive files": "Arkivera filer",
    "Create/extract archives": "Skapa/extrahera arkiv",
    "Tape archive": "Bandarkiv",
    "Compress files": "Komprimera filer",
    "Compress with gzip": "Komprimera med gzip",
    "Decompress files": "Dekomprimera filer",
    "Decompress gzip files": "Dekomprimera gzip-filer",
    "Create zip archive": "Skapa zip-arkiv",
    "Package and compress files": "Paketera och komprimera filer",
    "Extract zip archive": "Extrahera zip-arkiv",
    "Unpack zip files": "Packa upp zip-filer",
    "Test network connectivity": "Testa nätverksanslutning",
    "Send ICMP packets": "Skicka ICMP-paket",
    "Check host availability": "Kontrollera värdtillgänglighet",
    "Transfer data from URL": "Överför data från URL",
    "Make HTTP requests": "Gör HTTP-förfrågningar",
    "Download from web": "Ladda ner från webben",
    "Download files from web": "Ladda ner filer från webben",
    "Non-interactive download": "Icke-interaktiv nedladdning",
    "Secure shell connection": "Säker shell-anslutning",
    "Remote login": "Fjärrinloggning",
    "Connect to remote host": "Anslut till fjärrvärd",
    "Secure copy": "Säker kopiering",
    "Copy files over SSH": "Kopiera filer över SSH",
    "Remote file copy": "Fjärrfilkopiering",
    "Remote file sync": "Fjärrfilsynkronisering",
    "Sync files remotely": "Synkronisera filer på distans",
    "Fast file transfer": "Snabb filöverföring",
    "Show network connections": "Visa nätverksanslutningar",
    "Network statistics": "Nätverksstatistik",
    "Display network connections": "Visa nätverksanslutningar",
    "Socket statistics": "Socket-statistik",
    "Show socket info": "Visa socket-info",
    "Configure network": "Konfigurera nätverk",
    "Configure network interfaces": "Konfigurera nätverksgränssnitt",
    "Show/configure network interfaces": "Visa/konfigurera nätverksgränssnitt",
    "IP configuration": "IP-konfiguration",
    "Show/manipulate routing": "Visa/manipulera routing",
    "Show hostname": "Visa värdnamn",
    "Show/set system hostname": "Visa/sätt systemvärdnamn",
    "DNS lookup": "DNS-uppslag",
    "Query DNS servers": "Fråga DNS-servrar",
    "DNS lookup utility": "DNS-uppslagsverktyg",
    "Trace packet route": "Spåra paketrutt",
    "Show network path": "Visa nätverkssökväg",
    "Print route packets trace": "Skriv ut paketspårning",
    "Mount filesystem": "Montera filsystem",
    "Attach filesystem": "Koppla filsystem",
    "Unmount filesystem": "Avmontera filsystem",
    "Detach filesystem": "Koppla loss filsystem",
    "Partition table manipulator": "Partitionstabellmanipulator",
    "Manage disk partitions": "Hantera diskpartitioner",
    "Create filesystem": "Skapa filsystem",
    "Build a filesystem": "Bygg ett filsystem",
    "Check filesystem": "Kontrollera filsystem",
    "File system check": "Filsystemkontroll",
    "Repair filesystem": "Reparera filsystem",
    "Package manager": "Pakethanterare",
    "Manage packages": "Hantera paket",
    "Advanced package tool": "Avancerat paketverktyg",
    "Install packages": "Installera paket",
    "Debian package manager": "Debian-pakethanterare",
    "Manage .deb packages": "Hantera .deb-paket",
    "Yellowdog Updater Modified": "Yellowdog Updater Modified",
    "Package manager for RPM": "Pakethanterare för RPM",
    "Dandified YUM": "Dandified YUM",
    "Next-gen package manager": "Nästa generations pakethanterare",
    "RPM package manager": "RPM-pakethanterare",
    "Manage .rpm packages": "Hantera .rpm-paket",
    "Control systemd": "Kontrollera systemd",
    "Manage system services": "Hantera systemtjänster",
    "Control the systemd system": "Kontrollera systemd-systemet",
    "Manage services": "Hantera tjänster",
    "Run a System V init script": "Kör ett System V init-skript",
    "Query systemd journal": "Fråga systemd-journal",
    "View system logs": "Visa systemloggar",
    "Schedule periodic tasks": "Schemalägg periodiska uppgifter",
    "Manage cron jobs": "Hantera cron-jobb",
    "Schedule one-time task": "Schemalägg engångsuppgift",
    "Run command at specified time": "Kör kommando vid angiven tid",
    "List background jobs": "Lista bakgrundsjobb",
    "Show job status": "Visa jobbstatus",
    "Run job in background": "Kör jobb i bakgrunden",
    "Move job to background": "Flytta jobb till bakgrunden",
    "Run job in foreground": "Kör jobb i förgrunden",
    "Move job to foreground": "Flytta jobb till förgrunden",
    "Run immune to hangups": "Kör immun mot avbrott",
    "Run command ignoring hangup": "Kör kommando som ignorerar avbrott",
    "Terminal multiplexer": "Terminalmultiplexer",
    "Multiple terminal sessions": "Flera terminalsessioner",
    "Container management": "Containerhantering",
    "Manage Docker containers": "Hantera Docker-containers",
    "Run containers": "Kör containers",
    "Multi-container Docker": "Multi-container Docker",
    "Define multi-container apps": "Definiera multi-container-appar",
    "Kubernetes CLI": "Kubernetes CLI",
    "Manage Kubernetes": "Hantera Kubernetes",
    "Control Kubernetes cluster": "Kontrollera Kubernetes-kluster",

    # Flaggor och optioner
    "List all files including hidden": "Lista alla filer inklusive dolda",
    "Long format with details": "Långt format med detaljer",
    "Human readable sizes": "Läsbara storlekar",
    "Recursive": "Rekursiv",
    "Recursively": "Rekursivt",
    "Force": "Tvinga",
    "Interactive": "Interaktiv",
    "Verbose": "Utförlig",
    "Quiet": "Tyst",
    "Create": "Skapa",
    "Extract": "Extrahera",
    "Compress": "Komprimera",
    "Decompress": "Dekomprimera",
    "Follow symlinks": "Följ symboliska länkar",
    "Preserve permissions": "Bevara rättigheter",
    "Case insensitive": "Skiftlägesokänslig",
    "Invert match": "Invertera matchning",
    "Count matches": "Räkna matchningar",
    "Line numbers": "Radnummer",
    "Show line numbers": "Visa radnummer",
    "With line numbers": "Med radnummer",
    "Only matching": "Endast matchande",
    "Extended regex": "Utökat regex",
    "Fixed strings": "Fasta strängar",

    # Docker-specifikt
    "List running containers": "Lista körande containers",
    "List all containers": "Lista alla containers",
    "Run a container": "Kör en container",
    "Start a container": "Starta en container",
    "Stop a container": "Stoppa en container",
    "Remove a container": "Ta bort en container",
    "Build an image": "Bygg en image",
    "Pull an image": "Hämta en image",
    "Push an image": "Skicka en image",
    "List images": "Lista images",
    "Remove an image": "Ta bort en image",
    "Execute command in container": "Kör kommando i container",
    "View container logs": "Visa container-loggar",
    "Inspect container": "Inspektera container",
    "Show container stats": "Visa container-statistik",

    # Kubernetes-specifikt
    "List pods": "Lista pods",
    "List all resources": "Lista alla resurser",
    "Apply configuration": "Tillämpa konfiguration",
    "Delete resources": "Ta bort resurser",
    "Describe resource": "Beskriv resurs",
    "Get logs": "Hämta loggar",
    "Execute in pod": "Kör i pod",
    "Port forward": "Vidarebefordra port",
    "Scale deployment": "Skala deployment",

    # Rättigheter
    "Read, write, execute for all": "Läs, skriv, kör för alla",
    "Read and execute for all": "Läs och kör för alla",
    "Read and write for owner": "Läs och skriv för ägare",
    "Read only for all": "Endast läs för alla",
    "Full permissions for owner": "Fulla rättigheter för ägare",
    "No permissions": "Inga rättigheter",
    "Add execute permission": "Lägg till körrättighet",
    "Remove write permission": "Ta bort skrivrättighet",
    "Set read permission": "Sätt läsrättighet",

    # Övrigt
    "yes": "ja",
    "no": "nej",
    "true": "sant",
    "false": "falskt",
    "enabled": "aktiverad",
    "disabled": "inaktiverad",
    "running": "körs",
    "stopped": "stoppad",
    "active": "aktiv",
    "inactive": "inaktiv",
    "success": "lyckades",
    "failure": "misslyckades",
    "error": "fel",
    "warning": "varning",
    "info": "info",
    "debug": "debug",
}

# Funktion för att översätta en fråga
def translate_question(q):
    # Kolla om det finns en direkt översättning
    if q in question_translations:
        return question_translations[q]

    # Annars, försök med generella mönster
    result = q

    # "What does X do?" -> "Vad gör X?"
    match = re.match(r"What does (.+) do\?", q)
    if match:
        return f"Vad gör {match.group(1)}?"

    # "What does X show?" -> "Vad visar X?"
    match = re.match(r"What does (.+) show\?", q)
    if match:
        return f"Vad visar {match.group(1)}?"

    # "What is X?" -> "Vad är X?"
    match = re.match(r"What is (.+)\?", q)
    if match:
        return f"Vad är {match.group(1)}?"

    # "Which X is Y?" -> "Vilken X är Y?"
    match = re.match(r"Which (.+) is (.+)\?", q)
    if match:
        return f"Vilken {match.group(1)} är {match.group(2)}?"

    # "How do you X?" -> "Hur X man?"
    match = re.match(r"How do you (.+)\?", q)
    if match:
        return f"Hur {match.group(1)}?"

    # "How to X?" -> "Hur X?"
    match = re.match(r"How to (.+)\?", q)
    if match:
        return f"Hur {match.group(1)}?"

    # "Where is X?" -> "Var finns X?"
    match = re.match(r"Where is (.+)\?", q)
    if match:
        return f"Var finns {match.group(1)}?"

    return result

# Funktion för att översätta ett svar
def translate_answer(a):
    # Kolla om det finns en direkt översättning
    if a in answer_translations:
        return answer_translations[a]
    return a

# Hitta alla frågor och svar och översätt dem
def process_file(content):
    # Mönster för att hitta frågor
    question_pattern = r"question: '([^']+)'"

    # Mönster för att hitta svar (options)
    options_pattern = r"options: \[\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',?\s*\]"

    # Ersätt frågor
    def replace_question(match):
        original = match.group(1)
        translated = translate_question(original)
        return f"question: '{translated}'"

    content = re.sub(question_pattern, replace_question, content)

    # Ersätt svar
    def replace_options(match):
        o1 = translate_answer(match.group(1))
        o2 = translate_answer(match.group(2))
        o3 = translate_answer(match.group(3))
        o4 = translate_answer(match.group(4))
        return f"options: [\n            '{o1}',\n            '{o2}',\n            '{o3}',\n            '{o4}',\n        ]"

    content = re.sub(options_pattern, replace_options, content)

    return content

# Bearbeta och spara
new_content = process_file(content)

with open('apps/frontend/src/data/manpage-tenta-quiz.ts', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("✅ Översättning klar!")
print("Kontrollera filen för att verifiera.")
