"""
Ansible Mastery - Study Data
============================

90 Flashcards (30 easy, 30 medium, 30 hard)
60 Quiz Questions (20 easy, 20 medium, 20 hard)
"""

ANSIBLE_STUDY_DATA = {
    "module_slug": "ansible-mastery",
    "module_title": "Ansible",
    "module_description": "Configuration Management och Automation med Ansible",
    "icon": "Settings",

    "flashcards": {
        "easy": [
            {"front": "Vad är Ansible?", "back": "Agentless automation tool för configuration management, application deployment och orchestration."},
            {"front": "Vad menas med agentless?", "back": "Ingen software behöver installeras på managed nodes. Ansible använder SSH."},
            {"front": "Vad är en playbook?", "back": "YAML-fil som definierar automation tasks. Beskriver desired state."},
            {"front": "Vad är inventory?", "back": "Lista över hosts/servers som Ansible ska hantera. INI eller YAML format."},
            {"front": "Hur kör du en playbook?", "back": "ansible-playbook playbook.yml - kör alla tasks i playbooken."},
            {"front": "Vad är en task?", "back": "En enskild åtgärd i playbook - t.ex. installera paket, kopiera fil, starta tjänst."},
            {"front": "Vad är en module?", "back": "Inbyggd funktion för specifik uppgift. apt, yum, copy, file, service, etc."},
            {"front": "Hur installerar du paket med Ansible?", "back": "apt: name=nginx state=present (Debian) eller yum: name=nginx state=present (RHEL)"},
            {"front": "Vad är state: present?", "back": "Säkerställer att resursen finns. state: absent tar bort den."},
            {"front": "Vad är YAML?", "back": "YAML Ain't Markup Language - dataformat Ansible använder. Indentering är viktigt!"},
            {"front": "Hur definierar du hosts i playbook?", "back": "hosts: webservers - anger vilka hosts från inventory som ska påverkas."},
            {"front": "Vad är en play?", "back": "En mapping av hosts till tasks. En playbook kan ha flera plays."},
            {"front": "Hur kör du ad-hoc kommando?", "back": "ansible webservers -m ping - kör ping-modul på webservers grupp."},
            {"front": "Vad gör ping-modulen?", "back": "Testar anslutning och Python på remote host. Returnerar pong vid success."},
            {"front": "Hur kopierar du fil till remote?", "back": "copy: src=fil.txt dest=/path/fil.txt - kopierar lokal fil till remote."},
            {"front": "Vad är ansible.cfg?", "back": "Konfigurationsfil för Ansible. Inventory path, SSH settings, etc."},
            {"front": "Hur anger du become (sudo)?", "back": "become: yes i playbook eller -b flag vid körning."},
            {"front": "Vad är gather_facts?", "back": "Samlar systeminfo från hosts. ansible_os_family, ansible_hostname, etc."},
            {"front": "Hur startar du en tjänst?", "back": "service: name=nginx state=started enabled=yes"},
            {"front": "Vad är handlers?", "back": "Tasks som körs när de notifieras. T.ex. restart nginx efter config-ändring."},
            {"front": "Hur triggar du handler?", "back": "notify: handler_name i en task. Handler körs i slutet av play."},
            {"front": "Hur definierar du variabel?", "back": "vars: app_port: 8080 i playbook, eller i separata filer."},
            {"front": "Hur använder du variabel?", "back": "{{ variabelnamn }} - Jinja2 syntax. port: '{{ app_port }}'"},
            {"front": "Vad är template module?", "back": "Kopierar fil med Jinja2-variabler expanderade. template: src=config.j2 dest=/etc/app.conf"},
            {"front": "Vad är .j2 fil?", "back": "Jinja2 template-fil. Innehåller {{ variabler }} som ersätts vid körning."},
            {"front": "Hur kontrollerar du syntax?", "back": "ansible-playbook --syntax-check playbook.yml"},
            {"front": "Vad gör --check flag?", "back": "Dry run - visar vad som skulle hända utan att göra ändringar."},
            {"front": "Vad är idempotens?", "back": "Att köra samma playbook flera gånger ger samma resultat. Ansible är idempotent."},
            {"front": "Hur ser du vilka hosts matchar?", "back": "ansible webservers --list-hosts"},
            {"front": "Vad är ansible-galaxy?", "back": "Verktyg för att dela och ladda ner roles från Ansible Galaxy."},
        ],
        "medium": [
            {"front": "Vad är en role i Ansible?", "back": "Strukturerat sätt att organisera tasks, handlers, vars, templates. Återanvändbart."},
            {"front": "Vilken struktur har en role?", "back": "tasks/, handlers/, templates/, files/, vars/, defaults/, meta/ directories."},
            {"front": "Hur skapar du role-skelett?", "back": "ansible-galaxy init role_name - skapar katalogstruktur."},
            {"front": "Vad är defaults vs vars i role?", "back": "defaults/ har lägst prioritet (överskrivs lätt). vars/ har högre prioritet."},
            {"front": "Hur inkluderar du role i playbook?", "back": "roles: - role_name eller import_role/include_role tasks."},
            {"front": "Vad är loop i Ansible?", "back": "Itererar över lista. loop: ['pkg1', 'pkg2'] med {{ item }}"},
            {"front": "Vad ersatte with_items?", "back": "loop: - modern syntax. with_items fungerar men loop rekommenderas."},
            {"front": "Hur loopar du över dict?", "back": "loop: '{{ dict | dict2items }}' ger item.key och item.value"},
            {"front": "Vad är when condition?", "back": "Villkorlig körning. when: ansible_os_family == 'Debian'"},
            {"front": "Hur kombinerar du villkor?", "back": "when: var1 and var2 eller when: var1 or var2"},
            {"front": "Vad är register?", "back": "Sparar task output. register: result, sedan result.stdout, result.rc"},
            {"front": "Hur kontrollerar du task-resultat?", "back": "when: result.rc == 0 eller when: result is failed"},
            {"front": "Vad är block i Ansible?", "back": "Grupperar tasks. Kan ha rescue (vid fel) och always (körs alltid)."},
            {"front": "Hur hanterar du fel med block?", "back": "block: tasks rescue: error_handling always: cleanup"},
            {"front": "Vad är ansible_facts?", "back": "Dict med insamlad info. ansible_facts['os_family'], ansible_facts['hostname']"},
            {"front": "Hur sätter du custom fact?", "back": "set_fact: my_var: value - skapar variabel runtime."},
            {"front": "Vad är delegate_to?", "back": "Kör task på annan host. delegate_to: localhost för lokal körning."},
            {"front": "Vad är run_once?", "back": "Kör task bara en gång oavsett antal hosts. run_once: true"},
            {"front": "Hur väntar du på port?", "back": "wait_for: port=80 host={{ inventory_hostname }} - väntar tills port öppnas."},
            {"front": "Vad är serial i playbook?", "back": "Antal hosts att köra på samtidigt. serial: 2 för rolling updates."},
            {"front": "Hur ignorerar du fel?", "back": "ignore_errors: yes - fortsätter även om task misslyckas."},
            {"front": "Vad är changed_when?", "back": "Överskriver changed-status. changed_when: false om task alltid rapporterar changed."},
            {"front": "Vad är failed_when?", "back": "Custom failure condition. failed_when: result.rc != 0 and 'error' in result.stderr"},
            {"front": "Hur inkluderar du tasks dynamiskt?", "back": "include_tasks: file.yml vs import_tasks (statisk)."},
            {"front": "Skillnad include vs import?", "back": "import är statisk (parse time). include är dynamisk (runtime)."},
            {"front": "Vad är Ansible Vault?", "back": "Krypterar känslig data. ansible-vault encrypt secrets.yml"},
            {"front": "Hur kör du med vault?", "back": "--ask-vault-pass eller --vault-password-file"},
            {"front": "Vad är lookup plugin?", "back": "Hämtar data från externa källor. '{{ lookup('file', '/path/file') }}'"},
            {"front": "Vad är filter i Jinja2?", "back": "Transformerar data. {{ list | join(',') }}, {{ var | default('val') }}"},
            {"front": "Hur testar du role?", "back": "Molecule - test framework för Ansible roles med Docker/VM."},
        ],
        "hard": [
            {"front": "Vad är callback plugins?", "back": "Anpassar output/logging. profile_tasks, json, yaml output formats."},
            {"front": "Hur skriver du custom module?", "back": "Python script i library/. Tar JSON input, returnerar JSON med changed, failed, etc."},
            {"front": "Vad är action plugins?", "back": "Körs på control node före module. copy, template, fetch är action plugins."},
            {"front": "Vad är connection plugins?", "back": "Hur Ansible ansluter. ssh, local, docker, winrm för Windows."},
            {"front": "Vad är inventory plugins?", "back": "Dynamisk inventory från sources. aws_ec2, azure_rm, gcp_compute."},
            {"front": "Hur använder du dynamic inventory?", "back": "Plugin-fil eller script som returnerar JSON. ansible-inventory --list"},
            {"front": "Vad är facts caching?", "back": "Sparar facts för snabbare körning. fact_caching = jsonfile i ansible.cfg"},
            {"front": "Vad är ansible-pull?", "back": "Omvänd modell - nodes hämtar config från git istället för push."},
            {"front": "Hur optimerar du stora inventories?", "back": "Forks (parallellism), pipelining, mitogen för snabbare execution."},
            {"front": "Vad är mitogen?", "back": "Python library som dramatiskt snabbar upp Ansible genom effektivare remote execution."},
            {"front": "Vad är strategy plugins?", "back": "Hur tasks exekveras. linear (default), free (ingen väntan), debug."},
            {"front": "Hur debuggar du playbook?", "back": "strategy: debug eller -vvvv för verbose. debugger: on_failed."},
            {"front": "Vad är async tasks?", "back": "Kör task async: 300 poll: 5. Lång körning utan timeout."},
            {"front": "Hur hanterar du Windows?", "back": "WinRM connection. win_* modules (win_service, win_copy, etc)."},
            {"front": "Vad är Ansible Collections?", "back": "Paketeringsformat för content. amazon.aws, community.general, etc."},
            {"front": "Hur installerar du collection?", "back": "ansible-galaxy collection install amazon.aws"},
            {"front": "Vad är requirements.yml?", "back": "Definierar roles och collections dependencies. ansible-galaxy install -r requirements.yml"},
            {"front": "Vad är AWX/Tower?", "back": "Web UI och REST API för Ansible. Scheduling, RBAC, credentials management."},
            {"front": "Hur strukturerar du stora projekt?", "back": "Inventories per miljö, group_vars/, host_vars/, roles/, playbooks separerade."},
            {"front": "Vad är assert module?", "back": "Validerar conditions. assert: that: - var is defined - var > 0"},
            {"front": "Hur testar du med Molecule?", "back": "molecule init, molecule test. Skapar container, kör playbook, verifierar."},
            {"front": "Vad är idempotence test?", "back": "Kör playbook två gånger, andra körningen ska vara 'ok' inte 'changed'."},
            {"front": "Hur hanterar du secrets i CI/CD?", "back": "Environment vars, Vault med password file, external secret managers."},
            {"front": "Vad är Jinja2 tests?", "back": "Villkorstest: var is defined, var is number, var is iterable."},
            {"front": "Hur gör du rolling update?", "back": "serial: 1, max_fail_percentage, pre_tasks för health check."},
            {"front": "Vad är delegation för inventory?", "back": "delegate_to + delegate_facts: true sparar facts till delegerad host."},
            {"front": "Hur synkar du stora filer?", "back": "synchronize module (rsync wrapper) istället för copy för stora filer."},
            {"front": "Vad är throttle?", "back": "Begränsar antal parallella körningar av specifik task. throttle: 1"},
            {"front": "Hur hanterar du network devices?", "back": "network_cli connection, *_config modules (ios_config, junos_config)."},
            {"front": "Vad är Ansible Navigator?", "back": "TUI för Ansible. Ersätter ansible-playbook med bättre UX. ansible-navigator run playbook.yml"},
        ],
    },

    "quiz": {
        "easy": [
            {"question": "Vad menas med att Ansible är agentless?", "options": ["Har ingen GUI", "Kräver ingen installation på managed nodes", "Fungerar offline", "Ingen konfiguration behövs"], "correct": 1, "explanation": "Agentless betyder ingen agent-software på remote hosts. Ansible använder SSH."},
            {"question": "Vad är en playbook?", "options": ["Inventory-fil", "YAML-fil med automation tasks", "Python-script", "Log-fil"], "correct": 1, "explanation": "Playbook är YAML-fil som definierar tasks att köra."},
            {"question": "Vilket protokoll använder Ansible för Linux?", "options": ["HTTP", "SSH", "RDP", "Telnet"], "correct": 1, "explanation": "Ansible använder SSH för Linux/Unix. WinRM för Windows."},
            {"question": "Hur kör du en playbook?", "options": ["ansible run", "ansible-playbook playbook.yml", "ansible execute", "ansible start"], "correct": 1, "explanation": "ansible-playbook är kommandot för att köra playbooks."},
            {"question": "Vad är inventory?", "options": ["Playbook backup", "Lista över managed hosts", "Log directory", "Package list"], "correct": 1, "explanation": "Inventory definierar vilka hosts Ansible ska hantera."},
            {"question": "Hur installerar du paket på Debian?", "options": ["pkg: name=nginx", "apt: name=nginx state=present", "install: nginx", "package: nginx"], "correct": 1, "explanation": "apt module för Debian/Ubuntu, yum för RHEL/CentOS."},
            {"question": "Vad betyder state: present?", "options": ["Ta bort resurs", "Säkerställ att resurs finns", "Starta resurs", "Stoppa resurs"], "correct": 1, "explanation": "present = ska finnas. absent = ska inte finnas."},
            {"question": "Hur anger du sudo i playbook?", "options": ["sudo: yes", "become: yes", "root: yes", "admin: yes"], "correct": 1, "explanation": "become: yes eskalerar privileges (sudo)."},
            {"question": "Vad gör ping-modulen?", "options": ["Testar nätverk", "Testar SSH och Python på remote", "Ping ICMP", "Health check"], "correct": 1, "explanation": "ansible ping testar anslutning och Python, inte ICMP."},
            {"question": "Vad är handlers?", "options": ["Error handlers", "Tasks som körs vid notify", "Event handlers", "Exception handlers"], "correct": 1, "explanation": "Handlers triggas av notify och körs i slutet av play."},
            {"question": "Hur skriver du variabel i template?", "options": ["$variable", "%variable%", "{{ variable }}", "[variable]"], "correct": 2, "explanation": "Jinja2 syntax: {{ variabelnamn }}"},
            {"question": "Vad är idempotens?", "options": ["Snabb execution", "Samma resultat vid upprepade körningar", "Parallel execution", "Error recovery"], "correct": 1, "explanation": "Idempotent = köra flera gånger ger samma slutresultat."},
            {"question": "Hur gör du dry run?", "options": ["--dry", "--check", "--test", "--simulate"], "correct": 1, "explanation": "--check visar vad som skulle hända utan att ändra."},
            {"question": "Vad är template module?", "options": ["Skapar mallar", "Kopierar fil med variabelexpansion", "HTML templates", "Email templates"], "correct": 1, "explanation": "template kopierar .j2 fil och ersätter {{ variabler }}."},
            {"question": "Hur testar du anslutning?", "options": ["ansible hosts -m test", "ansible hosts -m ping", "ansible hosts --test", "ansible-test hosts"], "correct": 1, "explanation": "ansible group -m ping testar anslutning till hosts."},
            {"question": "Vad är ansible.cfg?", "options": ["Playbook", "Inventory", "Configuration file", "Credentials file"], "correct": 2, "explanation": "ansible.cfg innehåller Ansible-konfiguration."},
            {"question": "Hur kopierar du fil?", "options": ["file: src=a dest=b", "copy: src=a dest=b", "transfer: src=a dest=b", "move: src=a dest=b"], "correct": 1, "explanation": "copy module kopierar filer från control till managed node."},
            {"question": "Hur startar du tjänst?", "options": ["start: nginx", "service: name=nginx state=started", "run: nginx", "daemon: nginx start"], "correct": 1, "explanation": "service module hanterar systemtjänster."},
            {"question": "Vad är gather_facts?", "options": ["Samlar statistik", "Samlar systeminfo från hosts", "Samlar logs", "Samlar credentials"], "correct": 1, "explanation": "gather_facts samlar ansible_facts (OS, IP, etc)."},
            {"question": "Hur installerar du roles?", "options": ["ansible install", "ansible-galaxy install", "pip install", "apt install"], "correct": 1, "explanation": "ansible-galaxy hanterar roles från Galaxy."},
        ],
        "medium": [
            {"question": "Vad är en role?", "options": ["Användare", "Strukturerad samling av tasks/handlers/vars", "Permission", "Remote host"], "correct": 1, "explanation": "Role organiserar automation i återanvändbara komponenter."},
            {"question": "Hur itererar du över lista?", "options": ["for: items", "loop: [a, b, c]", "iterate: items", "each: items"], "correct": 1, "explanation": "loop ersätter with_items för iteration."},
            {"question": "Hur gör du villkorlig körning?", "options": ["if: condition", "when: condition", "condition: test", "check: condition"], "correct": 1, "explanation": "when: ansible_os_family == 'Debian'"},
            {"question": "Hur sparar du task-output?", "options": ["save: result", "register: result", "output: result", "store: result"], "correct": 1, "explanation": "register sparar output för senare användning."},
            {"question": "Vad är block/rescue/always?", "options": ["Loop struktur", "Error handling struktur", "Conditional struktur", "Import struktur"], "correct": 1, "explanation": "block grupperar tasks, rescue vid fel, always körs alltid."},
            {"question": "Hur krypterar du variabler?", "options": ["ansible encrypt", "ansible-vault encrypt", "ansible secure", "ansible-crypt"], "correct": 1, "explanation": "ansible-vault encrypt/decrypt hanterar krypterade filer."},
            {"question": "Vad är delegate_to?", "options": ["Delegera roll", "Kör task på annan host", "Delegera permission", "Delegera inventory"], "correct": 1, "explanation": "delegate_to: localhost kör task lokalt istället för remote."},
            {"question": "Hur gör du rolling update?", "options": ["rolling: true", "serial: 2", "batch: 2", "parallel: 2"], "correct": 1, "explanation": "serial anger antal hosts att uppdatera samtidigt."},
            {"question": "Vad är include vs import?", "options": ["Samma sak", "include = dynamisk, import = statisk", "import = dynamisk, include = statisk", "include för tasks, import för roles"], "correct": 1, "explanation": "include processar runtime, import vid parse time."},
            {"question": "Hur skapar du role-skelett?", "options": ["ansible role init", "ansible-galaxy init role_name", "ansible create role", "ansible-role new"], "correct": 1, "explanation": "ansible-galaxy init skapar role-katalogstruktur."},
            {"question": "Vad gör changed_when: false?", "options": ["Förhindrar körning", "Markerar aldrig som changed", "Ignorerar fel", "Tvingar ändring"], "correct": 1, "explanation": "changed_when överskriver changed-status."},
            {"question": "Hur väntar du på port?", "options": ["pause: port=80", "wait_for: port=80", "sleep: port=80", "hold: port=80"], "correct": 1, "explanation": "wait_for väntar tills port är tillgänglig."},
            {"question": "Vad är run_once?", "options": ["Kör en gång per host", "Kör bara en gång totalt", "Single thread", "No retry"], "correct": 1, "explanation": "run_once: true kör task endast på första host."},
            {"question": "Hur ignorerar du task-fel?", "options": ["skip_errors: yes", "ignore_errors: yes", "continue: yes", "no_fail: yes"], "correct": 1, "explanation": "ignore_errors låter playbook fortsätta vid fel."},
            {"question": "Vad är Jinja2 filter?", "options": ["Fil-filter", "Data transformation", "Log filter", "Network filter"], "correct": 1, "explanation": "Filters transformerar data: {{ list | join(',') }}"},
            {"question": "Vad är set_fact?", "options": ["Sätter inventory fact", "Skapar variabel runtime", "Definierar konstant", "Sätter global var"], "correct": 1, "explanation": "set_fact skapar eller ändrar variabel under körning."},
            {"question": "Hur testar du role?", "options": ["ansible-test", "molecule test", "pytest", "unittest"], "correct": 1, "explanation": "Molecule är test framework för Ansible roles."},
            {"question": "Vad är defaults/ i role?", "options": ["Fallback tasks", "Variabler med lägst prioritet", "Default handlers", "Default templates"], "correct": 1, "explanation": "defaults/main.yml har variabler som lätt överskrivs."},
            {"question": "Hur använder du lookup?", "options": ["lookup('file', path)", "read('file', path)", "get('file', path)", "load('file', path)"], "correct": 0, "explanation": "lookup plugin hämtar data: {{ lookup('file', '/path') }}"},
            {"question": "Vad är assert module?", "options": ["Test assertions", "Validerar villkor", "Security checks", "Type checking"], "correct": 1, "explanation": "assert validerar att conditions är sanna."},
        ],
        "hard": [
            {"question": "Vad är callback plugins?", "options": ["Event handlers", "Anpassar Ansible output/logging", "API callbacks", "Remote callbacks"], "correct": 1, "explanation": "Callbacks anpassar hur Ansible visar resultat."},
            {"question": "Hur skriver du custom module?", "options": ["YAML i modules/", "Python i library/", "Bash i scripts/", "JSON i plugins/"], "correct": 1, "explanation": "Custom modules är Python-scripts i library/."},
            {"question": "Vad är action plugins?", "options": ["Task actions", "Plugins som körs på control node", "Action handlers", "Pre-module plugins"], "correct": 1, "explanation": "Action plugins körs lokalt före remote module."},
            {"question": "Vad är dynamic inventory?", "options": ["Inventory från script/plugin", "Auto-updating inventory", "Load balanced inventory", "Cached inventory"], "correct": 0, "explanation": "Dynamic inventory hämtar hosts från externa källor."},
            {"question": "Vad är ansible-pull?", "options": ["Pull från remote", "Nodes hämtar config från git", "Pull inventory", "Pull modules"], "correct": 1, "explanation": "ansible-pull inverterar push-modellen."},
            {"question": "Vad gör async/poll?", "options": ["Async inventory", "Långkörande tasks utan timeout", "Async templates", "Poll status"], "correct": 1, "explanation": "async: 300 poll: 5 för tasks som tar lång tid."},
            {"question": "Vad är strategy: free?", "options": ["Free text", "Hosts väntar inte på varandra", "Free memory", "Free execution"], "correct": 1, "explanation": "free strategy låter hosts köra utan synkronisering."},
            {"question": "Vad är mitogen?", "options": ["Molecule plugin", "Snabbare Ansible execution", "Migration tool", "Git integration"], "correct": 1, "explanation": "Mitogen snabbar upp Ansible dramatiskt."},
            {"question": "Hur hanterar du Windows?", "options": ["SSH som Linux", "WinRM connection + win_* modules", "PowerShell remoting", "RDP automation"], "correct": 1, "explanation": "Windows kräver WinRM och win_-prefixade modules."},
            {"question": "Vad är Collections?", "options": ["Grupperade hosts", "Paketeringsformat för content", "Variable collections", "Task collections"], "correct": 1, "explanation": "Collections packeterar modules, plugins, roles."},
            {"question": "Vad är AWX?", "options": ["Ansible module", "Web UI för Ansible", "Ansible extension", "Cloud platform"], "correct": 1, "explanation": "AWX är open-source web UI (Tower community version)."},
            {"question": "Vad är facts caching?", "options": ["Cache playbooks", "Spara facts för snabbare körning", "Cache modules", "Cache inventory"], "correct": 1, "explanation": "Facts caching sparar ansible_facts mellan körningar."},
            {"question": "Hur gör du idempotence test?", "options": ["ansible --test", "Kör två gånger, kolla changed=0", "ansible-test idempotent", "molecule verify"], "correct": 1, "explanation": "Idempotence = andra körningen ska vara ok, inte changed."},
            {"question": "Vad är throttle?", "options": ["Speed limit", "Begränsar parallella task-körningar", "Memory limit", "Network throttle"], "correct": 1, "explanation": "throttle: 1 kör task på en host i taget."},
            {"question": "Vad är delegate_facts?", "options": ["Delegera factsinsamling", "Spara facts till delegerad host", "Facts delegation", "Remote facts"], "correct": 1, "explanation": "delegate_facts: true sparar facts till delegate_to host."},
            {"question": "Vad är synchronize module?", "options": ["Sync inventory", "rsync wrapper för stora filer", "Time sync", "Config sync"], "correct": 1, "explanation": "synchronize använder rsync, snabbare än copy för stora filer."},
            {"question": "Hur testar du Molecule scenario?", "options": ["molecule run", "molecule test", "molecule check", "molecule verify"], "correct": 1, "explanation": "molecule test kör full test-cycle."},
            {"question": "Vad är Ansible Navigator?", "options": ["File browser", "TUI ersättning för ansible-playbook", "Documentation viewer", "Role navigator"], "correct": 1, "explanation": "Navigator är modern TUI för att köra Ansible."},
            {"question": "Vad är network_cli connection?", "options": ["CLI wrapper", "Connection för nätverksutrustning", "Remote CLI", "Console connection"], "correct": 1, "explanation": "network_cli används för routers/switches."},
            {"question": "Hur installerar du collection?", "options": ["ansible install collection", "ansible-galaxy collection install", "pip install collection", "ansible get collection"], "correct": 1, "explanation": "ansible-galaxy collection install namespace.collection"},
        ],
    },

    "nodes": [
        {"id": 1, "title": "Ansible Introduktion", "slug": "ansible-intro"},
        {"id": 2, "title": "Installation & Setup", "slug": "installation-setup"},
        {"id": 3, "title": "Inventory Grunderna", "slug": "inventory-basics"},
        {"id": 4, "title": "Ad-hoc Commands", "slug": "ad-hoc-commands"},
        {"id": 5, "title": "Playbook Grunderna", "slug": "playbook-basics"},
        {"id": 6, "title": "Modules & Tasks", "slug": "modules-tasks"},
        {"id": 7, "title": "Variables", "slug": "variables"},
        {"id": 8, "title": "Templates (Jinja2)", "slug": "templates-jinja2"},
        {"id": 9, "title": "Handlers", "slug": "handlers"},
        {"id": 10, "title": "Conditionals & Loops", "slug": "conditionals-loops"},
        {"id": 11, "title": "Roles Grunderna", "slug": "roles-basics"},
        {"id": 12, "title": "Role Best Practices", "slug": "role-best-practices"},
        {"id": 13, "title": "Ansible Vault", "slug": "ansible-vault"},
        {"id": 14, "title": "Error Handling", "slug": "error-handling"},
        {"id": 15, "title": "Dynamic Inventory", "slug": "dynamic-inventory"},
        {"id": 16, "title": "Testing med Molecule", "slug": "testing-molecule"},
        {"id": 17, "title": "Optimization", "slug": "optimization"},
        {"id": 18, "title": "Collections", "slug": "collections"},
        {"id": 19, "title": "AWX/Tower", "slug": "awx-tower"},
        {"id": 20, "title": "Enterprise Patterns", "slug": "enterprise-patterns"},
    ],
}
