"""
AWS Fundamentals - Study Data
==============================

90 Flashcards (30 easy, 30 medium, 30 hard)
60 Quiz Questions (20 easy, 20 medium, 20 hard)
"""

AWS_STUDY_DATA = {
    "module_slug": "aws-fundamentals",
    "module_title": "AWS Fundamentals",
    "module_description": "Amazon Web Services - Molntjänster och Infrastructure",
    "icon": "Cloud",

    "flashcards": {
        "easy": [
            {"front": "Vad är AWS?", "back": "Amazon Web Services - världens största cloud provider. IaaS, PaaS, SaaS."},
            {"front": "Vad är EC2?", "back": "Elastic Compute Cloud - virtuella servrar. On-demand compute kapacitet."},
            {"front": "Vad är S3?", "back": "Simple Storage Service - object storage. Obegränsad skalbar lagring."},
            {"front": "Vad är en Region?", "back": "Geografiskt område med flera Availability Zones. us-east-1, eu-west-1."},
            {"front": "Vad är Availability Zone (AZ)?", "back": "Isolerat datacenter inom region. Redundans och hög tillgänglighet."},
            {"front": "Vad är IAM?", "back": "Identity and Access Management - hantera users, groups, roles, policies."},
            {"front": "Vad är VPC?", "back": "Virtual Private Cloud - isolerat nätverk i AWS. Subnets, routing."},
            {"front": "Vad är RDS?", "back": "Relational Database Service - managed databaser. MySQL, PostgreSQL, etc."},
            {"front": "Vad är Lambda?", "back": "Serverless compute. Kör kod utan att hantera servrar. Pay per execution."},
            {"front": "Vad är CloudWatch?", "back": "Monitoring och logging. Metrics, alarms, dashboards."},
            {"front": "Vad är en S3 bucket?", "back": "Container för objekt i S3. Globalt unikt namn."},
            {"front": "Vad är EC2 instance type?", "back": "Specifikation för CPU, RAM, nätverk. t2.micro, m5.large, etc."},
            {"front": "Vad är Security Group?", "back": "Virtual firewall för EC2. Kontrollerar inbound/outbound trafik."},
            {"front": "Vad är AMI?", "back": "Amazon Machine Image - template för EC2. OS + software konfiguration."},
            {"front": "Vad är EBS?", "back": "Elastic Block Store - persistent block storage för EC2."},
            {"front": "Vad är Route 53?", "back": "DNS service. Domain registration och routing."},
            {"front": "Vad är CloudFront?", "back": "CDN - Content Delivery Network. Caching vid edge locations."},
            {"front": "Vad är SNS?", "back": "Simple Notification Service - pub/sub messaging. Push notifications."},
            {"front": "Vad är SQS?", "back": "Simple Queue Service - message queuing. Decouple components."},
            {"front": "Vad är Elastic IP?", "back": "Statisk public IP-adress. Kan flyttas mellan instanser."},
            {"front": "Vad är AWS CLI?", "back": "Command Line Interface för AWS. Hantera resurser via terminal."},
            {"front": "Vad är Free Tier?", "back": "Gratis nivå för nya konton. 12 månader eller alltid gratis tjänster."},
            {"front": "Vad är on-demand pricing?", "back": "Betala per timme/sekund användning. Ingen förskottsbetalning."},
            {"front": "Vad är Reserved Instances?", "back": "1-3 års åtagande för rabatt. Upp till 75% billigare."},
            {"front": "Vad är Spot Instances?", "back": "Oanvänd kapacitet till rabatt. Kan avbrytas av AWS."},
            {"front": "Vad är key pair?", "back": "SSH-nyckelpar för EC2 access. Private key hos dig."},
            {"front": "Vad är tagging?", "back": "Metadata på resurser. Organisering, kostnadsfördelning."},
            {"front": "Vad är AWS Console?", "back": "Web-baserat GUI för AWS. Hantera alla tjänster."},
            {"front": "Vad är shared responsibility model?", "back": "AWS ansvarar för cloud-infra. Du ansvarar för det i cloud."},
            {"front": "Vad är root account?", "back": "Huvud AWS-konto. Full access - skydda med MFA!"},
        ],
        "medium": [
            {"front": "Vad är Auto Scaling?", "back": "Automatisk skalning av EC2. Öka/minska baserat på metrics."},
            {"front": "Vad är Load Balancer?", "back": "Distribuerar trafik över instanser. ALB, NLB, CLB."},
            {"front": "Vad är ALB?", "back": "Application Load Balancer - Layer 7. HTTP/HTTPS routing."},
            {"front": "Vad är NLB?", "back": "Network Load Balancer - Layer 4. Ultra-low latency."},
            {"front": "Vad är Launch Template?", "back": "Template för EC2 instanser. AMI, type, security group, etc."},
            {"front": "Vad är ECS?", "back": "Elastic Container Service - kör Docker containers. Managed."},
            {"front": "Vad är EKS?", "back": "Elastic Kubernetes Service - managed Kubernetes."},
            {"front": "Vad är Fargate?", "back": "Serverless compute för containers. Ingen server-hantering."},
            {"front": "Vad är subnet?", "back": "Segment av VPC CIDR. Public eller private."},
            {"front": "Vad är Internet Gateway?", "back": "Tillåter VPC kommunicera med internet. En per VPC."},
            {"front": "Vad är NAT Gateway?", "back": "Tillåter private subnets nå internet. Outbound only."},
            {"front": "Vad är NACL?", "back": "Network ACL - stateless firewall på subnet-nivå."},
            {"front": "Skillnad Security Group vs NACL?", "back": "SG är stateful (instance), NACL är stateless (subnet)."},
            {"front": "Vad är IAM Policy?", "back": "JSON-dokument som definierar permissions. Allow/Deny actions."},
            {"front": "Vad är IAM Role?", "back": "Identity för AWS services. EC2 kan anta roll för S3 access."},
            {"front": "Vad är DynamoDB?", "back": "NoSQL database - managed. Key-value och document store."},
            {"front": "Vad är ElastiCache?", "back": "Managed in-memory cache. Redis eller Memcached."},
            {"front": "Vad är CloudFormation?", "back": "Infrastructure as Code. YAML/JSON templates."},
            {"front": "Vad är Terraform vs CloudFormation?", "back": "Terraform är cloud-agnostic. CF är AWS-native."},
            {"front": "Vad är Secrets Manager?", "back": "Hantera hemligheter. Rotation, audit. API keys, DB passwords."},
            {"front": "Vad är Systems Manager?", "back": "Hantera EC2 fleet. Session Manager, Parameter Store."},
            {"front": "Vad är Parameter Store?", "back": "Centraliserad config. Hierarkisk struktur. Gratis alternativ."},
            {"front": "Vad är KMS?", "back": "Key Management Service - hantera encryption keys."},
            {"front": "Vad är CloudTrail?", "back": "Audit logging för AWS API calls. Vem gjorde vad, när."},
            {"front": "Vad är VPC Peering?", "back": "Direkt anslutning mellan två VPCs. Privat kommunikation."},
            {"front": "Vad är Transit Gateway?", "back": "Hub för VPC-anslutningar. Skalbar nätverksarkitektur."},
            {"front": "Vad är AWS Organizations?", "back": "Hantera flera AWS-konton. Consolidated billing, SCPs."},
            {"front": "Vad är S3 storage classes?", "back": "Standard, IA, Glacier. Olika kostnad/tillgänglighet."},
            {"front": "Vad är lifecycle policy?", "back": "Automatisk transition mellan storage classes. Kostnadsoptimering."},
            {"front": "Vad är versioning i S3?", "back": "Behåll alla versioner av objekt. Skydd mot oavsiktlig radering."},
        ],
        "hard": [
            {"front": "Vad är AWS Well-Architected Framework?", "back": "Best practices: Operational Excellence, Security, Reliability, Performance, Cost Optimization, Sustainability."},
            {"front": "Vad är multi-AZ deployment?", "back": "Deploy i flera Availability Zones. High availability och failover."},
            {"front": "Vad är cross-region replication?", "back": "Replikera data mellan regioner. DR och compliance."},
            {"front": "Vad är AWS Global Accelerator?", "back": "Anycast IP för global routing. Förbättrad performance."},
            {"front": "Vad är API Gateway?", "back": "Managed REST/WebSocket APIs. Rate limiting, auth, staging."},
            {"front": "Vad är Step Functions?", "back": "Serverless workflow orchestration. State machine."},
            {"front": "Vad är EventBridge?", "back": "Serverless event bus. Event routing och filtering."},
            {"front": "Vad är Kinesis?", "back": "Real-time data streaming. Kinesis Data Streams, Firehose."},
            {"front": "Vad är SageMaker?", "back": "ML platform. Build, train, deploy machine learning models."},
            {"front": "Vad är Athena?", "back": "Serverless query service. SQL mot S3 data."},
            {"front": "Vad är Redshift?", "back": "Data warehouse. Petabyte-scale analytics."},
            {"front": "Vad är Glue?", "back": "Serverless ETL. Data catalog och transformation."},
            {"front": "Vad är PrivateLink?", "back": "Privat anslutning till AWS services. Ingen internet exposure."},
            {"front": "Vad är Service Mesh?", "back": "App Mesh för microservices. Traffic management, observability."},
            {"front": "Vad är Cognito?", "back": "User authentication. User pools och identity pools."},
            {"front": "Vad är WAF?", "back": "Web Application Firewall. Skydd mot SQL injection, XSS."},
            {"front": "Vad är Shield?", "back": "DDoS protection. Standard (gratis) och Advanced."},
            {"front": "Vad är GuardDuty?", "back": "Threat detection. ML-baserad säkerhetsövervakning."},
            {"front": "Vad är Inspector?", "back": "Vulnerability scanning för EC2 och containers."},
            {"front": "Vad är Config?", "back": "Resource configuration audit. Compliance tracking."},
            {"front": "Vad är Control Tower?", "back": "Multi-account setup. Landing zone med guardrails."},
            {"front": "Vad är Service Control Policy?", "back": "Organization-wide permissions. Begränsa vad konton kan göra."},
            {"front": "Vad är Cost Explorer?", "back": "Analysera AWS-kostnader. Forecasting och rekommendationer."},
            {"front": "Vad är Trusted Advisor?", "back": "Best practice recommendations. Cost, security, performance."},
            {"front": "Vad är X-Ray?", "back": "Distributed tracing. Debug och analysera microservices."},
            {"front": "Vad är Container Insights?", "back": "Monitoring för ECS/EKS. Container metrics och logs."},
            {"front": "Vad är Outposts?", "back": "AWS infrastructure on-premises. Hybrid cloud."},
            {"front": "Vad är Wavelength?", "back": "Edge computing vid telecom. Ultra-low latency."},
            {"front": "Vad är CDK?", "back": "Cloud Development Kit. IaC med TypeScript, Python, Java."},
            {"front": "Vad är SAM?", "back": "Serverless Application Model. Template för Lambda apps."},
        ],
    },

    "quiz": {
        "easy": [
            {"question": "Vad är EC2?", "options": ["Database service", "Virtual servers", "Storage service", "DNS service"], "correct": 1, "explanation": "EC2 = Elastic Compute Cloud - virtuella servrar i AWS."},
            {"question": "Vad är S3?", "options": ["Server service", "Object storage", "Compute service", "Database"], "correct": 1, "explanation": "S3 = Simple Storage Service - skalbar object storage."},
            {"question": "Vad är en AWS Region?", "options": ["Single datacenter", "Geografiskt område med flera AZs", "Virtuellt nätverk", "Security zone"], "correct": 1, "explanation": "Region är geografiskt område med minst 3 Availability Zones."},
            {"question": "Vad är IAM?", "options": ["Infrastructure Management", "Identity and Access Management", "Instance Management", "Internet Access Module"], "correct": 1, "explanation": "IAM hanterar users, groups, roles och permissions."},
            {"question": "Vad är VPC?", "options": ["Virtual PC", "Virtual Private Cloud", "Virtual Public Cloud", "Virtual Processing Center"], "correct": 1, "explanation": "VPC = Virtual Private Cloud - isolerat nätverk i AWS."},
            {"question": "Vad är Security Group?", "options": ["User group", "Virtual firewall för EC2", "IAM group", "Network group"], "correct": 1, "explanation": "Security Groups är virtuella firewalls för EC2 instanser."},
            {"question": "Vad är Lambda?", "options": ["Database", "Serverless compute", "Load balancer", "Storage"], "correct": 1, "explanation": "Lambda kör kod utan att hantera servrar."},
            {"question": "Vad är RDS?", "options": ["Managed databases", "DNS service", "Routing service", "Cache service"], "correct": 0, "explanation": "RDS = Relational Database Service - managed SQL databaser."},
            {"question": "Vad är CloudWatch?", "options": ["CDN", "Monitoring och logging", "Security service", "Storage"], "correct": 1, "explanation": "CloudWatch är AWS monitoring och logging service."},
            {"question": "Vad är AMI?", "options": ["Amazon Monitoring Interface", "Amazon Machine Image", "AWS Management Instance", "Amazon Module Instance"], "correct": 1, "explanation": "AMI är template för att starta EC2 instanser."},
            {"question": "Vad är EBS?", "options": ["Elastic Block Store", "Elastic Backup Service", "Extended Block Storage", "Enterprise Backup Solution"], "correct": 0, "explanation": "EBS är persistent block storage för EC2."},
            {"question": "Vad är Route 53?", "options": ["Routing service", "DNS service", "VPN service", "Load balancer"], "correct": 1, "explanation": "Route 53 är AWS DNS och domain registration service."},
            {"question": "Vad är CloudFront?", "options": ["CDN", "Firewall", "Load balancer", "DNS"], "correct": 0, "explanation": "CloudFront är AWS Content Delivery Network."},
            {"question": "Vad är shared responsibility model?", "options": ["Delad kostnad", "AWS ansvarar för cloud, du för det i cloud", "Gemensam support", "Delad data"], "correct": 1, "explanation": "AWS hanterar infra-säkerhet, du hanterar din data/config."},
            {"question": "Vad är on-demand pricing?", "options": ["Förskottsbetalning", "Betala per användning", "Månadsabonnemang", "Årlig kostnad"], "correct": 1, "explanation": "On-demand = betala för vad du använder, ingen förskott."},
            {"question": "Vad är Spot Instances?", "options": ["Premium instances", "Rabatterad oanvänd kapacitet", "Reserved instances", "Free tier"], "correct": 1, "explanation": "Spot instances är billigare men kan avbrytas."},
            {"question": "Vad är key pair?", "options": ["API keys", "SSH-nyckelpar för EC2", "IAM credentials", "KMS keys"], "correct": 1, "explanation": "Key pair används för SSH access till EC2."},
            {"question": "Vad är Availability Zone?", "options": ["Region", "Isolerat datacenter", "Security zone", "Network zone"], "correct": 1, "explanation": "AZ är isolerat datacenter inom en region."},
            {"question": "Vad är AWS CLI?", "options": ["Web console", "Command Line Interface", "API client", "Mobile app"], "correct": 1, "explanation": "AWS CLI låter dig hantera AWS via terminal."},
            {"question": "Vad är S3 bucket?", "options": ["EC2 container", "Container för S3 objekt", "Database", "Lambda function"], "correct": 1, "explanation": "S3 bucket är container där objekt lagras."},
        ],
        "medium": [
            {"question": "Vad är Auto Scaling?", "options": ["Manual skalning", "Automatisk skalning baserat på demand", "Database scaling", "Network scaling"], "correct": 1, "explanation": "Auto Scaling ökar/minskar EC2 baserat på metrics."},
            {"question": "Vad är skillnaden mellan ALB och NLB?", "options": ["Samma sak", "ALB är Layer 7, NLB är Layer 4", "NLB är dyrare", "ALB är snabbare"], "correct": 1, "explanation": "ALB hanterar HTTP/HTTPS (L7), NLB hanterar TCP/UDP (L4)."},
            {"question": "Vad är ECS?", "options": ["EC2 service", "Container orchestration service", "Email service", "Cache service"], "correct": 1, "explanation": "ECS = Elastic Container Service - kör Docker containers."},
            {"question": "Vad är EKS?", "options": ["EC2 Kubernetes", "Managed Kubernetes service", "Email service", "EC2 Key Service"], "correct": 1, "explanation": "EKS = Elastic Kubernetes Service."},
            {"question": "Vad är Fargate?", "options": ["EC2 type", "Serverless containers", "Database", "Storage"], "correct": 1, "explanation": "Fargate kör containers utan att hantera servrar."},
            {"question": "Vad är NAT Gateway?", "options": ["Internet access", "Tillåter private subnets nå internet", "Firewall", "Load balancer"], "correct": 1, "explanation": "NAT Gateway låter private subnets kommunicera utåt."},
            {"question": "Skillnad Security Group vs NACL?", "options": ["Samma sak", "SG är stateful, NACL är stateless", "NACL är dyrare", "SG är för VPC"], "correct": 1, "explanation": "SG = stateful (instance), NACL = stateless (subnet)."},
            {"question": "Vad är IAM Role?", "options": ["User account", "Identity för services/EC2", "Admin role", "Permission set"], "correct": 1, "explanation": "Roles ger AWS services permissions att agera."},
            {"question": "Vad är DynamoDB?", "options": ["Relational DB", "NoSQL database", "Graph DB", "Cache"], "correct": 1, "explanation": "DynamoDB är managed NoSQL database."},
            {"question": "Vad är CloudFormation?", "options": ["Cloud forms", "Infrastructure as Code", "Deployment tool", "Monitoring"], "correct": 1, "explanation": "CloudFormation definierar infra i YAML/JSON templates."},
            {"question": "Vad är Secrets Manager?", "options": ["IAM service", "Hantera secrets med rotation", "Key management", "Password manager"], "correct": 1, "explanation": "Secrets Manager hanterar API keys, DB passwords med rotation."},
            {"question": "Vad är CloudTrail?", "options": ["Monitoring", "Audit logging av API calls", "Log aggregation", "Trail management"], "correct": 1, "explanation": "CloudTrail loggar alla AWS API calls för audit."},
            {"question": "Vad är VPC Peering?", "options": ["VPC backup", "Direkt anslutning mellan VPCs", "VPC sharing", "VPC copy"], "correct": 1, "explanation": "VPC Peering kopplar samman två VPCs privat."},
            {"question": "Vad är AWS Organizations?", "options": ["User groups", "Multi-account management", "Organization chart", "Team management"], "correct": 1, "explanation": "Organizations hanterar flera AWS-konton centralt."},
            {"question": "Vad är S3 storage classes?", "options": ["Bucket types", "Olika lagringskostnader/tillgänglighet", "File types", "Access levels"], "correct": 1, "explanation": "Standard, IA, Glacier - olika pris och access-tid."},
            {"question": "Vad är S3 versioning?", "options": ["API versions", "Behålla alla versioner av objekt", "Bucket versions", "File history"], "correct": 1, "explanation": "Versioning sparar alla versioner, skyddar mot radering."},
            {"question": "Vad är lifecycle policy?", "options": ["Account lifecycle", "Automatisk transition mellan storage classes", "EC2 lifecycle", "Data lifecycle"], "correct": 1, "explanation": "Lifecycle policies flyttar data automatiskt till billigare storage."},
            {"question": "Vad är KMS?", "options": ["Key Management Service", "Kubernetes Management", "Knowledge Management", "Kernel Management"], "correct": 0, "explanation": "KMS hanterar encryption keys för AWS services."},
            {"question": "Vad är ElastiCache?", "options": ["S3 cache", "Managed Redis/Memcached", "CloudFront", "Database cache"], "correct": 1, "explanation": "ElastiCache är managed in-memory cache."},
            {"question": "Vad är Transit Gateway?", "options": ["VPN gateway", "Hub för VPC-anslutningar", "Internet gateway", "NAT gateway"], "correct": 1, "explanation": "Transit Gateway kopplar samman många VPCs som hub."},
        ],
        "hard": [
            {"question": "Vilka är Well-Architected pillars?", "options": ["Security, Cost, Speed", "Op Ex, Security, Reliability, Perf, Cost, Sustainability", "Design, Deploy, Monitor", "Plan, Build, Run"], "correct": 1, "explanation": "6 pillars: Operational Excellence, Security, Reliability, Performance, Cost, Sustainability."},
            {"question": "Vad är API Gateway?", "options": ["VPC gateway", "Managed REST/WebSocket API service", "Load balancer", "DNS service"], "correct": 1, "explanation": "API Gateway är fully managed API service med auth, throttling."},
            {"question": "Vad är Step Functions?", "options": ["Lambda functions", "Serverless workflow orchestration", "Step debugging", "Function chaining"], "correct": 1, "explanation": "Step Functions orchestrerar serverless workflows."},
            {"question": "Vad är EventBridge?", "options": ["Network bridge", "Serverless event bus", "VPC peering", "Log bridge"], "correct": 1, "explanation": "EventBridge är serverless event routing service."},
            {"question": "Vad är Kinesis?", "options": ["Database", "Real-time data streaming", "Cache", "Queue"], "correct": 1, "explanation": "Kinesis hanterar real-time data streams."},
            {"question": "Vad är Athena?", "options": ["Database", "Serverless S3 SQL queries", "ML service", "Analytics"], "correct": 1, "explanation": "Athena kör SQL queries direkt mot S3 data."},
            {"question": "Vad är Redshift?", "options": ["Cache", "Data warehouse", "Database", "Analytics tool"], "correct": 1, "explanation": "Redshift är petabyte-scale data warehouse."},
            {"question": "Vad är PrivateLink?", "options": ["Private VPN", "Privat åtkomst till AWS services", "Private DNS", "Private subnet"], "correct": 1, "explanation": "PrivateLink ger privat access utan internet exposure."},
            {"question": "Vad är Cognito?", "options": ["ML service", "User authentication service", "Database", "Cache"], "correct": 1, "explanation": "Cognito hanterar user sign-up, sign-in, access."},
            {"question": "Vad är WAF?", "options": ["Firewall", "Web Application Firewall", "Network firewall", "DDoS protection"], "correct": 1, "explanation": "WAF skyddar mot SQL injection, XSS, etc."},
            {"question": "Vad är GuardDuty?", "options": ["Firewall", "ML-baserad threat detection", "Antivirus", "DDoS protection"], "correct": 1, "explanation": "GuardDuty upptäcker hot med machine learning."},
            {"question": "Vad är Inspector?", "options": ["Code review", "Vulnerability scanning", "Log analysis", "Security audit"], "correct": 1, "explanation": "Inspector skannar EC2 och containers för sårbarheter."},
            {"question": "Vad är Control Tower?", "options": ["EC2 management", "Multi-account landing zone", "Network control", "Access control"], "correct": 1, "explanation": "Control Tower sätter upp multi-account med guardrails."},
            {"question": "Vad är Service Control Policy?", "options": ["IAM policy", "Organization-wide begränsningar", "Service policy", "Access policy"], "correct": 1, "explanation": "SCPs begränsar vad konton i Organization kan göra."},
            {"question": "Vad är X-Ray?", "options": ["Security scan", "Distributed tracing", "Performance test", "Log analysis"], "correct": 1, "explanation": "X-Ray är distributed tracing för microservices."},
            {"question": "Vad är CDK?", "options": ["Cloud Deployment Kit", "Cloud Development Kit - IaC med kod", "Container Dev Kit", "Cloud Design Kit"], "correct": 1, "explanation": "CDK låter dig skriva IaC i TypeScript, Python, etc."},
            {"question": "Vad är SAM?", "options": ["Server Application Model", "Serverless Application Model", "Simple App Manager", "Service App Model"], "correct": 1, "explanation": "SAM är framework för serverless applications."},
            {"question": "Vad är Outposts?", "options": ["Remote region", "AWS infrastructure on-premises", "Edge location", "External VPC"], "correct": 1, "explanation": "Outposts kör AWS infra i ditt datacenter."},
            {"question": "Vad är Cost Explorer?", "options": ["Billing dashboard", "Analysera och forecast AWS-kostnader", "Cost calculator", "Budget tool"], "correct": 1, "explanation": "Cost Explorer ger detaljerad kostnadsanalys."},
            {"question": "Vad är Trusted Advisor?", "options": ["Support service", "Best practice recommendations", "Security advisor", "Cost advisor"], "correct": 1, "explanation": "Trusted Advisor ger rekommendationer för cost, security, performance."},
        ],
    },

    "nodes": [
        {"id": 1, "title": "AWS Introduktion", "slug": "aws-intro"},
        {"id": 2, "title": "Regioner & AZs", "slug": "regions-azs"},
        {"id": 3, "title": "IAM Grunderna", "slug": "iam-basics"},
        {"id": 4, "title": "EC2 Basics", "slug": "ec2-basics"},
        {"id": 5, "title": "EC2 Instance Types", "slug": "ec2-instance-types"},
        {"id": 6, "title": "Security Groups", "slug": "security-groups"},
        {"id": 7, "title": "S3 Storage", "slug": "s3-storage"},
        {"id": 8, "title": "VPC Networking", "slug": "vpc-networking"},
        {"id": 9, "title": "Subnets & Routing", "slug": "subnets-routing"},
        {"id": 10, "title": "Load Balancing", "slug": "load-balancing"},
        {"id": 11, "title": "Auto Scaling", "slug": "auto-scaling"},
        {"id": 12, "title": "RDS Databases", "slug": "rds-databases"},
        {"id": 13, "title": "Lambda Serverless", "slug": "lambda-serverless"},
        {"id": 14, "title": "ECS/EKS Containers", "slug": "ecs-eks-containers"},
        {"id": 15, "title": "CloudWatch Monitoring", "slug": "cloudwatch-monitoring"},
        {"id": 16, "title": "CloudFormation IaC", "slug": "cloudformation-iac"},
        {"id": 17, "title": "Security Services", "slug": "security-services"},
        {"id": 18, "title": "Cost Management", "slug": "cost-management"},
        {"id": 19, "title": "Well-Architected", "slug": "well-architected"},
        {"id": 20, "title": "AWS Enterprise", "slug": "aws-enterprise"},
    ],
}
