"""
Bash Mastery - Study Data
=========================

90 Flashcards (30 easy, 30 medium, 30 hard)
60 Quiz Questions (20 easy, 20 medium, 20 hard)
"""

BASH_STUDY_DATA = {
    "module_slug": "bash-mastery",
    "module_title": "Bash Mastery",
    "module_description": "Automatisering med Bash-skript",
    "icon": "Terminal",

    "flashcards": {
        "easy": [
            {"front": "Vad är Bash?", "back": "Bourne Again SHell - standardshell i de flesta Linux/macOS. Tolkar kommandon och kör scripts."},
            {"front": "Hur startar du ett Bash-script?", "back": "Första raden: #!/bin/bash (shebang). Gör körbar: chmod +x script.sh. Kör: ./script.sh"},
            {"front": "Hur skapar du en variabel?", "back": "namn=värde (utan mellanslag!). Läs med $namn eller ${namn}."},
            {"front": "Hur skriver du ut text?", "back": "echo 'text' - skriver text till stdout. printf för formaterad output."},
            {"front": "Hur läser du input från användare?", "back": "read variabel - väntar på input och sparar i variabeln."},
            {"front": "Hur skriver du en kommentar?", "back": "# Detta är en kommentar - allt efter # ignoreras."},
            {"front": "Hur kör du kommando och sparar output?", "back": "result=$(kommando) eller result=`kommando` (äldre syntax)."},
            {"front": "Vad gör $?", "back": "Exit status från senaste kommando. 0 = success, annat = fel."},
            {"front": "Hur konkatenerar du strängar?", "back": "str=\"$str1$str2\" eller str=\"${str1}text${str2}\""},
            {"front": "Vad är $0, $1, $2?", "back": "Positionella parametrar. $0 = scriptnamn, $1 = första arg, $2 = andra, etc."},
            {"front": "Vad gör $#?", "back": "Antal argument som skickats till scriptet."},
            {"front": "Vad gör $@?", "back": "Alla argument som separata strängar. \"$@\" bevarar quoting."},
            {"front": "Hur gör du en if-sats?", "back": "if [ villkor ]; then kommandon; fi - eller med [[ ]] för utökad syntax."},
            {"front": "Hur jämför du strängar?", "back": "[ \"$a\" = \"$b\" ] för lika, [ \"$a\" != \"$b\" ] för olika."},
            {"front": "Hur jämför du tal?", "back": "-eq (lika), -ne (olika), -lt (mindre), -gt (större), -le, -ge."},
            {"front": "Hur gör du en for-loop?", "back": "for i in 1 2 3; do echo $i; done - eller for ((i=0; i<10; i++))"},
            {"front": "Hur gör du en while-loop?", "back": "while [ villkor ]; do kommandon; done - körs medan villkor är sant."},
            {"front": "Hur avslutar du script med status?", "back": "exit 0 för success, exit 1 (eller annat) för fel."},
            {"front": "Vad gör && och ||?", "back": "&& kör nästa om förra lyckades. || kör nästa om förra misslyckades."},
            {"front": "Hur kontrollerar du om fil finns?", "back": "[ -f fil ] - returnerar true om fil finns och är vanlig fil."},
            {"front": "Hur kontrollerar du om katalog finns?", "back": "[ -d katalog ] - returnerar true om katalog finns."},
            {"front": "Hur gör du else-if?", "back": "if villkor; then ...; elif villkor2; then ...; else ...; fi"},
            {"front": "Hur loopar du över filer?", "back": "for file in *.txt; do echo $file; done"},
            {"front": "Hur definierar du en funktion?", "back": "function namn() { kommandon; } eller namn() { kommandon; }"},
            {"front": "Hur anropar du funktion med argument?", "back": "funktionsnamn arg1 arg2 - inuti funktionen: $1, $2, etc."},
            {"front": "Vad gör source eller .?", "back": "Kör script i nuvarande shell så variabler/funktioner blir tillgängliga."},
            {"front": "Hur lägger du till till en fil?", "back": "echo 'text' >> fil - append. > skriver över."},
            {"front": "Hur läser du fil rad för rad?", "back": "while read line; do echo $line; done < fil"},
            {"front": "Vad är PATH-variabeln?", "back": "Lista kataloger där shell letar efter kommandon. Separerade med :"},
            {"front": "Hur exporterar du variabel?", "back": "export VARIABEL=värde - gör tillgänglig för child-processer."},
        ],
        "medium": [
            {"front": "Skillnad mellan [ ] och [[ ]]?", "back": "[[ ]] är Bash-specifik med fler features: regex (=~), && och || inuti, ingen word splitting."},
            {"front": "Hur gör du regex-matching?", "back": "[[ $str =~ ^[0-9]+$ ]] - true om str bara innehåller siffror."},
            {"front": "Vad gör ${var:-default}?", "back": "Parameter expansion: returnerar default om var är tom eller ej satt."},
            {"front": "Vad gör ${var:=default}?", "back": "Sätter var till default om tom/ej satt, returnerar värdet."},
            {"front": "Vad gör ${#var}?", "back": "Returnerar längden på strängen var."},
            {"front": "Vad gör ${var%pattern}?", "back": "Tar bort kortaste match av pattern från slutet. ${fil%.txt} tar bort .txt"},
            {"front": "Vad gör ${var%%pattern}?", "back": "Tar bort längsta match av pattern från slutet."},
            {"front": "Vad gör ${var#pattern}?", "back": "Tar bort kortaste match från början. ${path#*/} tar bort första /-delen."},
            {"front": "Vad gör ${var//old/new}?", "back": "Ersätter alla förekomster av old med new i var."},
            {"front": "Hur skapar du array?", "back": "arr=(a b c) - index 0,1,2. Läs: ${arr[0]}, alla: ${arr[@]}"},
            {"front": "Hur får du array-längd?", "back": "${#arr[@]} - returnerar antal element i arrayen."},
            {"front": "Hur loopar du över array?", "back": "for item in \"${arr[@]}\"; do echo $item; done"},
            {"front": "Vad är associative array?", "back": "declare -A map; map[key]=value - hash/dictionary i Bash 4+."},
            {"front": "Hur gör du case-statement?", "back": "case $var in pattern1) cmd;; pattern2) cmd;; *) default;; esac"},
            {"front": "Vad gör set -e?", "back": "Avbryter script vid första fel (non-zero exit). Bra för robusta scripts."},
            {"front": "Vad gör set -u?", "back": "Behandlar odefinierade variabler som fel. Förhindrar typos."},
            {"front": "Vad gör set -o pipefail?", "back": "Pipeline returnerar fel om något kommando i pipe misslyckas."},
            {"front": "Hur fångar du signaler?", "back": "trap 'cleanup' EXIT INT TERM - kör cleanup vid exit/interrupt."},
            {"front": "Vad gör eval?", "back": "Kör sträng som kommando. eval \"$cmd\" - farligt med osäker input!"},
            {"front": "Hur gör du arithmetic?", "back": "$((1+2)) eller let 'sum=1+2' eller expr 1 + 2"},
            {"front": "Vad gör shift?", "back": "Flyttar positionella parametrar. $2 blir $1, $3 blir $2, etc."},
            {"front": "Hur processar du options?", "back": "getopts \"ab:c\" opt - hanterar -a, -b värde, -c. : kräver argument."},
            {"front": "Vad gör local i funktion?", "back": "local var=värde - variabeln finns bara i funktionen."},
            {"front": "Hur returnerar funktion värde?", "back": "return N för exit status (0-255). Eller echo och fånga med $()."},
            {"front": "Vad är subshell?", "back": "(kommandon) körs i child process. Variabler påverkar inte parent."},
            {"front": "Hur kör du parallellt?", "back": "cmd1 & cmd2 & wait - & kör i bakgrund, wait väntar på alla."},
            {"front": "Vad gör $RANDOM?", "back": "Returnerar slumpmässigt tal 0-32767. RANDOM % 100 för 0-99."},
            {"front": "Hur läser du JSON med jq?", "back": "echo '$json' | jq '.key' - extraherar värden från JSON."},
            {"front": "Vad är heredoc?", "back": "cat <<EOF ... EOF - multiline input. <<- för indenterad."},
            {"front": "Hur debuggar du script?", "back": "bash -x script.sh eller set -x i scriptet visar varje kommando."},
        ],
        "hard": [
            {"front": "Hur gör du named pipe (FIFO)?", "back": "mkfifo pipe; cmd1 > pipe & cmd2 < pipe - inter-process kommunikation."},
            {"front": "Vad gör coproc?", "back": "coproc NAME { cmd; } - kör i bakgrund med input/output file descriptors."},
            {"front": "Hur redirectar du fd 3?", "back": "exec 3> fil - öppnar fd 3 för write. echo text >&3 skriver dit."},
            {"front": "Hur duplicerar du file descriptors?", "back": "exec 3>&1 - fd 3 blir kopia av stdout. Användbart för att spara/återställa."},
            {"front": "Vad gör process substitution?", "back": "diff <(cmd1) <(cmd2) - behandlar command output som filer."},
            {"front": "Hur hanterar du concurrent writes?", "back": "flock -x lockfile -c 'cmd' - exclusive lock förhindrar race conditions."},
            {"front": "Hur gör du timeout på kommando?", "back": "timeout 5s cmd - avbryter efter 5 sekunder. timeout --signal=KILL 5s cmd"},
            {"front": "Vad är Bash completion?", "back": "complete -F _func cmd - definierar tab-completion för kommandon."},
            {"front": "Hur läser du binär data?", "back": "xxd, od, hexdump. read -n 4 läser 4 bytes. IFS= read -r -d '' för null-term."},
            {"front": "Vad gör BASH_REMATCH?", "back": "Array med regex capture groups efter [[ $str =~ regex ]]. ${BASH_REMATCH[1]}"},
            {"front": "Hur gör du recursive function?", "back": "func() { [ base ] && return; func ...; } - kolla base case först!"},
            {"front": "Vad är Bash strict mode?", "back": "set -euo pipefail; IFS=$'\\n\\t' - kombination för robusta scripts."},
            {"front": "Hur testar du script?", "back": "bats (Bash Automated Testing System) eller shunit2 för unit tests."},
            {"front": "Vad gör mapfile/readarray?", "back": "mapfile -t arr < fil - läser fil till array, en rad per element."},
            {"front": "Hur hanterar du special chars i filnamn?", "back": "find -print0 | xargs -0 - null-separerade för spaces/newlines."},
            {"front": "Vad är indirect reference?", "back": "${!varname} - expanderar värdet av variabeln vars namn är i varname."},
            {"front": "Hur gör du atomic file write?", "back": "Skriv till tempfil, sedan mv. mv är atomic på samma filsystem."},
            {"front": "Vad gör PROMPT_COMMAND?", "back": "Körs före varje prompt. Användbart för dynamisk PS1, logging, etc."},
            {"front": "Hur trackar du execution time?", "back": "SECONDS variabel - sätts till 0 vid scriptstart, ökar varje sekund."},
            {"front": "Vad är nameref?", "back": "declare -n ref=var - ref blir reference till var. Ändra ref ändrar var."},
            {"front": "Hur skickar du array till funktion?", "back": "Skicka namn: func arr; inuti: local -n ref=$1 eller ${!1[@]}"},
            {"front": "Vad gör shopt?", "back": "Shell options. shopt -s globstar aktiverar ** för recursive glob."},
            {"front": "Hur expanderar du ** (globstar)?", "back": "shopt -s globstar; ls **/*.txt - matchar rekursivt."},
            {"front": "Vad är extglob?", "back": "Extended globbing. shopt -s extglob; rm !(keep.txt) tar bort allt utom keep."},
            {"front": "Hur parsar du long options?", "back": "getopt (externt) eller manuellt med case och shift för --option=value."},
            {"front": "Vad gör FUNCNAME array?", "back": "Stack av funktionsnamn. ${FUNCNAME[0]} = nuvarande, [1] = caller."},
            {"front": "Hur fångar du stderr separat?", "back": "{ cmd 2>&1 1>&3 | stderr_handler; } 3>&1 | stdout_handler"},
            {"front": "Vad är Bash loadable builtins?", "back": "enable -f /path/builtin name - ladda C-kompilerade builtins dynamiskt."},
            {"front": "Hur optimerar du stora loops?", "back": "Undvik subshells i loop. Använd printf istället för echo. Builtin > externa cmd."},
            {"front": "Vad gör BASH_SOURCE?", "back": "Array med källfiler. ${BASH_SOURCE[0]} = nuvarande script även om sourced."},
        ],
    },

    "quiz": {
        "easy": [
            {"question": "Vad är shebang?", "options": ["Variabel", "#!/bin/bash på första raden", "Kommentar", "Funktion"], "correct": 1, "explanation": "Shebang (#!/bin/bash) talar om vilken tolk som ska köra scriptet."},
            {"question": "Hur skapar du variabel i Bash?", "options": ["var = värde", "var=värde", "$var=värde", "set var=värde"], "correct": 1, "explanation": "Inga mellanslag runt =. var=värde är korrekt syntax."},
            {"question": "Hur läser du variabelns värde?", "options": ["var", "$var", "@var", "&var"], "correct": 1, "explanation": "$ före variabelnamn ger dess värde. echo $var"},
            {"question": "Vad returnerar $?", "options": ["Senaste argument", "Exit status", "Process ID", "Variabelnamn"], "correct": 1, "explanation": "$? innehåller exit status från senaste kommando. 0 = success."},
            {"question": "Hur skriver du ut text?", "options": ["print 'text'", "echo 'text'", "write 'text'", "output 'text'"], "correct": 1, "explanation": "echo skriver till stdout. printf för formaterad output."},
            {"question": "Vad är $1 i ett script?", "options": ["Exit status", "Första argumentet", "Script-namn", "Process ID"], "correct": 1, "explanation": "$1 är första argumentet. $0 är scriptnamn, $2 andra argumentet."},
            {"question": "Hur gör du fil körbar?", "options": ["make executable", "chmod +x fil", "run fil", "exec fil"], "correct": 1, "explanation": "chmod +x lägger till execute-permission."},
            {"question": "Hur skriver du kommentar?", "options": ["// kommentar", "/* kommentar */", "# kommentar", "-- kommentar"], "correct": 2, "explanation": "# startar kommentar i Bash. Allt efter # ignoreras."},
            {"question": "Hur avslutar du script med error?", "options": ["exit", "exit 0", "exit 1", "return 1"], "correct": 2, "explanation": "exit 1 (eller annat icke-noll) indikerar fel. exit 0 = success."},
            {"question": "Vad gör && mellan kommandon?", "options": ["Kör parallellt", "Kör nästa om förra lyckades", "Kör båda alltid", "Logisk AND på output"], "correct": 1, "explanation": "cmd1 && cmd2 kör cmd2 bara om cmd1 returnerar 0."},
            {"question": "Hur kontrollerar du om fil finns?", "options": ["if exists fil", "if [ -f fil ]", "if file fil", "if test fil"], "correct": 1, "explanation": "[ -f fil ] testar om fil finns och är vanlig fil."},
            {"question": "Hur loopar du 1-10?", "options": ["for i in 1-10", "for i in {1..10}", "for (i=1;i<=10;i++)", "loop 1 to 10"], "correct": 1, "explanation": "{1..10} är brace expansion som genererar 1 2 3 ... 10."},
            {"question": "Hur definierar du funktion?", "options": ["function name {}", "def name():", "func name()", "name() {}"], "correct": 3, "explanation": "name() { kommandon; } eller function name { } definierar funktion."},
            {"question": "Vad gör || mellan kommandon?", "options": ["Pipe", "Kör nästa om förra misslyckades", "Kör parallellt", "OR på output"], "correct": 1, "explanation": "cmd1 || cmd2 kör cmd2 bara om cmd1 misslyckades (non-zero exit)."},
            {"question": "Hur sparar du command output i variabel?", "options": ["var=kommando", "var=$(kommando)", "var=`kommando`", "Både B och C"], "correct": 3, "explanation": "$(cmd) är modern syntax, `cmd` är äldre. Båda fungerar."},
            {"question": "Hur lägger du till text i fil?", "options": ["echo text > fil", "echo text >> fil", "echo text -> fil", "echo text +> fil"], "correct": 1, "explanation": ">> appendar. > skriver över filen."},
            {"question": "Vad är $#?", "options": ["Alla argument", "Antal argument", "Script PID", "Exit status"], "correct": 1, "explanation": "$# är antalet argument som skickats till scriptet."},
            {"question": "Hur jämför du tal i if?", "options": ["if [ $a == $b ]", "if [ $a -eq $b ]", "if [ $a = $b ]", "if (( a == b ))"], "correct": 1, "explanation": "-eq för equal, -ne not equal, -lt less than, etc. = är för strängar."},
            {"question": "Hur exporterar du variabel?", "options": ["global var=val", "export var=val", "set var=val", "env var=val"], "correct": 1, "explanation": "export gör variabel tillgänglig för child-processer."},
            {"question": "Vad gör while-loop?", "options": ["Loopar fast antal gånger", "Loopar medan villkor är sant", "Loopar över filer", "Loopar en gång"], "correct": 1, "explanation": "while [ villkor ]; do ...; done körs medan villkor är true."},
        ],
        "medium": [
            {"question": "Skillnad mellan [ ] och [[ ]]?", "options": ["Samma sak", "[[ ]] har fler features", "[ ] är Bash-specifik", "[[ ]] är POSIX"], "correct": 1, "explanation": "[[ ]] är Bash-specifik med regex, && ||, ingen word splitting."},
            {"question": "Vad gör ${var:-default}?", "options": ["Sätter default", "Returnerar default om var tom", "Felmeddelande", "Konkatenerar"], "correct": 1, "explanation": ":-default returnerar default om var är tom eller odefinierad."},
            {"question": "Hur får du stränglängd?", "options": ["len($var)", "${#var}", "strlen $var", "$var.length"], "correct": 1, "explanation": "${#var} returnerar antal tecken i var."},
            {"question": "Vad gör ${var%.txt}?", "options": ["Lägger till .txt", "Tar bort .txt från slutet", "Tar bort .txt från början", "Ersätter .txt"], "correct": 1, "explanation": "% tar bort pattern från slutet. %% för längsta match."},
            {"question": "Hur skapar du array?", "options": ["arr=[a,b,c]", "arr=(a b c)", "arr={a,b,c}", "array arr a b c"], "correct": 1, "explanation": "arr=(element1 element2 element3) skapar indexerad array."},
            {"question": "Hur läser du alla array-element?", "options": ["$arr", "${arr}", "${arr[@]}", "${arr[*]}"], "correct": 2, "explanation": "${arr[@]} expanderar alla element. Med quotes bevaras separata ord."},
            {"question": "Vad gör set -e?", "options": ["Enable echo", "Exit vid fel", "Error logging", "Extended mode"], "correct": 1, "explanation": "set -e avbryter script om kommando misslyckas."},
            {"question": "Vad gör set -u?", "options": ["Uppercase vars", "Error på odefinierade vars", "Unique mode", "User mode"], "correct": 1, "explanation": "set -u gör det till fel att använda odefinierade variabler."},
            {"question": "Hur fångar du EXIT signal?", "options": ["catch EXIT", "trap 'cmd' EXIT", "on EXIT cmd", "signal EXIT cmd"], "correct": 1, "explanation": "trap 'cleanup_function' EXIT kör cleanup oavsett hur script avslutas."},
            {"question": "Vad gör getopts?", "options": ["Hämtar options", "Parsar command line options", "Sätter options", "Listar options"], "correct": 1, "explanation": "getopts parsar -a, -b value style options i scripts."},
            {"question": "Hur gör du arithmetic?", "options": ["$a+$b", "$((a+b))", "math a+b", "calc a+b"], "correct": 1, "explanation": "$((expression)) evaluerar arithmetic. let och expr finns också."},
            {"question": "Vad gör shift?", "options": ["Flyttar filer", "Skiftar arguments", "Byter variabel", "Roterar array"], "correct": 1, "explanation": "shift flyttar arguments: $2 blir $1, $3 blir $2, osv."},
            {"question": "Hur deklarerar du local variabel?", "options": ["local var=val", "let var=val", "my var=val", "private var=val"], "correct": 0, "explanation": "local var=val gör variabeln synlig bara i funktionen."},
            {"question": "Vad är heredoc?", "options": ["Dokumentation", "Multiline input med <<EOF", "Here-and-there doc", "Help doc"], "correct": 1, "explanation": "<<EOF ... EOF skickar multiline text som input."},
            {"question": "Hur debuggar du script?", "options": ["bash --debug", "bash -x script", "debug script", "bash -d script"], "correct": 1, "explanation": "bash -x visar varje kommando som körs. set -x i script fungerar också."},
            {"question": "Vad gör case-statement?", "options": ["Switch-case matching", "Error handling", "Loop control", "Variable case"], "correct": 0, "explanation": "case $var in pattern) cmd;; esac matchar mönster."},
            {"question": "Hur kör du command i bakgrund?", "options": ["cmd bg", "cmd &", "bg cmd", "& cmd"], "correct": 1, "explanation": "& efter kommando kör det i bakgrund."},
            {"question": "Vad gör wait?", "options": ["Pausar script", "Väntar på bakgrundsprocesser", "Timeout", "Sleep"], "correct": 1, "explanation": "wait väntar tills alla bakgrundsprocesser är klara."},
            {"question": "Hur ersätter du alla förekomster i sträng?", "options": ["${var/old/new}", "${var//old/new}", "${var:old:new}", "replace $var old new"], "correct": 1, "explanation": "// ersätter alla. / ersätter bara första förekomsten."},
            {"question": "Vad gör source script.sh?", "options": ["Kompilerar", "Kör i nuvarande shell", "Kör i subshell", "Validerar syntax"], "correct": 1, "explanation": "source (eller .) kör script i nuvarande shell så variabler bevaras."},
        ],
        "hard": [
            {"question": "Vad gör process substitution <(cmd)?", "options": ["Subshell", "Behandlar output som fil", "Redirect", "Pipe"], "correct": 1, "explanation": "<(cmd) skapar named pipe som ser ut som fil. diff <(cmd1) <(cmd2)"},
            {"question": "Vad är BASH_REMATCH?", "options": ["Pattern match result", "Regex capture groups", "Match count", "Last match"], "correct": 1, "explanation": "Efter [[ str =~ regex ]] innehåller BASH_REMATCH capture groups."},
            {"question": "Vad gör set -o pipefail?", "options": ["Pipe optimization", "Returnerar fel om något i pipe misslyckas", "Fail on pipe", "Pipeline fail"], "correct": 1, "explanation": "Normalt returnerar pipe sista kommandots exit. pipefail returnerar första fel."},
            {"question": "Hur låser du fil för concurrent access?", "options": ["lock fil", "flock fil cmd", "mutex fil", "sync fil"], "correct": 1, "explanation": "flock -x lockfile -c 'cmd' ger exclusive lock."},
            {"question": "Vad gör exec 3>&1?", "options": ["Execute fd 3", "Duplicerar stdout till fd 3", "Redirect fd 3", "Close fd 3"], "correct": 1, "explanation": "Duplicerar fd 1 (stdout) till fd 3. Användbart för att spara streams."},
            {"question": "Vad är nameref (declare -n)?", "options": ["Named reference till variabel", "Negative number", "New reference", "Null reference"], "correct": 0, "explanation": "declare -n ref=var gör ref till reference. Ändra ref ändrar var."},
            {"question": "Hur gör du atomic file write?", "options": ["echo > file", "Skriv till temp, mv till dest", "lock + write", "sync write"], "correct": 1, "explanation": "Skriv till tempfil, sedan mv. mv är atomic på samma filsystem."},
            {"question": "Vad gör mapfile/readarray?", "options": ["Map funktion över array", "Läser fil till array", "Array till fil", "Mappa filer"], "correct": 1, "explanation": "mapfile -t arr < fil läser varje rad till array-element."},
            {"question": "Hur hanterar du filnamn med spaces?", "options": ["Quote alltid", "find -print0 | xargs -0", "Båda", "Undvik spaces"], "correct": 2, "explanation": "Quotes och null-separation (-print0) hanterar special chars."},
            {"question": "Vad gör indirect reference ${!var}?", "options": ["Negation", "Expanderar variabel vars namn är i var", "Last variable", "Inverse"], "correct": 1, "explanation": "name=foo; foo=bar; echo ${!name} ger bar."},
            {"question": "Vad gör shopt -s globstar?", "options": ["Global star", "** matchar rekursivt", "Glob options", "Star expansion"], "correct": 1, "explanation": "Med globstar: **/*.txt matchar alla txt-filer rekursivt."},
            {"question": "Vad är extglob?", "options": ["External glob", "Extended globbing patterns", "Extra glob", "Exit glob"], "correct": 1, "explanation": "extglob ger !(pattern), @(a|b), *(pattern), etc."},
            {"question": "Hur skickar du array till funktion?", "options": ["func ${arr[@]}", "func arr (nameref)", "func \"${arr[@]}\"", "Alla kan funka"], "correct": 3, "explanation": "Pass by value med ${arr[@]} eller by reference med nameref."},
            {"question": "Vad gör FUNCNAME?", "options": ["Current function name", "Array av function call stack", "Function count", "Named function"], "correct": 1, "explanation": "FUNCNAME är array: [0]=current, [1]=caller, etc."},
            {"question": "Vad är Bash strict mode?", "options": ["Strict syntax", "set -euo pipefail", "Error checking", "Safe mode"], "correct": 1, "explanation": "set -euo pipefail är kombination för robusta scripts."},
            {"question": "Hur testar du Bash scripts?", "options": ["unittest", "bats/shunit2", "pytest", "jest"], "correct": 1, "explanation": "bats (Bash Automated Testing System) är populärt testramverk."},
            {"question": "Vad gör coproc?", "options": ["Copy process", "Bakgrundsprocess med fd", "Concurrent process", "Core process"], "correct": 1, "explanation": "coproc kör process med tillgängliga input/output file descriptors."},
            {"question": "Hur får du script's directory?", "options": ["$PWD", "dirname $0", "$(dirname ${BASH_SOURCE[0]})", "$SCRIPT_DIR"], "correct": 2, "explanation": "BASH_SOURCE[0] ger rätt sökväg även vid source."},
            {"question": "Vad gör PROMPT_COMMAND?", "options": ["Prompt text", "Körs före varje prompt", "Command prompt", "History command"], "correct": 1, "explanation": "PROMPT_COMMAND körs automatiskt före varje PS1-prompt."},
            {"question": "Hur fångar du stderr separat från stdout?", "options": ["2>&1", "3>&1; 2>&3; 1>&3", "{ cmd 2>&1 1>&3 | handler } 3>&1", "stderr > file"], "correct": 2, "explanation": "Kräver fd-manipulation för att separera och hantera streams."},
        ],
    },

    "nodes": [
        {"id": 1, "title": "Bash Introduktion", "slug": "bash-intro"},
        {"id": 2, "title": "Variabler & Typer", "slug": "variables-types"},
        {"id": 3, "title": "Input & Output", "slug": "input-output"},
        {"id": 4, "title": "Villkorssatser", "slug": "conditionals"},
        {"id": 5, "title": "Test Commands", "slug": "test-commands"},
        {"id": 6, "title": "Loopar", "slug": "loops"},
        {"id": 7, "title": "Funktioner", "slug": "functions"},
        {"id": 8, "title": "Arrays", "slug": "arrays"},
        {"id": 9, "title": "String Manipulation", "slug": "string-manipulation"},
        {"id": 10, "title": "Parameter Expansion", "slug": "parameter-expansion"},
        {"id": 11, "title": "Redirects & Pipes", "slug": "redirects-pipes"},
        {"id": 12, "title": "Process Management", "slug": "process-management"},
        {"id": 13, "title": "Error Handling", "slug": "error-handling"},
        {"id": 14, "title": "Signals & Traps", "slug": "signals-traps"},
        {"id": 15, "title": "Debugging", "slug": "debugging"},
        {"id": 16, "title": "Regex & Pattern Matching", "slug": "regex-patterns"},
        {"id": 17, "title": "Options Parsing", "slug": "options-parsing"},
        {"id": 18, "title": "Best Practices", "slug": "best-practices"},
        {"id": 19, "title": "Testing Scripts", "slug": "testing-scripts"},
        {"id": 20, "title": "Production Scripts", "slug": "production-scripts"},
    ],
}
