"""
CI/CD Pipelines - Study Data
============================

90 Flashcards (30 easy, 30 medium, 30 hard)
60 Quiz Questions (20 easy, 20 medium, 20 hard)
"""

CICD_STUDY_DATA = {
    "module_slug": "cicd-pipelines",
    "module_title": "CI/CD Pipelines",
    "module_description": "Continuous Integration och Continuous Delivery/Deployment",
    "icon": "GitPullRequest",

    "flashcards": {
        "easy": [
            {"front": "Vad är CI (Continuous Integration)?", "back": "Automatisk integration av kodändringar. Bygga och testa kod vid varje commit."},
            {"front": "Vad är CD (Continuous Delivery)?", "back": "Automatisk leverans av kod till staging. Manuell deploy till produktion."},
            {"front": "Vad är Continuous Deployment?", "back": "Automatisk deploy hela vägen till produktion. Varje commit som klarar tester deployas."},
            {"front": "Vad är en pipeline?", "back": "Automatiserad sekvens av steg: build, test, deploy. Definieras i kod."},
            {"front": "Vad är GitHub Actions?", "back": "CI/CD platform integrerad i GitHub. Workflows definieras i .github/workflows/"},
            {"front": "Vad är en workflow?", "back": "Automatiserad process i GitHub Actions. Triggad av events (push, PR, etc)."},
            {"front": "Vad är GitLab CI?", "back": "CI/CD inbyggd i GitLab. Pipeline definieras i .gitlab-ci.yml"},
            {"front": "Vad är Jenkins?", "back": "Open source automation server. Plugins för CI/CD, mest flexibel."},
            {"front": "Vad är en build?", "back": "Kompilering av kod till körbart format. Docker image, JAR, bundle, etc."},
            {"front": "Vad är ett test stage?", "back": "Körning av automatiserade tester. Unit, integration, E2E."},
            {"front": "Vad är deploy stage?", "back": "Leverans av applikation till miljö. Dev, staging, produktion."},
            {"front": "Vad är en runner/agent?", "back": "Server som exekverar pipeline-jobb. Kan vara hosted eller self-hosted."},
            {"front": "Vad är trigger?", "back": "Event som startar pipeline. Push, PR, schedule, manual."},
            {"front": "Vad är artifact?", "back": "Output från build. Docker image, binär, paket som sparas."},
            {"front": "Vad är job i CI/CD?", "back": "Enskild uppgift i pipeline. Build job, test job, deploy job."},
            {"front": "Vad är stage?", "back": "Grupp av jobs som körs. Build stage, test stage, deploy stage."},
            {"front": "Vad är YAML?", "back": "Markup language för config. De flesta CI/CD tools använder YAML."},
            {"front": "Vad är environment variable?", "back": "Variabel tillgänglig i pipeline. API keys, config values."},
            {"front": "Vad är secret?", "back": "Krypterad environment variable. Lösenord, tokens, certifikat."},
            {"front": "Vad är caching i CI?", "back": "Spara beroenden mellan körningar. npm cache, pip cache. Snabbar upp builds."},
            {"front": "Vad är parallel execution?", "back": "Köra jobs samtidigt. Test job A och B körs parallellt."},
            {"front": "Vad är branch protection?", "back": "Kräver godkända checks för merge. Status checks must pass."},
            {"front": "Vad är status check?", "back": "Resultat från CI. Passed/failed visas på PR."},
            {"front": "Vad är pull request pipeline?", "back": "Pipeline som körs vid PR. Validerar innan merge."},
            {"front": "Vad är main/master pipeline?", "back": "Pipeline på huvudbranch. Ofta deploy till staging/prod."},
            {"front": "Vad är linting i CI?", "back": "Statisk kodanalys. ESLint, Pylint, etc körs automatiskt."},
            {"front": "Vad är code coverage?", "back": "Procent av kod som testas. Rapporteras i CI."},
            {"front": "Vad är notification?", "back": "Meddelande vid pipeline-status. Slack, email vid failure."},
            {"front": "Vad är retry?", "back": "Köra om misslyckat jobb. Hanterar flaky tests."},
            {"front": "Vad är timeout?", "back": "Max tid för job. Förhindrar hängande pipelines."},
        ],
        "medium": [
            {"front": "Vad är matrix build?", "back": "Testa mot flera versioner/OS. Node 16, 18, 20 × Ubuntu, Windows."},
            {"front": "Vad är conditional jobs?", "back": "Jobs som körs baserat på villkor. if: github.ref == 'refs/heads/main'"},
            {"front": "Vad är pipeline as code?", "back": "Pipeline definierad i repo. Versionshanterad som övrig kod."},
            {"front": "Vad är Jenkinsfile?", "back": "Pipeline definition för Jenkins. Groovy syntax, deklarativ eller scripted."},
            {"front": "Vad är multibranch pipeline?", "back": "En pipeline per branch. Jenkins skapar automatiskt."},
            {"front": "Vad är monorepo CI?", "back": "CI för monorepo. Kör bara för ändrade paket. Path filters."},
            {"front": "Vad är path filter?", "back": "Trigga baserat på ändrade filer. paths: ['frontend/**']"},
            {"front": "Vad är reusable workflow?", "back": "Workflow som kan kallas från andra. DRY principle i CI/CD."},
            {"front": "Vad är composite action?", "back": "Custom GitHub Action med flera steps. Återanvändbar logik."},
            {"front": "Vad är Docker-in-Docker?", "back": "Bygga Docker images i CI container. DinD service."},
            {"front": "Vad är service container?", "back": "Sidocontainer i CI. Database, Redis för integration tests."},
            {"front": "Vad är deployment environment?", "back": "Konfigurerad miljö med protection rules. Manual approval, secrets."},
            {"front": "Vad är release pipeline?", "back": "Pipeline för releases. Semantic versioning, changelogs, tagging."},
            {"front": "Vad är rollback?", "back": "Återställa tidigare version. Vid failed deploy."},
            {"front": "Vad är blue-green deployment?", "back": "Två identiska miljöer. Switch traffic till ny version."},
            {"front": "Vad är canary deployment?", "back": "Gradvis rollout. 5% → 25% → 100% av trafik."},
            {"front": "Vad är feature flag?", "back": "Toggle för features. Deployas men aktiveras separat."},
            {"front": "Vad är smoke test?", "back": "Snabba tester efter deploy. Verifierar basic functionality."},
            {"front": "Vad är SAST?", "back": "Static Application Security Testing. Sårbarhetsskanning i CI."},
            {"front": "Vad är DAST?", "back": "Dynamic Application Security Testing. Testar running application."},
            {"front": "Vad är dependency scanning?", "back": "Sök sårbara dependencies. npm audit, Snyk, Dependabot."},
            {"front": "Vad är container scanning?", "back": "Skanna Docker images för CVEs. Trivy, Clair."},
            {"front": "Vad är artifacts retention?", "back": "Hur länge artifacts sparas. 30 dagar default ofta."},
            {"front": "Vad är self-hosted runner?", "back": "Egen server som runner. Full kontroll, specifik hardware."},
            {"front": "Vad är concurrency control?", "back": "Begränsa parallella runs. cancel-in-progress för nya commits."},
            {"front": "Vad är required reviewers?", "back": "Kräv godkännande från specifika personer. Environment protection."},
            {"front": "Vad är wait timer?", "back": "Fördröjning innan deploy. Tid för manuell granskning."},
            {"front": "Vad är artifact upload/download?", "back": "Dela filer mellan jobs. Build → test → deploy."},
            {"front": "Vad är manual trigger?", "back": "Starta pipeline manuellt. workflow_dispatch i GitHub Actions."},
            {"front": "Vad är scheduled pipeline?", "back": "Cron-baserad körning. Nightly builds, weekly security scans."},
        ],
        "hard": [
            {"front": "Vad är GitOps?", "back": "Git som single source of truth. Argo CD, Flux synckar från git till cluster."},
            {"front": "Vad är Argo CD?", "back": "Declarative GitOps CD för Kubernetes. Synkar git state till cluster."},
            {"front": "Vad är Flux?", "back": "GitOps toolkit för Kubernetes. Continuous delivery från git."},
            {"front": "Vad är trunk-based development?", "back": "Alla committar till main. Korta branches, frekventa merges."},
            {"front": "Vad är feature branching?", "back": "Branch per feature. PR för merge. Längre livslängd."},
            {"front": "Vad är GitFlow?", "back": "Branch-strategi med develop, release, hotfix. Mer komplext."},
            {"front": "Vad är environment promotion?", "back": "Artifact rör sig genom miljöer. Dev → staging → prod."},
            {"front": "Vad är immutable deployments?", "back": "Nya versioner = nya instanser. Ingen in-place update."},
            {"front": "Vad är progressive delivery?", "back": "Gradvis rollout med monitoring. Canary, A/B, feature flags."},
            {"front": "Vad är pipeline orchestration?", "back": "Koordinera komplexa pipelines. Cross-project dependencies."},
            {"front": "Vad är fan-out/fan-in?", "back": "Parallella jobs som konvergerar. Build → tests (parallel) → deploy."},
            {"front": "Vad är ephemeral environments?", "back": "Temporära miljöer per PR. Förhandsgranska changes."},
            {"front": "Vad är Tekton?", "back": "Kubernetes-native CI/CD. Pipeline CRDs, cloud-native."},
            {"front": "Vad är Dagger?", "back": "CI/CD as code i Go/Python/TS. Portabla pipelines."},
            {"front": "Vad är BuildKit?", "back": "Next-gen Docker builder. Effektivare caching, parallellism."},
            {"front": "Vad är multi-arch builds?", "back": "Bygga för flera arkitekturer. amd64 + arm64 images."},
            {"front": "Vad är signed commits?", "back": "GPG-signerade commits. Verifierar author identity."},
            {"front": "Vad är attestation?", "back": "Kryptografisk bevis på build. SLSA, in-toto."},
            {"front": "Vad är SLSA?", "back": "Supply-chain Levels for Software Artifacts. Security framework."},
            {"front": "Vad är SBOM?", "back": "Software Bill of Materials. Lista över dependencies."},
            {"front": "Vad är policy as code?", "back": "Policies definierade som kod. OPA, Conftest validerar."},
            {"front": "Vad är compliance pipeline?", "back": "Automatisk compliance-verifiering. SOC2, HIPAA checks."},
            {"front": "Vad är chaos engineering i CI?", "back": "Injicera failures i pipeline. Testa resilience."},
            {"front": "Vad är pipeline observability?", "back": "Metrics och traces för CI/CD. Build times, failure rates."},
            {"front": "Vad är DORA metrics?", "back": "DevOps Research metrics. Deploy frequency, lead time, MTTR, failure rate."},
            {"front": "Vad är deployment frequency?", "back": "Hur ofta deployas. Elite = multiple per dag."},
            {"front": "Vad är lead time for changes?", "back": "Commit till produktion. Elite = under 1 timme."},
            {"front": "Vad är MTTR?", "back": "Mean Time To Recovery. Hur snabbt återställs service."},
            {"front": "Vad är change failure rate?", "back": "Procent deployments som orsakar incidents. Elite = 0-15%."},
            {"front": "Vad är infrastructure pipelines?", "back": "CI/CD för IaC. Terraform plan → apply i pipeline."},
        ],
    },

    "quiz": {
        "easy": [
            {"question": "Vad är CI?", "options": ["Continuous Inspection", "Continuous Integration", "Code Integration", "Continuous Installation"], "correct": 1, "explanation": "CI = Continuous Integration - automatisk build och test vid commits."},
            {"question": "Vad är skillnaden mellan Continuous Delivery och Deployment?", "options": ["Samma sak", "Delivery = manuell prod deploy, Deployment = automatisk", "Delivery är snabbare", "Deployment kräver approval"], "correct": 1, "explanation": "Delivery stoppar vid staging. Deployment går automatiskt till prod."},
            {"question": "Var definieras GitHub Actions workflows?", "options": [".github/actions/", ".github/workflows/", "workflows/", ".actions/"], "correct": 1, "explanation": "GitHub Actions workflows ligger i .github/workflows/*.yml"},
            {"question": "Vad är en pipeline trigger?", "options": ["Pipeline output", "Event som startar pipeline", "Pipeline config", "Test runner"], "correct": 1, "explanation": "Trigger är event (push, PR, schedule) som startar pipeline."},
            {"question": "Vad är en artifact?", "options": ["Source code", "Output från build", "Test results", "Pipeline config"], "correct": 1, "explanation": "Artifact är build output - Docker image, binär, paket."},
            {"question": "Vad är purpose med CI caching?", "options": ["Spara logs", "Snabba upp builds genom att spara dependencies", "Cache testresultat", "Backup"], "correct": 1, "explanation": "Caching sparar node_modules, pip packages mellan runs."},
            {"question": "Vad är en runner?", "options": ["Test framework", "Server som kör pipeline-jobs", "Deployment tool", "Build cache"], "correct": 1, "explanation": "Runner/agent är servern som exekverar CI/CD jobs."},
            {"question": "Vad är GitLab CI config fil?", "options": ["gitlab.yml", ".gitlab-ci.yml", "ci.yml", "pipeline.yml"], "correct": 1, "explanation": "GitLab CI definieras i .gitlab-ci.yml i repo root."},
            {"question": "Vad menas med status check?", "options": ["Health check", "CI-resultat visad på PR", "Manual check", "Deployment status"], "correct": 1, "explanation": "Status checks visar CI pass/fail på pull requests."},
            {"question": "Vad är secret i CI/CD?", "options": ["Hemlig pipeline", "Krypterad environment variable", "Private repo", "Secret branch"], "correct": 1, "explanation": "Secrets är krypterade variabler för känslig data."},
            {"question": "Vad är linting i CI?", "options": ["Code compilation", "Statisk kodanalys", "Runtime testing", "Performance testing"], "correct": 1, "explanation": "Linting är statisk analys - ESLint, Pylint i pipeline."},
            {"question": "Vad är code coverage?", "options": ["Hur många filer finns", "Procent av kod som testas", "Lines of code", "Branch coverage"], "correct": 1, "explanation": "Coverage visar hur mycket kod som körs under tester."},
            {"question": "Vad är parallel execution i CI?", "options": ["Sequential jobs", "Köra flera jobs samtidigt", "Multi-threading", "Load balancing"], "correct": 1, "explanation": "Parallella jobs körs samtidigt för snabbare pipeline."},
            {"question": "Vad är branch protection?", "options": ["Backup av branches", "Kräv checks innan merge", "Branch encryption", "Branch naming"], "correct": 1, "explanation": "Branch protection kräver godkända checks för merge."},
            {"question": "Vad gör retry i CI?", "options": ["Restart pipeline", "Kör om misslyckat job", "Retry login", "Rebuild cache"], "correct": 1, "explanation": "Retry kör om failed job, hjälper mot flaky tests."},
            {"question": "Vad är timeout i pipeline?", "options": ["Session timeout", "Max tid för job", "API timeout", "Cache timeout"], "correct": 1, "explanation": "Timeout förhindrar hängande jobs."},
            {"question": "Vad är deploy stage?", "options": ["Första steget", "Leverans till miljö", "Test stage", "Build stage"], "correct": 1, "explanation": "Deploy stage levererar applikation till dev/staging/prod."},
            {"question": "Vad är Jenkins?", "options": ["GitHub feature", "Open source automation server", "GitLab plugin", "Cloud provider"], "correct": 1, "explanation": "Jenkins är populär open source CI/CD server."},
            {"question": "Vad är notification i CI?", "options": ["Push notification", "Meddelande vid pipeline-status", "PR notification", "Email marketing"], "correct": 1, "explanation": "Notifications skickas vid failure/success - Slack, email."},
            {"question": "Vad är YAML?", "options": ["Programming language", "Markup language för config", "Testing framework", "Build tool"], "correct": 1, "explanation": "YAML är data format som de flesta CI tools använder."},
        ],
        "medium": [
            {"question": "Vad är matrix build?", "options": ["Build grid", "Testa mot flera versioner/plattformar", "Parallel builds", "Build matrix optimization"], "correct": 1, "explanation": "Matrix bygger och testar mot kombinationer av versions/OS."},
            {"question": "Vad är pipeline as code?", "options": ["Kod i pipeline", "Pipeline definierad i versionshanterad fil", "Code generation", "Pipeline script"], "correct": 1, "explanation": "Pipeline as code = pipeline-config i repo, versionshanterad."},
            {"question": "Vad är Jenkinsfile?", "options": ["Config fil", "Pipeline definition för Jenkins", "Docker file", "Deployment manifest"], "correct": 1, "explanation": "Jenkinsfile definierar Jenkins pipeline i Groovy."},
            {"question": "Vad är monorepo CI-utmaning?", "options": ["Stora repos", "Köra bara för ändrade delar", "Single pipeline", "Shared dependencies"], "correct": 1, "explanation": "Monorepo CI måste kunna filtrera baserat på path changes."},
            {"question": "Vad är reusable workflow?", "options": ["Repeated workflow", "Workflow som kan kallas från andra", "Template workflow", "Shared steps"], "correct": 1, "explanation": "Reusable workflows kan återanvändas av andra workflows."},
            {"question": "Vad är service container?", "options": ["Microservice", "Sidocontainer för tests (DB, Redis)", "Docker service", "CI container"], "correct": 1, "explanation": "Service containers kör dependencies för integration tests."},
            {"question": "Vad är blue-green deployment?", "options": ["Color coding", "Två identiska miljöer med traffic switch", "Testing strategy", "Multi-region deployment"], "correct": 1, "explanation": "Blue-green har två miljöer - switch traffic för instant rollback."},
            {"question": "Vad är canary deployment?", "options": ["Test deployment", "Gradvis rollout till del av trafik", "Canary testing", "A/B deployment"], "correct": 1, "explanation": "Canary skickar först liten del av trafik till ny version."},
            {"question": "Vad är feature flag?", "options": ["Feature branch", "Toggle för att aktivera features", "Feature test", "Flag file"], "correct": 1, "explanation": "Feature flags låter dig deploya kod men aktivera separat."},
            {"question": "Vad är smoke test?", "options": ["Load test", "Snabba tester efter deploy", "Unit test", "Integration test"], "correct": 1, "explanation": "Smoke tests verifierar basic functionality efter deploy."},
            {"question": "Vad är SAST?", "options": ["Security Analysis Software Tool", "Static Application Security Testing", "System Analysis Security Test", "Source Analysis Security Tool"], "correct": 1, "explanation": "SAST skannar källkod för säkerhetsproblem."},
            {"question": "Vad är dependency scanning?", "options": ["Scan imports", "Hitta sårbara dependencies", "Check versions", "Dependency graph"], "correct": 1, "explanation": "Dependency scanning hittar CVEs i npm/pip packages."},
            {"question": "Vad är container scanning?", "options": ["Docker inspect", "Skanna images för sårbarheter", "Container logs", "Image diff"], "correct": 1, "explanation": "Container scanning hittar CVEs i Docker images."},
            {"question": "Vad är self-hosted runner?", "options": ["Local runner", "Egen server som CI runner", "Private cloud", "On-prem CI"], "correct": 1, "explanation": "Self-hosted runner är egen server istället för cloud-hosted."},
            {"question": "Vad är concurrency control?", "options": ["Thread control", "Begränsa parallella pipeline runs", "Job control", "Process control"], "correct": 1, "explanation": "Concurrency control begränsar samtidiga runs, cancel-in-progress."},
            {"question": "Vad är environment protection?", "options": ["Env security", "Regler för deployment environments", "Variable protection", "Secret protection"], "correct": 1, "explanation": "Environment protection kräver approval, wait timer, etc."},
            {"question": "Vad är artifact upload/download?", "options": ["File transfer", "Dela filer mellan pipeline jobs", "Artifact storage", "Binary upload"], "correct": 1, "explanation": "Artifacts delas mellan jobs - build output till test job."},
            {"question": "Vad är workflow_dispatch?", "options": ["Workflow start", "Manual trigger för GitHub Actions", "Event dispatch", "API trigger"], "correct": 1, "explanation": "workflow_dispatch låter dig starta workflow manuellt."},
            {"question": "Vad är scheduled pipeline?", "options": ["Pipeline queue", "Cron-baserad körning", "Delayed pipeline", "Batch pipeline"], "correct": 1, "explanation": "Schedule kör pipelines på bestämda tider - nightly builds."},
            {"question": "Vad är rollback?", "options": ["Undo commit", "Återställa tidigare version", "Revert PR", "Git reset"], "correct": 1, "explanation": "Rollback återställer tidigare fungerande version vid problem."},
        ],
        "hard": [
            {"question": "Vad är GitOps?", "options": ["Git workflow", "Git som single source of truth för deployments", "Git operations", "Git automation"], "correct": 1, "explanation": "GitOps synckar desired state från git till cluster automatiskt."},
            {"question": "Vad är Argo CD?", "options": ["CI tool", "GitOps CD för Kubernetes", "Argo workflow", "CD platform"], "correct": 1, "explanation": "Argo CD synkar Kubernetes state från git repositories."},
            {"question": "Vad är trunk-based development?", "options": ["Branch strategy", "Alla committar till main, korta branches", "Trunk repo", "Main development"], "correct": 1, "explanation": "Trunk-based = main branch focus, korta feature branches."},
            {"question": "Vad är progressive delivery?", "options": ["Gradual deployment", "Gradvis rollout med monitoring och rollback", "Progressive enhancement", "Staged delivery"], "correct": 1, "explanation": "Progressive delivery = canary + feature flags + observability."},
            {"question": "Vad är ephemeral environments?", "options": ["Short-lived envs", "Temporära miljöer per PR", "Ephemeral storage", "Dynamic envs"], "correct": 0, "explanation": "Ephemeral environments skapas för PR preview, tas bort efter merge."},
            {"question": "Vad är Tekton?", "options": ["CI server", "Kubernetes-native CI/CD med CRDs", "Jenkins plugin", "GitLab runner"], "correct": 1, "explanation": "Tekton är cloud-native CI/CD byggd på Kubernetes."},
            {"question": "Vad är SLSA?", "options": ["Security Level Software Assessment", "Supply-chain Levels for Software Artifacts", "Software Lifecycle Security Audit", "Source Level Security Analysis"], "correct": 1, "explanation": "SLSA är framework för supply chain security."},
            {"question": "Vad är SBOM?", "options": ["Software Build Output Manifest", "Software Bill of Materials", "Security Build Object Model", "Source Binary Object Map"], "correct": 1, "explanation": "SBOM är lista över alla dependencies i software."},
            {"question": "Vad är policy as code?", "options": ["Code policies", "Policies definierade och validerade som kod", "Policy enforcement", "Code standards"], "correct": 1, "explanation": "Policy as code använder OPA/Conftest för automatisk validering."},
            {"question": "Vad är DORA deployment frequency?", "options": ["Deploy count", "Hur ofta organisation deployer", "Release frequency", "Build frequency"], "correct": 1, "explanation": "Deployment frequency är DORA metric - elite = multiple/dag."},
            {"question": "Vad är lead time for changes?", "options": ["Development time", "Tid från commit till produktion", "Review time", "Build time"], "correct": 1, "explanation": "Lead time mäter hur snabbt kod når produktion - elite <1h."},
            {"question": "Vad är MTTR?", "options": ["Mean Time To Release", "Mean Time To Recovery", "Maximum Time To Resolve", "Minimum Time To Restore"], "correct": 1, "explanation": "MTTR = Mean Time To Recovery - hur snabbt återställs service."},
            {"question": "Vad är change failure rate?", "options": ["Test failure rate", "Procent deploys som orsakar incidents", "Build failure rate", "Rollback rate"], "correct": 1, "explanation": "Change failure rate = deployments som kräver rollback/fix."},
            {"question": "Vad är fan-out/fan-in pattern?", "options": ["Load distribution", "Parallella jobs som konvergerar", "Event pattern", "Messaging pattern"], "correct": 1, "explanation": "Fan-out = parallella jobs, fan-in = vänta på alla."},
            {"question": "Vad är immutable deployments?", "options": ["Read-only deploys", "Nya versioner = nya instanser", "Immutable infrastructure", "No-update deploys"], "correct": 1, "explanation": "Immutable = ingen in-place update, nya instanser istället."},
            {"question": "Vad är BuildKit?", "options": ["Build framework", "Next-gen Docker builder med bättre caching", "Kubernetes builder", "CI build tool"], "correct": 1, "explanation": "BuildKit är modern Docker builder med parallellism och caching."},
            {"question": "Vad är multi-arch builds?", "options": ["Multiple architectures", "Bygga images för amd64 och arm64", "Cross compilation", "Platform builds"], "correct": 1, "explanation": "Multi-arch bygger samma image för flera CPU-arkitekturer."},
            {"question": "Vad är signed commits?", "options": ["Approved commits", "GPG-signerade commits för verifiering", "Reviewed commits", "Validated commits"], "correct": 1, "explanation": "Signed commits bevisar author identity kryptografiskt."},
            {"question": "Vad är attestation i CI/CD?", "options": ["Certification", "Kryptografiskt bevis på build provenance", "Verification", "Audit log"], "correct": 1, "explanation": "Attestation bevisar vem byggde vad, när, hur - supply chain security."},
            {"question": "Vad är infrastructure pipelines?", "options": ["Infra deployment", "CI/CD för IaC (Terraform plan/apply)", "Server pipelines", "Network CI"], "correct": 1, "explanation": "Infrastructure pipelines kör Terraform/Pulumi i CI/CD."},
        ],
    },

    "nodes": [
        {"id": 1, "title": "CI/CD Introduktion", "slug": "cicd-intro"},
        {"id": 2, "title": "CI vs CD vs CD", "slug": "ci-cd-cd"},
        {"id": 3, "title": "GitHub Actions Basics", "slug": "github-actions-basics"},
        {"id": 4, "title": "Workflow Syntax", "slug": "workflow-syntax"},
        {"id": 5, "title": "Triggers & Events", "slug": "triggers-events"},
        {"id": 6, "title": "Jobs & Steps", "slug": "jobs-steps"},
        {"id": 7, "title": "Secrets & Variables", "slug": "secrets-variables"},
        {"id": 8, "title": "Caching & Artifacts", "slug": "caching-artifacts"},
        {"id": 9, "title": "Matrix Builds", "slug": "matrix-builds"},
        {"id": 10, "title": "Reusable Workflows", "slug": "reusable-workflows"},
        {"id": 11, "title": "GitLab CI/CD", "slug": "gitlab-cicd"},
        {"id": 12, "title": "Jenkins Pipelines", "slug": "jenkins-pipelines"},
        {"id": 13, "title": "Deployment Strategies", "slug": "deployment-strategies"},
        {"id": 14, "title": "Environment Management", "slug": "environment-management"},
        {"id": 15, "title": "Security Scanning", "slug": "security-scanning"},
        {"id": 16, "title": "GitOps med Argo CD", "slug": "gitops-argocd"},
        {"id": 17, "title": "DORA Metrics", "slug": "dora-metrics"},
        {"id": 18, "title": "Pipeline Optimization", "slug": "pipeline-optimization"},
        {"id": 19, "title": "Supply Chain Security", "slug": "supply-chain-security"},
        {"id": 20, "title": "Enterprise CI/CD", "slug": "enterprise-cicd"},
    ],
}
