"""
Kubernetes Mastery - Study Data
===============================

90 Flashcards (30 easy, 30 medium, 30 hard)
60 Quiz Questions (20 easy, 20 medium, 20 hard)
"""

KUBERNETES_STUDY_DATA = {
    "module_slug": "kubernetes-mastery",
    "module_title": "Kubernetes Mastery",
    "module_description": "Container-orkestrering med K8s",
    "icon": "Layers",

    "flashcards": {
        "easy": [
            {"front": "Vad är Kubernetes?", "back": "Open-source plattform för att automatisera deployment, skalning och hantering av containeriserade applikationer."},
            {"front": "Vad är en Pod?", "back": "Minsta deployningsbara enhet i K8s. Innehåller en eller flera containers som delar nätverk och lagring."},
            {"front": "Vad gör kubectl?", "back": "Kommandoradsverktyg för att kommunicera med Kubernetes-kluster. kubectl get pods, kubectl apply, etc."},
            {"front": "Vad är en Node?", "back": "En maskin (fysisk eller virtuell) som kör workloads. Worker nodes kör pods, master nodes hanterar klustret."},
            {"front": "Vad är ett Deployment?", "back": "Deklarativ uppdatering av Pods och ReplicaSets. Hanterar rollouts, rollbacks och skalning."},
            {"front": "Vad är en Service?", "back": "Abstraherar åtkomst till Pods med stabil IP/DNS. Typer: ClusterIP, NodePort, LoadBalancer."},
            {"front": "Hur listar du pods?", "back": "kubectl get pods - visar pods i default namespace. -n namespace för specifikt namespace."},
            {"front": "Vad är ett Namespace?", "back": "Logisk isolering inom ett kluster. Separerar resurser för olika team, miljöer eller applikationer."},
            {"front": "Vad gör kubectl apply?", "back": "Applicerar konfiguration från YAML-fil. Skapar eller uppdaterar resurser deklarativt."},
            {"front": "Vad är kubelet?", "back": "Agent som körs på varje node. Säkerställer att containers körs i pods enligt specifikationen."},
            {"front": "Vad är kube-proxy?", "back": "Nätverkskomponent på varje node. Hanterar nätverksregler och service-routing."},
            {"front": "Hur beskriver du en resurs?", "back": "kubectl describe pod podname - visar detaljerad info, events och status."},
            {"front": "Vad är ett ReplicaSet?", "back": "Säkerställer att ett specificerat antal pod-replikor körs. Används oftast via Deployment."},
            {"front": "Hur tar du bort en pod?", "back": "kubectl delete pod podname. Pod återskapas om den styrs av Deployment/ReplicaSet."},
            {"front": "Vad är kubectl get all?", "back": "Listar vanliga resurser: pods, services, deployments, replicasets i aktuellt namespace."},
            {"front": "Vad är container port?", "back": "Porten som applikationen lyssnar på inuti containern. Definieras i pod spec."},
            {"front": "Hur ser du loggar?", "back": "kubectl logs podname - visar container stdout/stderr. -f för att följa i realtid."},
            {"front": "Vad är kubectl exec?", "back": "Kör kommando i en container. kubectl exec -it podname -- bash öppnar shell."},
            {"front": "Vad är Control Plane?", "back": "Master-komponenter: API Server, etcd, Scheduler, Controller Manager. Hanterar klustret."},
            {"front": "Vad är etcd?", "back": "Distribuerad key-value databas. Lagrar all kluster-data och konfiguration."},
            {"front": "Hur skalar du ett deployment?", "back": "kubectl scale deployment name --replicas=3 eller ändra replicas i YAML."},
            {"front": "Vad är ClusterIP service?", "back": "Standard service-typ. Intern IP som bara är nåbar inom klustret."},
            {"front": "Vad är NodePort service?", "back": "Exponerar service på en port på alla nodes. Åtkomlig utifrån på NodeIP:NodePort."},
            {"front": "Vad är LoadBalancer service?", "back": "Skapar extern load balancer (i molnet). Ger publik IP för extern åtkomst."},
            {"front": "Hur kör du pod från image direkt?", "back": "kubectl run podname --image=nginx - snabbt sätt att starta pod utan YAML."},
            {"front": "Vad är ett Label?", "back": "Key-value par som taggar resurser. Används för att organisera och välja resurser."},
            {"front": "Vad är en Selector?", "back": "Väljer resurser baserat på labels. matchLabels: app: nginx väljer pods med den labeln."},
            {"front": "Hur kontrollerar du klusterstatus?", "back": "kubectl cluster-info visar API-server och DNS. kubectl get nodes visar node-status."},
            {"front": "Vad gör kubectl create?", "back": "Skapar resurs imperativt. kubectl create deployment name --image=nginx"},
            {"front": "Hur exporterar du resurs till YAML?", "back": "kubectl get pod name -o yaml > pod.yaml - sparar nuvarande konfiguration."},
        ],
        "medium": [
            {"front": "Vad är en ConfigMap?", "back": "Lagrar icke-känslig konfiguration som key-value. Kan monteras som fil eller miljövariabler i pods."},
            {"front": "Vad är en Secret?", "back": "Lagrar känslig data (lösenord, tokens) base64-kodad. Monteras som fil eller env var."},
            {"front": "Hur skapar du ConfigMap från fil?", "back": "kubectl create configmap name --from-file=config.txt eller --from-literal=key=value"},
            {"front": "Vad är en PersistentVolume (PV)?", "back": "Cluster-resurs för lagring. Definierar fysisk lagring som kan användas av pods."},
            {"front": "Vad är PersistentVolumeClaim (PVC)?", "back": "Begäran om lagring från användare. Binder till lämplig PV automatiskt."},
            {"front": "Vad är StorageClass?", "back": "Definierar typer av lagring. Möjliggör dynamisk provisioning av volymer."},
            {"front": "Vad är en Ingress?", "back": "Hanterar extern HTTP/HTTPS-åtkomst till services. Routing baserat på host/path."},
            {"front": "Vad är Ingress Controller?", "back": "Implementerar Ingress-regler. Exempel: nginx-ingress, traefik, HAProxy."},
            {"front": "Vad gör Rolling Update?", "back": "Uppdaterar pods gradvis utan downtime. Nya pods startas innan gamla tas bort."},
            {"front": "Hur rullar du tillbaka deployment?", "back": "kubectl rollout undo deployment name. --to-revision=N för specifik version."},
            {"front": "Vad är liveness probe?", "back": "Kontrollerar om container lever. Startar om containern om probe misslyckas."},
            {"front": "Vad är readiness probe?", "back": "Kontrollerar om container är redo för trafik. Tar bort från service om den misslyckas."},
            {"front": "Vad är startup probe?", "back": "Kontrollerar uppstart. Inaktiverar liveness/readiness tills startup lyckas."},
            {"front": "Vad är Resource Requests?", "back": "Garanterade resurser för container. Scheduler använder för placering."},
            {"front": "Vad är Resource Limits?", "back": "Max resurser container kan använda. Throttling vid CPU-limit, OOMKill vid minneslimit."},
            {"front": "Vad är DaemonSet?", "back": "Kör en pod på varje node. Används för logs, monitoring, nätverksplugins."},
            {"front": "Vad är StatefulSet?", "back": "För stateful applikationer. Garanterar ordning, stabila nätverksnamn och persistent storage."},
            {"front": "Vad är ett Job?", "back": "Kör tasks till completion. Startar om vid fel tills det lyckas."},
            {"front": "Vad är CronJob?", "back": "Schemalägger Jobs. Cron-syntax för regelbundna körningar."},
            {"front": "Vad är Horizontal Pod Autoscaler?", "back": "Skalar automatiskt baserat på CPU/minne eller custom metrics."},
            {"front": "Vad är Network Policy?", "back": "Definierar nätverksregler för pods. Ingress/egress trafikkontroll."},
            {"front": "Vad är RBAC?", "back": "Role-Based Access Control. Roles, ClusterRoles, RoleBindings för behörigheter."},
            {"front": "Vad är ServiceAccount?", "back": "Identitet för pods. Används för API-åtkomst och RBAC-bindningar."},
            {"front": "Hur debuggar du pod som inte startar?", "back": "kubectl describe pod, kubectl logs, kubectl get events. Kolla status och events."},
            {"front": "Vad är Init Container?", "back": "Körs före app-container. Används för setup, dependencies, migrations."},
            {"front": "Vad är Sidecar Container?", "back": "Extra container i pod. Hanterar logging, proxy, service mesh."},
            {"front": "Vad är Pod Disruption Budget?", "back": "Garanterar minimum antal pods vid disruption. Skyddar mot för aggressiva ändringar."},
            {"front": "Vad är Taints och Tolerations?", "back": "Taints markerar nodes som 'oönskade'. Tolerations låter pods köras på taintade nodes."},
            {"front": "Vad är Node Affinity?", "back": "Regler för pod-placering baserat på node-labels. Soft (preferred) eller hard (required)."},
            {"front": "Vad är Pod Affinity/Anti-Affinity?", "back": "Placerar pods nära eller borta från varandra baserat på labels."},
        ],
        "hard": [
            {"front": "Hur fungerar kube-scheduler?", "back": "Filtrerar nodes (constraints), poängsätter (affinity, resources), väljer bästa node för pod."},
            {"front": "Vad är Custom Resource Definition (CRD)?", "back": "Utökar K8s API med egna resurstyper. Grund för operators och custom controllers."},
            {"front": "Vad är en Operator?", "back": "Custom controller som hanterar komplex applikationslogik. Automatiserar drift av stateful apps."},
            {"front": "Hur fungerar etcd consensus?", "back": "Raft consensus protokoll. Leader election, log replication. Kräver quorum för skriv."},
            {"front": "Vad är Controller Manager?", "back": "Kör controllers: Node, ReplicaSet, Endpoint, ServiceAccount. Reconciliation loops."},
            {"front": "Vad är Admission Controllers?", "back": "Interceptar API-requests. Validating och Mutating. Kan godkänna, avvisa, modifiera."},
            {"front": "Hur fungerar kubelet CRI?", "back": "Container Runtime Interface. Abstraktion för container runtime (containerd, CRI-O)."},
            {"front": "Vad är CNI?", "back": "Container Network Interface. Plugin-standard för pod-nätverk. Calico, Cilium, Flannel."},
            {"front": "Vad är CSI?", "back": "Container Storage Interface. Standard för storage-plugins. Dynamisk provisioning."},
            {"front": "Hur fungerar Service discovery?", "back": "CoreDNS skapar DNS för services. servicename.namespace.svc.cluster.local"},
            {"front": "Vad är Endpoints?", "back": "Lista av pod IPs bakom en Service. Uppdateras automatiskt när pods ändras."},
            {"front": "Hur fungerar kube-proxy iptables mode?", "back": "Skapar iptables-regler för service IP. Random distribution till pod endpoints."},
            {"front": "Vad är IPVS mode?", "back": "Alternativ till iptables. Bättre skalbarhet, fler load balancing-algoritmer."},
            {"front": "Vad är Pod Security Standards?", "back": "Ersätter PodSecurityPolicy. Privileged, Baseline, Restricted. Enforce, Audit, Warn."},
            {"front": "Hur fungerar HPA?", "back": "Metrics Server samlar CPU/minne. HPA jämför med target, justerar replicas."},
            {"front": "Vad är Cluster Autoscaler?", "back": "Skalar nodes automatiskt. Lägger till vid pending pods, tar bort underutnyttjade."},
            {"front": "Vad är Vertical Pod Autoscaler?", "back": "Justerar requests/limits baserat på historisk användning. Kan kräva pod restart."},
            {"front": "Hur säkrar du etcd?", "back": "TLS för client/peer kommunikation. Kryptering av data at rest. RBAC."},
            {"front": "Vad är API Server aggregation?", "back": "Möjliggör custom API servers bakom huvud-API. APIService för registrering."},
            {"front": "Hur fungerar Garbage Collection?", "back": "Owner references spårar beroenden. Cascade delete tar bort dependents."},
            {"front": "Vad är finalizers?", "back": "Blockerar deletion tills cleanup är klar. Controller tar bort finalizer när färdig."},
            {"front": "Hur fungerar leader election?", "back": "Controllers använder lease objects för att välja aktiv leader. Förhindrar race conditions."},
            {"front": "Vad är PriorityClass?", "back": "Sätter pod-prioritet. Högre prioritet kan preempta (avbryta) lägre prioritet."},
            {"front": "Hur fungerar Topology Spread Constraints?", "back": "Sprider pods jämnt över failure domains. maxSkew, topologyKey."},
            {"front": "Vad är RuntimeClass?", "back": "Väljer container runtime per pod. gVisor, Kata Containers för extra isolering."},
            {"front": "Hur fungerar cert-manager?", "back": "Automatiserar TLS-certifikat. Issuers för Let's Encrypt, Vault. Certificate CRD."},
            {"front": "Vad är Service Mesh?", "back": "Istio, Linkerd. Sidecar proxy för mTLS, traffic management, observability."},
            {"front": "Hur fungerar GitOps med Flux/ArgoCD?", "back": "Git som source of truth. Kontinuerlig synkronisering av kluster-state."},
            {"front": "Vad är Kustomize?", "back": "Templating utan templates. Overlays för miljöer. Inbyggt i kubectl."},
            {"front": "Hur debuggar du nätverksproblem?", "back": "kubectl exec netshoot. tcpdump, netstat. Kolla NetworkPolicies, DNS, Service endpoints."},
        ],
    },

    "quiz": {
        "easy": [
            {"question": "Vad är den minsta deployningsbara enheten i Kubernetes?", "options": ["Container", "Pod", "Node", "Deployment"], "correct": 1, "explanation": "Pod är minsta enheten. Den kan innehålla en eller flera containers."},
            {"question": "Vilket kommando listar alla pods?", "options": ["kubectl list pods", "kubectl get pods", "kubectl show pods", "kubectl pods list"], "correct": 1, "explanation": "kubectl get pods listar pods. Lägg till -A för alla namespaces."},
            {"question": "Vad gör en Service i Kubernetes?", "options": ["Kör containers", "Ger stabil åtkomst till pods", "Lagrar data", "Schemalägger pods"], "correct": 1, "explanation": "Service ger stabil IP/DNS för att nå pods, även när de byts ut."},
            {"question": "Vad är ett Namespace?", "options": ["En typ av pod", "Logisk isolering i klustret", "En nätverksport", "En container"], "correct": 1, "explanation": "Namespace separerar resurser logiskt inom ett kluster."},
            {"question": "Vilket kommando applicerar YAML-konfiguration?", "options": ["kubectl run", "kubectl apply -f", "kubectl create yaml", "kubectl config"], "correct": 1, "explanation": "kubectl apply -f fil.yaml applicerar konfiguration deklarativt."},
            {"question": "Vad gör kubelet?", "options": ["API-kommunikation", "Kör pods på noden", "DNS-resolution", "Nätverksregler"], "correct": 1, "explanation": "Kubelet är agenten på varje node som säkerställer att pods körs."},
            {"question": "Hur ser du loggar för en pod?", "options": ["kubectl get logs", "kubectl logs podname", "kubectl show logs", "kubectl log podname"], "correct": 1, "explanation": "kubectl logs podname visar container stdout/stderr."},
            {"question": "Vad är etcd?", "options": ["Container runtime", "Nätverkskomponent", "Distribuerad databas", "Schemaläggare"], "correct": 2, "explanation": "etcd lagrar all klusterdata och konfiguration."},
            {"question": "Vad är ClusterIP?", "options": ["Publik IP", "Intern service-IP", "Node IP", "Pod IP"], "correct": 1, "explanation": "ClusterIP är standard service-typ, endast nåbar inom klustret."},
            {"question": "Hur skalar du till 5 replikor?", "options": ["kubectl replicas 5", "kubectl scale --replicas=5", "kubectl set replicas 5", "kubectl resize 5"], "correct": 1, "explanation": "kubectl scale deployment name --replicas=5 justerar antal pods."},
            {"question": "Vad är en Label?", "options": ["Namespace", "Key-value tagg", "Container", "Volume"], "correct": 1, "explanation": "Labels är key-value par för att organisera och välja resurser."},
            {"question": "Vad gör kubectl describe?", "options": ["Skapar resurs", "Visar detaljerad info", "Tar bort resurs", "Uppdaterar resurs"], "correct": 1, "explanation": "describe visar detaljerad status, events och konfiguration."},
            {"question": "Vad är NodePort service?", "options": ["Intern port", "Exponerar på alla nodes", "Lastbalanserare", "Pod port"], "correct": 1, "explanation": "NodePort öppnar en port på alla nodes för extern åtkomst."},
            {"question": "Hur kommer du in i container med shell?", "options": ["kubectl shell pod", "kubectl exec -it pod -- bash", "kubectl connect pod", "kubectl ssh pod"], "correct": 1, "explanation": "kubectl exec -it podname -- bash öppnar interaktiv shell."},
            {"question": "Vad är ett ReplicaSet?", "options": ["Nätverkskonfiguration", "Säkerställer antal pods", "Volymhanterare", "Service mesh"], "correct": 1, "explanation": "ReplicaSet garanterar att specificerat antal pod-kopior körs."},
            {"question": "Vad är Control Plane?", "options": ["Worker nodes", "Master-komponenter", "Container runtime", "Nätverk"], "correct": 1, "explanation": "Control Plane = API Server, etcd, Scheduler, Controller Manager."},
            {"question": "Hur exporterar du pod-config till YAML?", "options": ["kubectl export", "kubectl get pod -o yaml", "kubectl yaml pod", "kubectl dump pod"], "correct": 1, "explanation": "-o yaml output formaterar resursen som YAML."},
            {"question": "Vad gör LoadBalancer service?", "options": ["Intern lastbalansering", "Skapar extern LB med publik IP", "DNS-balansering", "Pod-balansering"], "correct": 1, "explanation": "LoadBalancer skapar extern lastbalanserare i molnmiljöer."},
            {"question": "Hur kontrollerar du klusterstatus?", "options": ["kubectl status", "kubectl cluster-info", "kubectl health", "kubectl check"], "correct": 1, "explanation": "kubectl cluster-info visar master och DNS-adresser."},
            {"question": "Vad är kube-proxy?", "options": ["API proxy", "Nätverksregler på nodes", "Container proxy", "Storage proxy"], "correct": 1, "explanation": "kube-proxy hanterar nätverksregler för service-routing."},
        ],
        "medium": [
            {"question": "Vad är skillnaden mellan ConfigMap och Secret?", "options": ["Ingen skillnad", "Secret är base64-kodad för känslig data", "ConfigMap är krypterad", "Secret lagras externt"], "correct": 1, "explanation": "Secrets är avsedda för känslig data och base64-kodas."},
            {"question": "Vad gör liveness probe?", "options": ["Kontrollerar om pod är redo", "Startar om container om den kraschar", "Mäter prestanda", "Loggar hälsostatus"], "correct": 1, "explanation": "Liveness probe startar om container om den inte svarar."},
            {"question": "Hur rullar du tillbaka en deployment?", "options": ["kubectl revert", "kubectl rollout undo", "kubectl rollback", "kubectl restore"], "correct": 1, "explanation": "kubectl rollout undo deployment name återgår till förra versionen."},
            {"question": "Vad är Resource Limits?", "options": ["Garanterade resurser", "Max resurser container kan använda", "Klusterresurser", "Nätverksbegränsningar"], "correct": 1, "explanation": "Limits sätter tak. CPU throttlas, minne OOMKillas vid överskridning."},
            {"question": "Vad är DaemonSet?", "options": ["Kör pod på varje node", "Schemalagd körning", "Stateful pods", "Batch-jobb"], "correct": 0, "explanation": "DaemonSet säkerställer att en pod körs på varje (eller utvalda) nodes."},
            {"question": "Vad gör Ingress?", "options": ["Intern kommunikation", "HTTP/HTTPS routing till services", "DNS-hantering", "Load balancing"], "correct": 1, "explanation": "Ingress hanterar extern HTTP-trafik med host/path-baserad routing."},
            {"question": "Vad är readiness probe?", "options": ["Testar om container lever", "Kontrollerar om den är redo för trafik", "Mäter latens", "Validerar config"], "correct": 1, "explanation": "Readiness avgör om pod ska få trafik via Service."},
            {"question": "Vad är StatefulSet?", "options": ["Stateless pods", "Ordnad deployment med stabil identitet", "Batch processing", "Cron-jobb"], "correct": 1, "explanation": "StatefulSet ger ordning, stabila namn och persistent storage."},
            {"question": "Vad gör PersistentVolumeClaim?", "options": ["Skapar fysisk disk", "Begär lagring från klustret", "Monterar NFS", "Backupar data"], "correct": 1, "explanation": "PVC är användarens begäran om lagring som binds till en PV."},
            {"question": "Hur aktiverar du autoskalning?", "options": ["kubectl autoscale", "kubectl scale auto", "kubectl hpa create", "Både A och C"], "correct": 0, "explanation": "kubectl autoscale deployment name --min=2 --max=10 --cpu-percent=50"},
            {"question": "Vad är Init Container?", "options": ["Huvud-container", "Körs före app-container", "Sidecar", "Debug-container"], "correct": 1, "explanation": "Init containers körs sekventiellt före app-containers."},
            {"question": "Vad gör Network Policy?", "options": ["Konfigurerar DNS", "Kontrollerar pod-trafik", "Sätter bandwidth", "Definierar services"], "correct": 1, "explanation": "NetworkPolicy definierar ingress/egress-regler för pods."},
            {"question": "Vad är RBAC?", "options": ["Nätverksprotokoll", "Role-Based Access Control", "Resource Balancing", "Runtime Config"], "correct": 1, "explanation": "RBAC styr behörigheter med Roles och RoleBindings."},
            {"question": "Vad gör CronJob?", "options": ["Kör en gång", "Schemalägger återkommande jobb", "Kontinuerlig körning", "On-demand körning"], "correct": 1, "explanation": "CronJob kör Jobs enligt cron-schema."},
            {"question": "Vad är ServiceAccount?", "options": ["Användarkonto", "Pod-identitet för API-åtkomst", "Service login", "Cluster admin"], "correct": 1, "explanation": "ServiceAccount ger pods identitet för RBAC och API-access."},
            {"question": "Hur debuggar du ImagePullBackOff?", "options": ["Kolla CPU", "Verifiera image och credentials", "Skala ner", "Byt namespace"], "correct": 1, "explanation": "ImagePullBackOff = kan ej ladda image. Kolla namn, tag, registry auth."},
            {"question": "Vad gör Taints på nodes?", "options": ["Markerar för special-pods", "Markerar nodes som oönskade", "Ökar prioritet", "Aktiverar GPU"], "correct": 1, "explanation": "Taints avvisar pods såvida de inte har matchande Tolerations."},
            {"question": "Vad är StorageClass?", "options": ["Volym-typ", "Definierar lagringsprofiler", "Backup-policy", "Disk quota"], "correct": 1, "explanation": "StorageClass möjliggör dynamisk provisioning med olika lagringstyper."},
            {"question": "Vad gör Pod Disruption Budget?", "options": ["Begränsar CPU", "Garanterar minimum pods vid disruption", "Sätter prioritet", "Backup-schema"], "correct": 1, "explanation": "PDB skyddar mot för många samtida pod-avbrott."},
            {"question": "Hur monterar du Secret som fil?", "options": ["env valueFrom", "volumeMounts med secretName", "secretRef", "configMapKeyRef"], "correct": 1, "explanation": "Secrets kan monteras som volymer där varje key blir en fil."},
        ],
        "hard": [
            {"question": "Hur fungerar kube-scheduler filtering?", "options": ["Slumpmässigt val", "Filtrerar på constraints, poängsätter resterande", "Round-robin", "Baserat på node-namn"], "correct": 1, "explanation": "Scheduler filtrerar nodes med constraints, poängsätter baserat på prioriteter."},
            {"question": "Vad är CRD?", "options": ["Container Runtime Definition", "Custom Resource Definition", "Cluster Role Definition", "Config Resource Data"], "correct": 1, "explanation": "CRD utökar K8s API med egna resurstyper för operators."},
            {"question": "Hur fungerar etcd Raft consensus?", "options": ["Master election", "Leader election med quorum för skriv", "Round-robin", "Eventual consistency"], "correct": 1, "explanation": "Raft väljer leader, kräver majoritet (quorum) för att committa."},
            {"question": "Vad gör Admission Controller?", "options": ["Hanterar authentication", "Interceptar och modifierar API-requests", "Schemaläggning", "Nätverksfilter"], "correct": 1, "explanation": "Admission controllers validerar/muterar requests före persistering."},
            {"question": "Vad är CNI?", "options": ["Container Node Interface", "Container Network Interface", "Cluster Network Integration", "Core Network Infrastructure"], "correct": 1, "explanation": "CNI är standard för nätverksplugins som Calico, Cilium."},
            {"question": "Hur fungerar Service discovery DNS?", "options": ["External DNS", "CoreDNS skapar servicename.namespace.svc.cluster.local", "mDNS", "Consul"], "correct": 1, "explanation": "CoreDNS ger automatisk DNS för services i formatet service.namespace.svc.cluster.local."},
            {"question": "Vad är kube-proxy IPVS mode?", "options": ["IP Virtual Server för bättre skalbarhet", "IP Version Service", "Internal VPN Service", "IP Verification System"], "correct": 0, "explanation": "IPVS erbjuder bättre prestanda och fler load balancing-algoritmer än iptables."},
            {"question": "Vad är Pod Security Standards?", "options": ["SSL-konfiguration", "Privileged/Baseline/Restricted policies", "Network policies", "RBAC regler"], "correct": 1, "explanation": "PSS definierar säkerhetsnivåer: Privileged (inga restriktioner), Baseline (minimal), Restricted (hård)."},
            {"question": "Hur fungerar HPA metrics?", "options": ["Direkt från kubelet", "Metrics Server samlar, HPA jämför med target", "Prometheus", "etcd queries"], "correct": 1, "explanation": "Metrics Server aggregerar data. HPA kontrollerar och justerar replicas."},
            {"question": "Vad gör Vertical Pod Autoscaler?", "options": ["Skalar antal pods", "Justerar requests/limits baserat på användning", "Skalar nodes", "Justerar namespace quotas"], "correct": 1, "explanation": "VPA rekommenderar eller ändrar resource requests/limits."},
            {"question": "Vad är API Server aggregation?", "options": ["Load balancing av API", "Custom API servers bakom huvud-API", "Request batching", "Caching"], "correct": 1, "explanation": "Aggregation layer möjliggör att registrera custom API servers."},
            {"question": "Hur fungerar finalizers?", "options": ["Cleanup scripts", "Blockerar deletion tills controller tar bort dem", "Avslutningsloggar", "Graceful shutdown"], "correct": 1, "explanation": "Finalizers förhindrar deletion tills cleanup är komplett."},
            {"question": "Vad är PriorityClass?", "options": ["Nätverksprioritet", "Pod-prioritet för preemption", "Storage I/O prioritet", "CPU scheduling"], "correct": 1, "explanation": "PriorityClass sätter podprioritet. Högre kan avbryta lägre vid resursbrist."},
            {"question": "Vad gör RuntimeClass?", "options": ["Väljer K8s version", "Väljer container runtime per pod", "Definierar resource limits", "Sätter namespace"], "correct": 1, "explanation": "RuntimeClass möjliggör val av runtime (containerd, gVisor, Kata)."},
            {"question": "Hur hanterar cert-manager certifikat?", "options": ["Manuell import", "Automatisk issuance via Issuers och Certificate CRD", "Extern CA", "Self-signed endast"], "correct": 1, "explanation": "cert-manager automatiserar via Issuers (Let's Encrypt, Vault) och Certificate resurser."},
            {"question": "Vad är Service Mesh sidecar?", "options": ["Extra node", "Proxy container i varje pod", "Extern lastbalanserare", "DNS server"], "correct": 1, "explanation": "Sidecars (Envoy i Istio) hanterar mTLS, traffic management per pod."},
            {"question": "Hur fungerar Kustomize overlays?", "options": ["Docker layers", "Base + miljöspecifika patches", "Helm charts", "ConfigMap inheritance"], "correct": 1, "explanation": "Kustomize använder base och overlays för att patcha config per miljö."},
            {"question": "Vad är Topology Spread Constraints?", "options": ["Nätverkstopologi", "Sprider pods jämnt över failure domains", "Node labeling", "Rack awareness"], "correct": 1, "explanation": "Topology Spread säkerställer pods är jämnt fördelade över zoner/nodes."},
            {"question": "Hur debuggar du DNS-problem i pod?", "options": ["kubectl logs kube-dns", "nslookup från pod + kolla CoreDNS", "Restart kubelet", "Kolla etcd"], "correct": 1, "explanation": "Kör nslookup/dig i pod, verifiera CoreDNS pods och config."},
            {"question": "Vad gör leader election för controllers?", "options": ["Väljer master node", "Endast en controller-instans är aktiv", "Load balancing", "Failover"], "correct": 1, "explanation": "Leader election säkerställer att bara en replica kör reconciliation."},
        ],
    },

    "nodes": [
        {"id": 1, "title": "Kubernetes Introduktion", "slug": "kubernetes-intro"},
        {"id": 2, "title": "Klusterarkitektur", "slug": "cluster-architecture"},
        {"id": 3, "title": "Pods Grunderna", "slug": "pods-basics"},
        {"id": 4, "title": "Deployments", "slug": "deployments"},
        {"id": 5, "title": "Services", "slug": "services"},
        {"id": 6, "title": "Namespaces & Labels", "slug": "namespaces-labels"},
        {"id": 7, "title": "ConfigMaps & Secrets", "slug": "configmaps-secrets"},
        {"id": 8, "title": "Persistent Storage", "slug": "persistent-storage"},
        {"id": 9, "title": "Health Checks", "slug": "health-checks"},
        {"id": 10, "title": "Resource Management", "slug": "resource-management"},
        {"id": 11, "title": "Networking Djupdykning", "slug": "networking-deep"},
        {"id": 12, "title": "Ingress Controllers", "slug": "ingress-controllers"},
        {"id": 13, "title": "Workload Types", "slug": "workload-types"},
        {"id": 14, "title": "Autoscaling", "slug": "autoscaling"},
        {"id": 15, "title": "RBAC & Security", "slug": "rbac-security"},
        {"id": 16, "title": "Scheduling Avancerat", "slug": "advanced-scheduling"},
        {"id": 17, "title": "Helm Package Manager", "slug": "helm"},
        {"id": 18, "title": "Observability", "slug": "observability"},
        {"id": 19, "title": "Operators & CRDs", "slug": "operators-crds"},
        {"id": 20, "title": "Production Best Practices", "slug": "production-practices"},
    ],
}
