"""
Terraform Mastery - Study Data
==============================

90 Flashcards (30 easy, 30 medium, 30 hard)
60 Quiz Questions (20 easy, 20 medium, 20 hard)
"""

TERRAFORM_STUDY_DATA = {
    "module_slug": "terraform-mastery",
    "module_title": "Terraform",
    "module_description": "Infrastructure as Code med Terraform",
    "icon": "Cloud",

    "flashcards": {
        "easy": [
            {"front": "Vad är Terraform?", "back": "Infrastructure as Code verktyg från HashiCorp. Deklarativ syntax för att skapa och hantera molnresurser."},
            {"front": "Vad är HCL?", "back": "HashiCorp Configuration Language - syntaxen som Terraform använder för att definiera infrastruktur."},
            {"front": "Vad gör terraform init?", "back": "Initierar arbetskatalog, laddar ner providers och moduler, sätter upp backend."},
            {"front": "Vad gör terraform plan?", "back": "Visar vad Terraform kommer göra utan att utföra ändringar. Jämför desired vs current state."},
            {"front": "Vad gör terraform apply?", "back": "Skapar eller uppdaterar infrastruktur enligt konfigurationen. Frågar om bekräftelse."},
            {"front": "Vad gör terraform destroy?", "back": "Tar bort all infrastruktur som Terraform hanterar. Frågar om bekräftelse."},
            {"front": "Vad är en resource i Terraform?", "back": "Ett infrastrukturobjekt: EC2, S3 bucket, VPC, etc. resource 'aws_instance' 'name' {}"},
            {"front": "Vad är en provider?", "back": "Plugin som interagerar med ett API (AWS, Azure, GCP). Måste deklareras och konfigureras."},
            {"front": "Hur deklarerar du AWS provider?", "back": "provider 'aws' { region = 'eu-north-1' } - konfigurerar AWS provider."},
            {"front": "Vad är terraform.tfstate?", "back": "State-fil som lagrar nuvarande infrastrukturens tillstånd. Används för att jämföra ändringar."},
            {"front": "Vad är en variabel i Terraform?", "back": "Parametrar som gör konfiguration återanvändbar. variable 'name' { default = 'value' }"},
            {"front": "Hur refererar du till variabel?", "back": "var.variabelnamn - t.ex. var.region eller var.instance_type"},
            {"front": "Vad är output i Terraform?", "back": "Värden som visas efter apply. output 'ip' { value = aws_instance.web.public_ip }"},
            {"front": "Hur kommenterar du i HCL?", "back": "# single line eller /* multi line */ kommentarer."},
            {"front": "Vad är data source?", "back": "Hämtar information om existerande resurser. data 'aws_ami' 'ubuntu' {}"},
            {"front": "Skillnad mellan resource och data?", "back": "Resource skapar/hanterar. Data source läser endast existerande resurser."},
            {"front": "Vad gör terraform fmt?", "back": "Formaterar .tf filer enligt standard stil. Gör koden konsistent."},
            {"front": "Vad gör terraform validate?", "back": "Validerar syntax och konfiguration utan att kontakta providers."},
            {"front": "Hur sätter du variabel via CLI?", "back": "-var 'name=value' eller -var-file='vars.tfvars'"},
            {"front": "Vad är .tfvars fil?", "back": "Fil med variabelvärden. terraform.tfvars laddas automatiskt."},
            {"front": "Vad är locals i Terraform?", "back": "Lokala beräknade värden. locals { name = '${var.prefix}-app' }"},
            {"front": "Hur refererar du till local?", "back": "local.namn - t.ex. local.common_tags"},
            {"front": "Vad gör count i resource?", "back": "Skapar flera instanser av samma resource. count = 3 skapar 3 st."},
            {"front": "Hur refererar du till count index?", "back": "count.index - 0, 1, 2, etc. Användbart för namngivning."},
            {"front": "Vad är en Terraform modul?", "back": "Återanvändbar samling av resurser. Antingen lokal katalog eller från registry."},
            {"front": "Hur använder du en modul?", "back": "module 'name' { source = './modules/vpc' variables... }"},
            {"front": "Vad är Terraform Registry?", "back": "Officiellt bibliotek med providers och moduler. registry.terraform.io"},
            {"front": "Hur ser du resource-attribut?", "back": "terraform state show resource_address - visar alla attribut."},
            {"front": "Vad gör terraform refresh?", "back": "Uppdaterar state med verklig infrastruktur. Inbyggt i plan/apply sedan 0.15."},
            {"front": "Hur importerar du existerande resurs?", "back": "terraform import aws_instance.web i-1234567890 - lägger till i state."},
        ],
        "medium": [
            {"front": "Vad är for_each i Terraform?", "back": "Itererar över map/set för att skapa resurser. for_each = toset(['a','b'])"},
            {"front": "Skillnad mellan count och for_each?", "back": "count använder index. for_each använder keys/values, bättre för dynamiska sets."},
            {"front": "Hur refererar du till for_each?", "back": "each.key och each.value - t.ex. name = each.key"},
            {"front": "Vad är dynamic block?", "back": "Genererar upprepade nested blocks dynamiskt. dynamic 'ingress' { for_each = var.ports }"},
            {"front": "Vad är depends_on?", "back": "Explicit beroende mellan resurser. depends_on = [aws_iam_role.role]"},
            {"front": "Vad är lifecycle block?", "back": "Kontrollerar resurs-livscykel: create_before_destroy, prevent_destroy, ignore_changes."},
            {"front": "Vad gör create_before_destroy?", "back": "Skapar ny resurs innan gammal tas bort. Minskar downtime."},
            {"front": "Vad gör prevent_destroy?", "back": "Förhindrar att resursen tas bort av misstag. Kräver manuell ändring."},
            {"front": "Vad gör ignore_changes?", "back": "Ignorerar ändringar i specifika attribut. ignore_changes = [tags]"},
            {"front": "Vad är remote state?", "back": "State lagrad på remote location (S3, GCS, Terraform Cloud) för team-samarbete."},
            {"front": "Hur konfigurerar du S3 backend?", "back": "backend 's3' { bucket='tfstate' key='prod/state' region='eu-north-1' }"},
            {"front": "Vad är state locking?", "back": "Förhindrar concurrent ändringar. DynamoDB för S3, inbyggt i Terraform Cloud."},
            {"front": "Vad är workspace i Terraform?", "back": "Separata state-instanser för olika miljöer. terraform workspace new prod"},
            {"front": "Hur läser du remote state?", "back": "data 'terraform_remote_state' 'vpc' { backend = 's3' config = {...} }"},
            {"front": "Vad är provisioner?", "back": "Kör scripts på resurser. local-exec, remote-exec. Använd sparsamt!"},
            {"front": "Vad är null_resource?", "back": "Resurs utan infrastruktur. Används för triggers och provisioners."},
            {"front": "Vad gör terraform taint?", "back": "Markerar resurs för omskrivning vid nästa apply. Ersatt av -replace flag."},
            {"front": "Hur tvingar du resurs-omskrivning?", "back": "terraform apply -replace='aws_instance.web' (ersätter taint)"},
            {"front": "Vad är sensitive variabel?", "back": "variable { sensitive = true } döljer värde i output och logs."},
            {"front": "Hur organiserar du stora projekt?", "back": "Separata .tf filer, moduler för återanvändning, environments med workspaces/katalogstruktur."},
            {"front": "Vad är terraform.lock.hcl?", "back": "Låser provider-versioner. Skapas av init, committas till git."},
            {"front": "Hur uppgraderar du providers?", "back": "terraform init -upgrade laddar senaste versioner inom constraints."},
            {"front": "Vad är version constraints?", "back": "version = '~> 4.0' tillåter 4.x men inte 5.0. >= 4.0, < 5.0 explicit."},
            {"front": "Vad gör terraform output?", "back": "Visar output-värden. terraform output ip_address"},
            {"front": "Hur använder du output från modul?", "back": "module.modulnamn.outputnamn - t.ex. module.vpc.vpc_id"},
            {"front": "Vad är required_providers?", "back": "Specificerar providers med source och version i terraform block."},
            {"front": "Vad är alias på provider?", "back": "Flera konfigurationer av samma provider. provider 'aws' { alias = 'west' }"},
            {"front": "Hur använder du provider alias?", "back": "resource 'aws_instance' 'west_server' { provider = aws.west }"},
            {"front": "Vad är moved block?", "back": "Deklarerar att resurs flyttats/döpts om utan att förstöra den."},
            {"front": "Vad gör terraform graph?", "back": "Genererar DOT-format beroendeträd. Visualisera med Graphviz."},
        ],
        "hard": [
            {"front": "Vad är Terraform Cloud/Enterprise?", "back": "SaaS/self-hosted för remote state, remote execution, policy as code, team collaboration."},
            {"front": "Vad är Sentinel i Terraform?", "back": "Policy as Code ramverk. Definierar regler som måste uppfyllas före apply."},
            {"front": "Hur fungerar terraform plan -out?", "back": "Sparar plan till fil. terraform apply planfile applicerar exakt den planen."},
            {"front": "Vad är module versioning?", "back": "Pinnar modulversion: source = 'registry/module' version = '2.0.0'"},
            {"front": "Vad är terraform state mv?", "back": "Flyttar resurs i state. terraform state mv aws_instance.old aws_instance.new"},
            {"front": "Vad gör terraform state rm?", "back": "Tar bort resurs från state (inte från molnet). Användbart vid import-misslyckanden."},
            {"front": "Hur hanterar du secrets i Terraform?", "back": "Använd secret managers (Vault, AWS Secrets), environment variables, eller encrypted state."},
            {"front": "Vad är data source lifecycle?", "back": "postcondition validerar läst data. precondition finns också."},
            {"front": "Hur fungerar replace_triggered_by?", "back": "lifecycle { replace_triggered_by = [null_resource.trigger] } - tvingar omskrivning."},
            {"front": "Vad är terraform import block?", "back": "Deklarativ import i HCL (1.5+). import { to = aws_instance.web id = 'i-123' }"},
            {"front": "Vad är terraform test?", "back": "Inbyggt testramverk (1.6+). Skriver tester i .tftest.hcl filer."},
            {"front": "Hur fungerar conditions i variables?", "back": "validation { condition = length(var.name) > 0 error_message = 'msg' }"},
            {"front": "Vad är precondition/postcondition?", "back": "Resource lifecycle conditions. precondition körs före, postcondition efter."},
            {"front": "Hur hanterar du drift?", "back": "terraform plan detekterar. Antingen apply för att korrigera eller import/state för att matcha."},
            {"front": "Vad är terraform_data resource?", "back": "Ersätter null_resource. Lagrar triggervärden utan extern provider."},
            {"front": "Hur optimerar du stora configurations?", "back": "Parallelism, targeted applies, -refresh=false, modulär struktur."},
            {"front": "Vad gör -target flag?", "back": "terraform apply -target=aws_instance.web applicerar bara specifik resurs."},
            {"front": "Hur hanterar du circular dependencies?", "back": "Refaktorera beroenden, använd depends_on explicit, eller separera i flera applies."},
            {"front": "Vad är override files?", "back": "_override.tf filer mergear med huvudconfig. Användbart för lokala variationer."},
            {"front": "Hur testar du moduler?", "back": "terraform test (native), Terratest (Go), kitchen-terraform, eller manuella sandbox-miljöer."},
            {"front": "Vad är OpenTofu?", "back": "Open-source fork av Terraform efter licensändring. Kompatibelt med Terraform."},
            {"front": "Hur hanterar du multi-region?", "back": "Provider aliases, for_each över regioner, eller separata state per region."},
            {"front": "Vad är terragrunt?", "back": "Wrapper som hanterar DRY config, remote state, dependencies mellan moduler."},
            {"front": "Hur fungerar terraform console?", "back": "Interaktiv REPL för att testa expressions. terraform console"},
            {"front": "Vad är check blocks?", "back": "Continuous validation (1.5+). Assertions som körs vid plan utan att blockera."},
            {"front": "Hur hanterar du provider credentials säkert?", "back": "Environment variables, IAM roles, Vault, eller Terraform Cloud credential management."},
            {"front": "Vad är ephemeral resources?", "back": "Resources som inte sparas i state. Används för temporära värden."},
            {"front": "Hur debuggar du Terraform?", "back": "TF_LOG=DEBUG för verbose output. TF_LOG_PATH sparar till fil."},
            {"front": "Vad är run triggers i TF Cloud?", "back": "Automatiska runs när upstream workspace ändras. Kedjar deploys."},
            {"front": "Hur implementerar du GitOps med Terraform?", "back": "CI/CD pipeline: plan på PR, apply på merge. TF Cloud VCS integration."},
        ],
    },

    "quiz": {
        "easy": [
            {"question": "Vad gör 'terraform init'?", "options": ["Skapar resurser", "Initierar och laddar providers", "Validerar syntax", "Visar plan"], "correct": 1, "explanation": "init laddar ner providers, moduler och sätter upp backend."},
            {"question": "Vad gör 'terraform plan'?", "options": ["Skapar infrastruktur", "Visar vad som kommer ske", "Tar bort resurser", "Validerar syntax"], "correct": 1, "explanation": "plan visar ändringar utan att utföra dem."},
            {"question": "Vad är en provider i Terraform?", "options": ["Molnresurs", "Plugin för API-kommunikation", "Variabel", "State-fil"], "correct": 1, "explanation": "Provider är plugin som interagerar med AWS, Azure, GCP, etc."},
            {"question": "Hur sparar Terraform nuvarande tillstånd?", "options": ["I .tf filer", "I terraform.tfstate", "I molnet", "I minnet"], "correct": 1, "explanation": "tfstate-fil lagrar mappning mellan config och verklig infrastruktur."},
            {"question": "Hur refererar du till variabel?", "options": ["$variable", "variable.name", "var.name", "{variable}"], "correct": 2, "explanation": "var.variabelnamn är syntaxen för att referera till variabler."},
            {"question": "Vad gör 'terraform destroy'?", "options": ["Formaterar kod", "Tar bort all hanterad infrastruktur", "Validerar config", "Importerar resurser"], "correct": 1, "explanation": "destroy tar bort allt som Terraform skapat."},
            {"question": "Hur applicerar du ändringar?", "options": ["terraform run", "terraform apply", "terraform create", "terraform deploy"], "correct": 1, "explanation": "apply skapar/uppdaterar infrastruktur enligt config."},
            {"question": "Vad är HCL?", "options": ["HashiCorp Command Line", "HashiCorp Configuration Language", "High-level Cloud Language", "Hybrid Config Layer"], "correct": 1, "explanation": "HCL är syntax-språket för Terraform-konfiguration."},
            {"question": "Hur formaterar du Terraform-kod?", "options": ["terraform format", "terraform fmt", "terraform style", "terraform lint"], "correct": 1, "explanation": "fmt formaterar .tf filer enligt standard."},
            {"question": "Vad är ett output i Terraform?", "options": ["Loggfil", "Värde som visas efter apply", "Felmeddelande", "Input från användare"], "correct": 1, "explanation": "output definierar värden att visa/exportera efter apply."},
            {"question": "Vad gör 'terraform validate'?", "options": ["Applicerar ändringar", "Validerar syntax och config", "Testar i sandbox", "Kontrollerar state"], "correct": 1, "explanation": "validate kontrollerar syntax utan att kontakta providers."},
            {"question": "Hur skapar du variabel med default?", "options": ["var name = 'val'", "variable 'name' { default = 'val' }", "default name = 'val'", "set name = 'val'"], "correct": 1, "explanation": "variable block med default-attribut definierar variabel."},
            {"question": "Vad är data source?", "options": ["Skapar resurs", "Läser existerande resurs", "Database connection", "API endpoint"], "correct": 1, "explanation": "data source hämtar info om resurser som redan finns."},
            {"question": "Hur anger du provider-region?", "options": ["region: eu-north-1", "region = 'eu-north-1'", "set region eu-north-1", "-region eu-north-1"], "correct": 1, "explanation": "region = 'value' i provider-block anger region."},
            {"question": "Vad gör count = 3?", "options": ["Väntar 3 sekunder", "Skapar 3 instanser", "3 retry försök", "Version 3"], "correct": 1, "explanation": "count skapar flera kopior av samma resurs."},
            {"question": "Vad är Terraform Registry?", "options": ["Lokal cache", "Officiellt bibliotek för providers/moduler", "State storage", "Log repository"], "correct": 1, "explanation": "Registry har providers och moduler att använda."},
            {"question": "Hur importerar du existerande resurs?", "options": ["terraform import", "terraform add", "terraform attach", "terraform load"], "correct": 0, "explanation": "import lägger till existerande resurs i state."},
            {"question": "Vad lagrar .terraform katalogen?", "options": ["State", "Nedladdade providers och moduler", "Loggar", "Backup"], "correct": 1, "explanation": ".terraform innehåller providers och cached moduler."},
            {"question": "Hur sätter du variabel via CLI?", "options": ["--var", "-var 'name=val'", "-set name=val", "--define name=val"], "correct": 1, "explanation": "-var flag sätter variabelvärde vid körning."},
            {"question": "Vad är terraform.tfvars?", "options": ["State fil", "Fil med variabelvärden", "Provider config", "Module definition"], "correct": 1, "explanation": "tfvars innehåller variabelvärden, laddas automatiskt."},
        ],
        "medium": [
            {"question": "Skillnad mellan count och for_each?", "options": ["Samma sak", "count = index, for_each = keys", "for_each är snabbare", "count är nyare"], "correct": 1, "explanation": "count använder index (0,1,2). for_each använder map/set keys."},
            {"question": "Vad gör depends_on?", "options": ["Definierar dependencies", "Explicit beroende mellan resurser", "Dependency injection", "Import dependencies"], "correct": 1, "explanation": "depends_on sätter explicit beroende när implicit inte räcker."},
            {"question": "Vad är remote state?", "options": ["State på disk", "State lagrad i molnet/server", "Remote desktop", "Backup state"], "correct": 1, "explanation": "Remote state möjliggör team-samarbete och locking."},
            {"question": "Hur förhindrar du oavsiktlig borttagning?", "options": ["lock = true", "prevent_destroy = true", "readonly = true", "protected = true"], "correct": 1, "explanation": "lifecycle { prevent_destroy = true } blockerar destroy."},
            {"question": "Vad gör create_before_destroy?", "options": ["Skapar backup", "Skapar ny resurs innan gammal tas bort", "Skapar duplicate", "Testar före destroy"], "correct": 1, "explanation": "Minskar downtime genom att skapa ersättare först."},
            {"question": "Vad är state locking?", "options": ["Krypterar state", "Förhindrar concurrent ändringar", "Låser provider", "Versionskontroll"], "correct": 1, "explanation": "Locking förhindrar att flera kör terraform samtidigt."},
            {"question": "Hur använder du workspace?", "options": ["terraform env", "terraform workspace", "terraform space", "terraform context"], "correct": 1, "explanation": "workspace skapar separata state-instanser per miljö."},
            {"question": "Vad är provisioner?", "options": ["Provider setup", "Scripts som körs på resurser", "Provision cloud", "Setup wizard"], "correct": 1, "explanation": "Provisioners kör scripts efter resurser skapats."},
            {"question": "Vad gör ignore_changes?", "options": ["Ignorerar fel", "Ignorerar ändringar i attribut", "Ignorerar warnings", "Ignorerar dependencies"], "correct": 1, "explanation": "lifecycle { ignore_changes = [tags] } ignorerar extern tagändring."},
            {"question": "Hur refererar du till modul output?", "options": ["module.output", "module.name.output", "output.module", "module->output"], "correct": 1, "explanation": "module.modulnamn.outputnamn ger modulens output."},
            {"question": "Vad är dynamic block?", "options": ["Runtime block", "Genererar nested blocks dynamiskt", "Dynamic typing", "Async block"], "correct": 1, "explanation": "dynamic genererar upprepade block baserat på for_each."},
            {"question": "Hur låser du provider-version?", "options": ["lock.hcl", "terraform.lock.hcl", "version.lock", "provider.lock"], "correct": 1, "explanation": "terraform.lock.hcl låser exakta provider-versioner."},
            {"question": "Vad gör -target flag?", "options": ["Sätter mål-miljö", "Applicerar bara specifik resurs", "Target audience", "Mål-region"], "correct": 1, "explanation": "-target begränsar apply till specifika resurser."},
            {"question": "Vad är locals?", "options": ["Lokala providers", "Lokala beräknade värden", "Local variables", "Båda B och C"], "correct": 3, "explanation": "locals definierar beräknade värden som inte är input."},
            {"question": "Hur läser du annan workspace state?", "options": ["import state", "data terraform_remote_state", "read_state", "state.other"], "correct": 1, "explanation": "terraform_remote_state data source läser annan state."},
            {"question": "Vad är null_resource?", "options": ["Tom resurs", "Resurs för provisioners/triggers", "Null pointer", "Deleted resource"], "correct": 1, "explanation": "null_resource har ingen infra men kan ha provisioners."},
            {"question": "Hur tvingar du omskrivning av resurs?", "options": ["terraform taint", "terraform apply -replace=resource", "terraform recreate", "Båda A och B"], "correct": 3, "explanation": "taint (deprecated) och -replace tvingar nyskrivning."},
            {"question": "Vad är provider alias?", "options": ["Namnändring", "Flera configs av samma provider", "Shortcut", "Import alias"], "correct": 1, "explanation": "alias möjliggör t.ex. aws provider för olika regioner."},
            {"question": "Vad gör terraform graph?", "options": ["Visar metrics", "Genererar beroendeträd", "Graph database", "Visual editor"], "correct": 1, "explanation": "graph skapar DOT-format av resursberoenden."},
            {"question": "Hur validerar du variabelvärde?", "options": ["validate block", "validation block i variable", "check block", "assert block"], "correct": 1, "explanation": "validation block med condition och error_message."},
        ],
        "hard": [
            {"question": "Vad är Sentinel?", "options": ["Security scan", "Policy as Code framework", "Secret management", "Monitoring"], "correct": 1, "explanation": "Sentinel definierar policies som körs före apply i TF Cloud/Enterprise."},
            {"question": "Hur sparar du plan för senare apply?", "options": ["terraform plan -save", "terraform plan -out=file", "terraform export", "terraform cache"], "correct": 1, "explanation": "-out sparar plan som kan appliceras exakt senare."},
            {"question": "Vad är terraform state mv?", "options": ["Flyttar state-fil", "Flyttar resurs i state", "Move to cloud", "Version move"], "correct": 1, "explanation": "state mv ändrar resursadress i state utan att ändra infrastruktur."},
            {"question": "Vad gör postcondition?", "options": ["Pre-deploy check", "Validerar resurs efter skapande", "Post-script", "Cleanup"], "correct": 1, "explanation": "postcondition validerar resursattribut efter create/update."},
            {"question": "Vad är terraform import block (1.5+)?", "options": ["Import script", "Deklarativ import i HCL", "Import module", "State import"], "correct": 1, "explanation": "import block ersätter CLI import med deklarativ syntax."},
            {"question": "Hur testar du moduler native (1.6+)?", "options": ["terraform test", "terraform validate --test", "terraform check", "terraform spec"], "correct": 0, "explanation": "terraform test kör .tftest.hcl testfiler."},
            {"question": "Vad är check block?", "options": ["Syntax check", "Continuous validation utan blockering", "Health check", "Security check"], "correct": 1, "explanation": "check blocks validerar men blockerar inte apply."},
            {"question": "Vad är replace_triggered_by?", "options": ["Replace provider", "Tvingar omskrivning vid trigger-ändring", "Trigger webhook", "Replace all"], "correct": 1, "explanation": "lifecycle { replace_triggered_by } tvingar omskrivning."},
            {"question": "Hur hanterar du secrets säkert?", "options": ["I .tf filer", "Environment vars eller secret manager", "I tfvars", "I comments"], "correct": 1, "explanation": "Aldrig hårdkoda secrets. Använd env vars, Vault, etc."},
            {"question": "Vad är ephemeral resources?", "options": ["Temporary instances", "Resources som inte sparas i state", "Short-lived VMs", "Cache resources"], "correct": 1, "explanation": "Ephemeral resources existerar bara under plan/apply."},
            {"question": "Hur debuggar du Terraform?", "options": ["terraform debug", "TF_LOG=DEBUG", "terraform --verbose", "terraform -v"], "correct": 1, "explanation": "TF_LOG environment variable aktiverar debug logging."},
            {"question": "Vad är moved block?", "options": ["Refactoring deklaration", "Deklarerar resurs-flytt utan destroy", "Move state", "Migration block"], "correct": 1, "explanation": "moved block låter dig byta namn/adress utan att förstöra."},
            {"question": "Vad är terragrunt?", "options": ["Terraform GUI", "Wrapper för DRY config och dependencies", "Testing tool", "State manager"], "correct": 1, "explanation": "Terragrunt hanterar repetitiv config och modul-dependencies."},
            {"question": "Hur fungerar terraform console?", "options": ["Web console", "Interaktiv REPL för expressions", "Cloud console", "Debug console"], "correct": 1, "explanation": "console låter dig testa expressions interaktivt."},
            {"question": "Vad är OpenTofu?", "options": ["Terraform GUI", "Open-source Terraform fork", "Testing framework", "Cloud provider"], "correct": 1, "explanation": "OpenTofu är community fork efter HashiCorp licensändring."},
            {"question": "Hur hanterar du drift?", "options": ["Ignorera", "plan detectar, apply/import fixar", "Manual fix only", "Recreate all"], "correct": 1, "explanation": "plan visar drift, apply korrigerar eller import matchar."},
            {"question": "Vad är run triggers i TF Cloud?", "options": ["CI triggers", "Auto-run vid upstream workspace-ändring", "Manual triggers", "Time triggers"], "correct": 1, "explanation": "Run triggers kedjar workspace-körningar automatiskt."},
            {"question": "Hur implementerar du GitOps?", "options": ["Manual apply", "CI/CD: plan på PR, apply på merge", "Git hooks", "Cron jobs"], "correct": 1, "explanation": "GitOps: plan i PR för review, apply vid merge till main."},
            {"question": "Vad är override files?", "options": ["Config backup", "_override.tf filer som mergear", "Override variables", "Module override"], "correct": 1, "explanation": "Override files mergear med huvudconfig för lokala variationer."},
            {"question": "Hur hanterar du multi-region?", "options": ["En state för allt", "Provider aliases eller separata states", "Multi-region module", "Region variable"], "correct": 1, "explanation": "Aliases för en state, separata states för isolation."},
        ],
    },

    "nodes": [
        {"id": 1, "title": "Terraform Introduktion", "slug": "terraform-intro"},
        {"id": 2, "title": "HCL Syntax", "slug": "hcl-syntax"},
        {"id": 3, "title": "Providers", "slug": "providers"},
        {"id": 4, "title": "Resources Grunderna", "slug": "resources-basics"},
        {"id": 5, "title": "State Management", "slug": "state-management"},
        {"id": 6, "title": "Variables & Outputs", "slug": "variables-outputs"},
        {"id": 7, "title": "Data Sources", "slug": "data-sources"},
        {"id": 8, "title": "Moduler Grunderna", "slug": "modules-basics"},
        {"id": 9, "title": "Count & For Each", "slug": "count-for-each"},
        {"id": 10, "title": "Dynamic Blocks", "slug": "dynamic-blocks"},
        {"id": 11, "title": "Lifecycle Management", "slug": "lifecycle-management"},
        {"id": 12, "title": "Remote State", "slug": "remote-state"},
        {"id": 13, "title": "Workspaces", "slug": "workspaces"},
        {"id": 14, "title": "Provisioners", "slug": "provisioners"},
        {"id": 15, "title": "Import & State Commands", "slug": "import-state-commands"},
        {"id": 16, "title": "Moduler Avancerat", "slug": "modules-advanced"},
        {"id": 17, "title": "Testing", "slug": "terraform-testing"},
        {"id": 18, "title": "CI/CD Integration", "slug": "cicd-integration"},
        {"id": 19, "title": "Security Best Practices", "slug": "security-practices"},
        {"id": 20, "title": "Enterprise Patterns", "slug": "enterprise-patterns"},
    ],
}
