"""
Linux V2 Nodes - Interactive Learning Engine Format
"""

from .node_1_process_v2 import LINUX_NODE_1_PROCESS_V2
from .node_2_filesystem_v2 import LINUX_NODE_2_FILESYSTEM_V2
from .node_3_fileops_v2 import LINUX_NODE_3_FILEOPS_V2
from .node_4_permissions_v2 import LINUX_NODE_4_PERMISSIONS_V2
from .node_5_textproc_v2 import LINUX_NODE_5_TEXTPROC_V2
from .node_6_editors_v2 import LINUX_NODE_6_EDITORS_V2
from .node_7_pipes_v2 import LINUX_NODE_7_PIPES_V2
from .node_8_users_v2 import LINUX_NODE_8_USERS_V2
from .node_9_packages_v2 import LINUX_NODE_9_PACKAGES_V2
from .node_10_services_v2 import LINUX_NODE_10_SERVICES_V2
from .node_11_storage_v2 import LINUX_NODE_11_STORAGE_V2
from .node_12_networking_v2 import LINUX_NODE_12_NETWORKING_V2
from .node_13_dns_v2 import LINUX_NODE_13_DNS_V2
from .node_14_firewall_v2 import LINUX_NODE_14_FIREWALL_V2
from .node_15_ssh_v2 import LINUX_NODE_15_SSH_V2
from .node_16_archiving_v2 import LINUX_NODE_16_ARCHIVING_V2
from .node_17_cron_v2 import LINUX_NODE_17_CRON_V2
from .node_18_logs_v2 import LINUX_NODE_18_LOGS_V2
from .node_19_performance_v2 import LINUX_NODE_19_PERFORMANCE_V2
from .node_20_troubleshooting_v2 import LINUX_NODE_20_TROUBLESHOOTING_V2

ALL_LINUX_V2_NODES = [
    LINUX_NODE_1_PROCESS_V2,
    LINUX_NODE_2_FILESYSTEM_V2,
    LINUX_NODE_3_FILEOPS_V2,
    LINUX_NODE_4_PERMISSIONS_V2,
    LINUX_NODE_5_TEXTPROC_V2,
    LINUX_NODE_6_EDITORS_V2,
    LINUX_NODE_7_PIPES_V2,
    LINUX_NODE_8_USERS_V2,
    LINUX_NODE_9_PACKAGES_V2,
    LINUX_NODE_10_SERVICES_V2,
    LINUX_NODE_11_STORAGE_V2,
    LINUX_NODE_12_NETWORKING_V2,
    LINUX_NODE_13_DNS_V2,
    LINUX_NODE_14_FIREWALL_V2,
    LINUX_NODE_15_SSH_V2,
    LINUX_NODE_16_ARCHIVING_V2,
    LINUX_NODE_17_CRON_V2,
    LINUX_NODE_18_LOGS_V2,
    LINUX_NODE_19_PERFORMANCE_V2,
    LINUX_NODE_20_TROUBLESHOOTING_V2,
]

__all__ = [
    "ALL_LINUX_V2_NODES",
    "LINUX_NODE_1_PROCESS_V2",
    "LINUX_NODE_2_FILESYSTEM_V2",
    "LINUX_NODE_3_FILEOPS_V2",
    "LINUX_NODE_4_PERMISSIONS_V2",
    "LINUX_NODE_5_TEXTPROC_V2",
    "LINUX_NODE_6_EDITORS_V2",
    "LINUX_NODE_7_PIPES_V2",
    "LINUX_NODE_8_USERS_V2",
    "LINUX_NODE_9_PACKAGES_V2",
    "LINUX_NODE_10_SERVICES_V2",
    "LINUX_NODE_11_STORAGE_V2",
    "LINUX_NODE_12_NETWORKING_V2",
    "LINUX_NODE_13_DNS_V2",
    "LINUX_NODE_14_FIREWALL_V2",
    "LINUX_NODE_15_SSH_V2",
    "LINUX_NODE_16_ARCHIVING_V2",
    "LINUX_NODE_17_CRON_V2",
    "LINUX_NODE_18_LOGS_V2",
    "LINUX_NODE_19_PERFORMANCE_V2",
    "LINUX_NODE_20_TROUBLESHOOTING_V2",
]
