name: Frontend CI

on:
    push:
        branches: ["main"]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Lint
              working-directory: apps/frontend
              run: npm run lint

            - name: Build
              working-directory: apps/frontend
              run: npm run build

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: frontend_build
                  path: apps/frontend/.next
